//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs
// swiftlint:disable identifier_name

/// Declares all component tokens for accordion components like `OUDSAccordionFaq`
/// Used for tokens providers like `OrangeThemeAccordionComponentTokensProvider` etc.
///
/// - Since: 3.0.0
public protocol AccordionFaqComponentTokens {

    // MARK: - Spaces

    var spaceColumnGapMobile: SpaceSemanticToken { get }
    var spaceColumnGapTablet: SpaceSemanticToken { get }
    var spacePaddingBlockMobile: SpaceSemanticToken { get }
    var spacePaddingBlockTablet: SpaceSemanticToken { get }
    var spacePaddingBlockBottomExpandContainerMobile: SpaceSemanticToken { get }
    var spacePaddingBlockBottomExpandContainerTablet: SpaceSemanticToken { get }
    var spacePaddingBlockBottomSlotListItemContainerMobile: SpaceSemanticToken { get }
    var spacePaddingBlockBottomSlotListItemContainerTablet: SpaceSemanticToken { get }

    // MARK: - Size

    var sizeIconMobile: SizeSemanticToken { get }
    var sizeIconTablet: SizeSemanticToken { get }
    var sizeExpandingIndicatorMobile: SizeSemanticToken { get }
    var sizeExpandingIndicatorTablet: SizeSemanticToken { get }
    var sizeMinHeightMobile: SizeSemanticToken { get }
    var sizeMinHeightTablet: SizeSemanticToken { get }
}

// swiftlint:enable missing_docs
// swiftlint:enable identifier_name
