//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs
// swiftlint:disable identifier_name

/// Declares all component tokens for bar components l
/// Use for tokens providers like `OrangeThemeBarComponentTokensProvider`.
///
/// - Since: 0.22.0
public protocol BarComponentTokens {

    // MARK: - Colors

    var colorBgOpaque: MultipleColorSemanticToken { get }
    var colorBgTranslucent: MultipleColorSemanticToken { get }
    var colorContentSelectedEnabled: MultipleColorSemanticToken { get }
    var colorContentSelectedHover: MultipleColorSemanticToken { get }
    var colorContentSelectedPressed: MultipleColorSemanticToken { get }
    var colorContentSelectedFocus: MultipleColorSemanticToken { get }
    var colorContentUnselectedEnabled: MultipleColorSemanticToken { get }
    var colorContentUnselectedHover: MultipleColorSemanticToken { get }
    var colorContentUnselectedPressed: MultipleColorSemanticToken { get }
    var colorContentUnselectedFocus: MultipleColorSemanticToken { get }
    var colorContentOnAccent: MultipleColorSemanticToken { get }
    var colorBorderBadge: MultipleColorSemanticToken { get }
    var colorActiveIndicatorCustomSelectedEnabled: MultipleColorSemanticToken { get }
    var colorActiveIndicatorCustomSelectedHover: MultipleColorSemanticToken { get }
    var colorActiveIndicatorCustomSelectedPressed: MultipleColorSemanticToken { get }
    var colorActiveIndicatorCustomSelectedFocus: MultipleColorSemanticToken { get }

    // MARK: - Opacities

    var opacityActiveIndicatorCustom: OpacitySemanticToken { get }

    // MARK: - Effects

    var effectBgBlur: EffectSemanticToken { get }

    // MARK: - Borders

    var borderRadiusActiveIndicatorCustomTop: BorderRadiusSemanticToken { get }
    var borderRadiusActiveIndicatorCustomBottom: BorderRadiusSemanticToken { get }

    // MARK: - Sizes

    var sizeWidthActiveIndicatorCustomTop: SizeSemanticToken { get }
    var sizeWidthActiveIndicatorCustomBottom: SizeSemanticToken { get }
    var sizeHeightActiveIndicatorCustom: SizeSemanticToken { get }
}

// swiftlint:enable missing_docs
// swiftlint:enable identifier_name
