//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for links components like `OUDSBulletList`
/// Use for tokens providers like `OrangeThemeBulletListComponentTokensProvider`.
///
/// - Since: 0.10.0
public protocol BulletListComponentTokens {

    // MARK: - Spaces

    var bulletListSpaceColumnGapBodyLarge: SpaceSemanticToken { get }
    var bulletListSpaceColumnGapBodyMedium: SpaceSemanticToken { get }
    var bulletListSpacePaddingBlockBodyLarge: SpaceSemanticToken { get }
    var bulletListSpacePaddingBlockBodyMedium: SpaceSemanticToken { get }
    var bulletListSpacePaddingInlineLevel0: SpaceSemanticToken { get }
    var bulletListSpacePaddingInlineLevel1: SpaceSemanticToken { get }
    var bulletListSpacePaddingInlineLevel2: SpaceSemanticToken { get }
}

// swiftlint:enable missing_docs
