//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for buttons components like `OUDSButton` in **monochrome mode**.
/// Use for tokens providers like `OrangeThemeButtonComponentTokensProvider`.
///
/// - Since: 0.16.0
public protocol ButtonMonoComponentTokens {

    // NOTE: Tokens prefixed by "mono" even id redundant with tokens provider and protocol names
    // because some of the tokens exist in button component tokens gathered in same provider

    var monoColorBgDefaultEnabled: MultipleColorSemanticToken { get }
    var monoColorBgDefaultHover: MultipleColorSemanticToken { get }
    var monoColorBgDefaultPressed: MultipleColorSemanticToken { get }
    var monoColorBgDefaultLoading: MultipleColorSemanticToken { get }
    var monoColorBgDefaultDisabled: MultipleColorSemanticToken { get }
    var monoColorBgDefaultFocus: MultipleColorSemanticToken { get }
    var monoColorBgMinimalHover: MultipleColorSemanticToken { get }
    var monoColorBgMinimalPressed: MultipleColorSemanticToken { get }
    var monoColorBgMinimalFocus: MultipleColorSemanticToken { get }
    var monoColorBgStrongEnabled: MultipleColorSemanticToken { get }
    var monoColorBgStrongHover: MultipleColorSemanticToken { get }
    var monoColorBgStrongPressed: MultipleColorSemanticToken { get }
    var monoColorBgStrongLoading: MultipleColorSemanticToken { get }
    var monoColorBgStrongDisabled: MultipleColorSemanticToken { get }
    var monoColorBgStrongFocus: MultipleColorSemanticToken { get }
    var monoColorContentDefaultEnabled: MultipleColorSemanticToken { get }
    var monoColorContentDefaultHover: MultipleColorSemanticToken { get }
    var monoColorContentDefaultPressed: MultipleColorSemanticToken { get }
    var monoColorContentDefaultLoading: MultipleColorSemanticToken { get }
    var monoColorContentDefaultDisabled: MultipleColorSemanticToken { get }
    var monoColorContentDefaultFocus: MultipleColorSemanticToken { get }
    var monoColorContentMinimalEnabled: MultipleColorSemanticToken { get }
    var monoColorContentMinimalHover: MultipleColorSemanticToken { get }
    var monoColorContentMinimalPressed: MultipleColorSemanticToken { get }
    var monoColorContentMinimalLoading: MultipleColorSemanticToken { get }
    var monoColorContentMinimalDisabled: MultipleColorSemanticToken { get }
    var monoColorContentMinimalFocus: MultipleColorSemanticToken { get }
    var monoColorContentStrongEnabled: MultipleColorSemanticToken { get }
    var monoColorContentStrongHover: MultipleColorSemanticToken { get }
    var monoColorContentStrongPressed: MultipleColorSemanticToken { get }
    var monoColorContentStrongLoading: MultipleColorSemanticToken { get }
    var monoColorContentStrongDisabled: MultipleColorSemanticToken { get }
    var monoColorContentStrongFocus: MultipleColorSemanticToken { get }
    var monoColorBorderDefaultEnabled: MultipleColorSemanticToken { get }
    var monoColorBorderDefaultHover: MultipleColorSemanticToken { get }
    var monoColorBorderDefaultPressed: MultipleColorSemanticToken { get }
    var monoColorBorderDefaultLoading: MultipleColorSemanticToken { get }
    var monoColorBorderDefaultDisabled: MultipleColorSemanticToken { get }
    var monoColorBorderDefaultFocus: MultipleColorSemanticToken { get }
}

// swiftlint:enable missing_docs
