//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for buttons components like `OUDSButton`
/// Use for tokens providers like `OrangeThemeButtonComponentTokensProvider`.
///
/// - Since: 0.9.0
public protocol ButtonComponentTokens {

    // MARK: - Size

    var sizeMaxHeightIconOnly: SizeSemanticToken { get }
    var sizeMinHeight: SizeSemanticToken { get }
    var sizeMinWidth: SizeSemanticToken { get }
    var sizeIcon: SizeSemanticToken { get }
    var sizeIconOnly: SizeSemanticToken { get }
    var sizeLoader: SizeSemanticToken { get }

    // MARK: - Space

    var spaceColumnGapIcon: SpaceSemanticToken { get }
    var spaceInsetIconOnly: SpaceSemanticToken { get }
    var spacePaddingBlock: SpaceSemanticToken { get }
    var spacePaddingInlineChevronEnd: SpaceSemanticToken { get }
    var spacePaddingInlineChevronStart: SpaceSemanticToken { get }
    var spacePaddingInlineEndIconStart: SpaceSemanticToken { get }
    var spacePaddingInlineIconNone: SpaceSemanticToken { get }
    var spacePaddingInlineIconStart: SpaceSemanticToken { get }
    var spacePaddingInlineStartIconEnd: SpaceSemanticToken { get }

    // MARK: - Border

    var borderRadiusDefault: BorderRadiusSemanticToken { get }
    var borderRadiusRounded: BorderRadiusSemanticToken { get }
    var borderRadiusSocial: BorderRadiusSemanticToken { get }
    var borderWidthDefault: BorderWidthSemanticToken { get }
    var borderWidthDefaultInteraction: BorderWidthSemanticToken { get }
    var borderWidthDefaultInteractionMono: BorderWidthSemanticToken { get }

    // MARK: - Color - Background

    var colorBgDefaultDisabled: MultipleColorSemanticToken { get }
    var colorBgDefaultEnabled: MultipleColorSemanticToken { get }
    var colorBgDefaultFocus: MultipleColorSemanticToken { get }
    var colorBgDefaultHover: MultipleColorSemanticToken { get }
    var colorBgDefaultLoading: MultipleColorSemanticToken { get }
    var colorBgDefaultPressed: MultipleColorSemanticToken { get }
    var colorBgMinimalFocus: MultipleColorSemanticToken { get }
    var colorBgMinimalHover: MultipleColorSemanticToken { get }
    var colorBgMinimalPressed: MultipleColorSemanticToken { get }

    // MARK: - Color - Brand

    var colorBgBrandEnabled: MultipleColorSemanticToken { get }
    var colorBgBrandHover: MultipleColorSemanticToken { get }
    var colorBgBrandPressed: MultipleColorSemanticToken { get }
    var colorBgBrandLoading: MultipleColorSemanticToken { get }
    var colorBgBrandFocus: MultipleColorSemanticToken { get }
    var colorContentBrandEnabled: MultipleColorSemanticToken { get }
    var colorContentBrandHover: MultipleColorSemanticToken { get }
    var colorContentBrandPressed: MultipleColorSemanticToken { get }
    var colorContentBrandLoading: MultipleColorSemanticToken { get }
    var colorContentBrandFocus: MultipleColorSemanticToken { get }

    // MARK: - Color - Border

    var colorBorderDefaultDisabled: MultipleColorSemanticToken { get }
    var colorBorderDefaultEnabled: MultipleColorSemanticToken { get }
    var colorBorderDefaultFocus: MultipleColorSemanticToken { get }
    var colorBorderDefaultHover: MultipleColorSemanticToken { get }
    var colorBorderDefaultLoading: MultipleColorSemanticToken { get }
    var colorBorderDefaultPressed: MultipleColorSemanticToken { get }

    // MARK: - Color - Content

    var colorContentDefaultDisabled: MultipleColorSemanticToken { get }
    var colorContentDefaultEnabled: MultipleColorSemanticToken { get }
    var colorContentDefaultFocus: MultipleColorSemanticToken { get }
    var colorContentDefaultHover: MultipleColorSemanticToken { get }
    var colorContentDefaultLoading: MultipleColorSemanticToken { get }
    var colorContentDefaultPressed: MultipleColorSemanticToken { get }
    var colorContentMinimalDisabled: MultipleColorSemanticToken { get }
    var colorContentMinimalEnabled: MultipleColorSemanticToken { get }
    var colorContentMinimalFocus: MultipleColorSemanticToken { get }
    var colorContentMinimalHover: MultipleColorSemanticToken { get }
    var colorContentMinimalLoading: MultipleColorSemanticToken { get }
    var colorContentMinimalPressed: MultipleColorSemanticToken { get }
}

// swiftlint:enable missing_docs
