//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for buttons components like `OUDSButton`
/// Use for tokens providers like `OrangeThemeButtonComponentTokensProvider`.
///
/// - Since: 0.9.0
public protocol ButtonComponentTokens {

    // MARK: - Size

    var buttonSizeMaxHeightIconOnly: SizeSemanticToken { get }
    var buttonSizeMinHeight: SizeSemanticToken { get }
    var buttonSizeMinWidth: SizeSemanticToken { get }
    var buttonSizeIcon: SizeSemanticToken { get }
    var buttonSizeIconOnly: SizeSemanticToken { get }
    var buttonSizeLoader: SizeSemanticToken { get }

    // MARK: - Space

    var buttonSpaceColumnGapIcon: SpaceSemanticToken { get }
    var buttonSpaceInsetIconOnly: SpaceSemanticToken { get }
    var buttonSpacePaddingBlock: SpaceSemanticToken { get }
    var buttonSpacePaddingInlineChevronEnd: SpaceSemanticToken { get }
    var buttonSpacePaddingInlineChevronStart: SpaceSemanticToken { get }
    var buttonSpacePaddingInlineEndIconStart: SpaceSemanticToken { get }
    var buttonSpacePaddingInlineIconNone: SpaceSemanticToken { get }
    var buttonSpacePaddingInlineIconStart: SpaceSemanticToken { get }
    var buttonSpacePaddingInlineStartIconEnd: SpaceSemanticToken { get }

    // MARK: - Border

    var buttonBorderRadiusDefault: BorderRadiusSemanticToken { get }
    var buttonBorderRadiusRounded: BorderRadiusSemanticToken { get }
    var buttonBorderRadiusSocial: BorderRadiusSemanticToken { get }
    var buttonBorderWidthDefault: BorderWidthSemanticToken { get }
    var buttonBorderWidthDefaultInteraction: BorderWidthSemanticToken { get }
    var buttonBorderWidthDefaultInteractionMono: BorderWidthSemanticToken { get }

    // MARK: - Color - Background

    var buttonColorBgDefaultDisabled: MultipleColorSemanticTokens { get }
    var buttonColorBgDefaultEnabled: MultipleColorSemanticTokens { get }
    var buttonColorBgDefaultFocus: MultipleColorSemanticTokens { get }
    var buttonColorBgDefaultHover: MultipleColorSemanticTokens { get }
    var buttonColorBgDefaultLoading: MultipleColorSemanticTokens { get }
    var buttonColorBgDefaultPressed: MultipleColorSemanticTokens { get }
    var buttonColorBgMinimalFocus: MultipleColorSemanticTokens { get }
    var buttonColorBgMinimalHover: MultipleColorSemanticTokens { get }
    var buttonColorBgMinimalPressed: MultipleColorSemanticTokens { get }

    // MARK: - Color - Brand

    var buttonColorBgBrandEnabled: MultipleColorSemanticTokens { get }
    var buttonColorBgBrandHover: MultipleColorSemanticTokens { get }
    var buttonColorBgBrandPressed: MultipleColorSemanticTokens { get }
    var buttonColorBgBrandLoading: MultipleColorSemanticTokens { get }
    var buttonColorBgBrandFocus: MultipleColorSemanticTokens { get }
    var buttonColorContentBrandEnabled: MultipleColorSemanticTokens { get }
    var buttonColorContentBrandHover: MultipleColorSemanticTokens { get }
    var buttonColorContentBrandPressed: MultipleColorSemanticTokens { get }
    var buttonColorContentBrandLoading: MultipleColorSemanticTokens { get }
    var buttonColorContentBrandFocus: MultipleColorSemanticTokens { get }

    // MARK: - Color - Border

    var buttonColorBorderDefaultDisabled: MultipleColorSemanticTokens { get }
    var buttonColorBorderDefaultEnabled: MultipleColorSemanticTokens { get }
    var buttonColorBorderDefaultFocus: MultipleColorSemanticTokens { get }
    var buttonColorBorderDefaultHover: MultipleColorSemanticTokens { get }
    var buttonColorBorderDefaultLoading: MultipleColorSemanticTokens { get }
    var buttonColorBorderDefaultPressed: MultipleColorSemanticTokens { get }

    // MARK: - Color - Content

    var buttonColorContentDefaultDisabled: MultipleColorSemanticTokens { get }
    var buttonColorContentDefaultEnabled: MultipleColorSemanticTokens { get }
    var buttonColorContentDefaultFocus: MultipleColorSemanticTokens { get }
    var buttonColorContentDefaultHover: MultipleColorSemanticTokens { get }
    var buttonColorContentDefaultLoading: MultipleColorSemanticTokens { get }
    var buttonColorContentDefaultPressed: MultipleColorSemanticTokens { get }
    var buttonColorContentMinimalDisabled: MultipleColorSemanticTokens { get }
    var buttonColorContentMinimalEnabled: MultipleColorSemanticTokens { get }
    var buttonColorContentMinimalFocus: MultipleColorSemanticTokens { get }
    var buttonColorContentMinimalHover: MultipleColorSemanticTokens { get }
    var buttonColorContentMinimalLoading: MultipleColorSemanticTokens { get }
    var buttonColorContentMinimalPressed: MultipleColorSemanticTokens { get }
}

// swiftlint:enable missing_docs
