//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for buttons components like `OUDSButton` in **monochrome mode**.
/// Use for tokens providers like `OrangeThemeButtonComponentTokensProvider`.
///
/// - Since: 0.16.0
public protocol ButtonMonoComponentTokens {
    var monoColorBgDefaultEnabled: MultipleColorSemanticTokens { get }
    var monoColorBgDefaultHover: MultipleColorSemanticTokens { get }
    var monoColorBgDefaultPressed: MultipleColorSemanticTokens { get }
    var monoColorBgDefaultLoading: MultipleColorSemanticTokens { get }
    var monoColorBgDefaultDisabled: MultipleColorSemanticTokens { get }
    var monoColorBgDefaultFocus: MultipleColorSemanticTokens { get }
    var monoColorBgMinimalHover: MultipleColorSemanticTokens { get }
    var monoColorBgMinimalPressed: MultipleColorSemanticTokens { get }
    var monoColorBgMinimalFocus: MultipleColorSemanticTokens { get }
    var monoColorBgStrongEnabled: MultipleColorSemanticTokens { get }
    var monoColorBgStrongHover: MultipleColorSemanticTokens { get }
    var monoColorBgStrongPressed: MultipleColorSemanticTokens { get }
    var monoColorBgStrongLoading: MultipleColorSemanticTokens { get }
    var monoColorBgStrongDisabled: MultipleColorSemanticTokens { get }
    var monoColorBgStrongFocus: MultipleColorSemanticTokens { get }
    var monoColorContentDefaultEnabled: MultipleColorSemanticTokens { get }
    var monoColorContentDefaultHover: MultipleColorSemanticTokens { get }
    var monoColorContentDefaultPressed: MultipleColorSemanticTokens { get }
    var monoColorContentDefaultLoading: MultipleColorSemanticTokens { get }
    var monoColorContentDefaultDisabled: MultipleColorSemanticTokens { get }
    var monoColorContentDefaultFocus: MultipleColorSemanticTokens { get }
    var monoColorContentMinimalEnabled: MultipleColorSemanticTokens { get }
    var monoColorContentMinimalHover: MultipleColorSemanticTokens { get }
    var monoColorContentMinimalPressed: MultipleColorSemanticTokens { get }
    var monoColorContentMinimalLoading: MultipleColorSemanticTokens { get }
    var monoColorContentMinimalDisabled: MultipleColorSemanticTokens { get }
    var monoColorContentMinimalFocus: MultipleColorSemanticTokens { get }
    var monoColorContentStrongEnabled: MultipleColorSemanticTokens { get }
    var monoColorContentStrongHover: MultipleColorSemanticTokens { get }
    var monoColorContentStrongPressed: MultipleColorSemanticTokens { get }
    var monoColorContentStrongLoading: MultipleColorSemanticTokens { get }
    var monoColorContentStrongDisabled: MultipleColorSemanticTokens { get }
    var monoColorContentStrongFocus: MultipleColorSemanticTokens { get }
    var monoColorBorderDefaultEnabled: MultipleColorSemanticTokens { get }
    var monoColorBorderDefaultHover: MultipleColorSemanticTokens { get }
    var monoColorBorderDefaultPressed: MultipleColorSemanticTokens { get }
    var monoColorBorderDefaultLoading: MultipleColorSemanticTokens { get }
    var monoColorBorderDefaultDisabled: MultipleColorSemanticTokens { get }
    var monoColorBorderDefaultFocus: MultipleColorSemanticTokens { get }
}

// swiftlint:enable missing_docs
