//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for components using control item layout like `OUDSSwitch`, `OUDSCheckboxItem` and `OUDSRadioButton`
/// Use for tokens providers like `OrangeThemeControlItemComponentTokensProvider`.
///
/// - Since: 0.11.0
public protocol ControlItemComponentTokens {

    // MARK: - Sizes

    var controlItemSizeMinHeight: SizeSemanticToken { get }
    var controlItemSizeMinWidth: SizeSemanticToken { get }
    var controlItemSizeMaxHeightAssetsContainer: SizeSemanticToken { get }
    var controlItemSizeIcon: SizeSemanticToken { get }
    var controlItemSizeLoader: SizeSemanticToken { get }

    // MARK: - Colors

    var controlItemColorBgHover: MultipleColorSemanticTokens { get }
    var controlItemColorBgPressed: MultipleColorSemanticTokens { get }
    var controlItemColorBgLoading: MultipleColorSemanticTokens { get }
    var controlItemColorBgFocus: MultipleColorSemanticTokens { get }
    var controlItemColorContentLoader: MultipleColorSemanticTokens { get }

    // MARK: - Spaces

    var controlItemSpaceColumnGap: SpaceSemanticToken { get }
    var controlItemSpaceRowGap: SpaceSemanticToken { get }
    var controlItemSpaceInset: SpaceSemanticToken { get }

    // MARK: - Borders

    var controlItemBorderRadius: BorderRadiusSemanticToken { get }
    var controlItemBorderRadiusItemOnly: BorderRadiusSemanticToken { get }
}

// swiftlint:enable missing_docs
