//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs
// swiftlint:disable identifier_name

/// Declares all component tokens for components using control item layout like `OUDSSwitch`, `OUDSCheckboxItem` and `OUDSRadioButton`
/// Use for tokens providers like `OrangeThemeControlItemComponentTokensProvider`.
///
/// - Since: 0.11.0
public protocol ControlItemComponentTokens {

    // MARK: - Colors

    var colorBgCurrentEnabled: MultipleColorSemanticToken { get }
    var colorBgCurrentHover: MultipleColorSemanticToken { get }
    var colorBgCurrentPressed: MultipleColorSemanticToken { get }
    var colorBgCurrentDisabled: MultipleColorSemanticToken { get }
    var colorBgCurrentFocus: MultipleColorSemanticToken { get }
    var colorContentCurrentEnabled: MultipleColorSemanticToken { get }
    var colorContentCurrentHover: MultipleColorSemanticToken { get }
    var colorContentCurrentPressed: MultipleColorSemanticToken { get }
    var colorContentCurrentDisabled: MultipleColorSemanticToken { get }
    var colorContentCurrentFocus: MultipleColorSemanticToken { get }
    var colorBadgeSafetyArea: MultipleColorSemanticToken { get }

    // MARK: - Fonts

    var fontSizeAvatarInitialXlarge: FontSizeSemanticToken { get }
    var fontLineHeightAvatarInitialXlarge: FontLineHeightSemanticToken { get }
    var fontLetterSpacingAvatarInitialXlarge: FontLetterSpacingSemanticToken { get }

    // MARK: - Opacities

    var opacityCurrentIndicator: OpacitySemanticToken { get }
    var opacityCurrentDivider: OpacitySemanticToken { get }

    // MARK: - Borders

    var borderWidthDefault: BorderWidthSemanticToken { get }
    var borderWidthCurrentPage: BorderWidthSemanticToken { get }
    var borderRadiusDefault: BorderRadiusSemanticToken { get }
    var borderRadiusRounded: BorderRadiusSemanticToken { get }
    var borderRadiusMedia: BorderRadiusSemanticToken { get }
    var borderRadiusMediaRoundedCorner: BorderRadiusSemanticToken { get }
    var borderRadiusCurrentIndicator: BorderRadiusSemanticToken { get }

    // MARK: - Spaces

    var spacePaddingInline: SpaceSemanticToken { get }
    var spaceColumnGap: SpaceSemanticToken { get }
    var spaceRowGap: SpaceSemanticToken { get }
    var spacePaddingBlockTopHelperText: SpaceSemanticToken { get }
    var spacePaddingBlockBottomSlot: SpaceSemanticToken { get }
    var spacePaddingBlockDensityCompact: SpaceSemanticToken { get }
    var spacePaddingBlockDensityCompactTopAlignmentTopTextContainer: SpaceSemanticToken { get }
    var spacePaddingBlockDensityCompactTopAlignmentTopCounterweight: SpaceSemanticToken { get }
    var spacePaddingBlockDensityCompactBottomExpandContainer: SpaceSemanticToken { get }
    var spacePaddingBlockDensityDefault: SpaceSemanticToken { get }
    var spacePaddingBlockDensityDefaultTopAlignmentTopTextContainer: SpaceSemanticToken { get }
    var spacePaddingBlockDensityDefaultTopAlignmentTopCounterweight: SpaceSemanticToken { get }
    var spacePaddingBlockDensityDefaultBottomExpandContainer: SpaceSemanticToken { get }

    // MARK: - Sizes

    var sizeControlIndicator: SizeSemanticToken { get }
    var sizeMinHeightCompact: SizeSemanticToken { get }
    var sizeMinHeightDefault: SizeSemanticToken { get }
    var sizeMinWidth: SizeSemanticToken { get }
    var sizeMaxWidth: SizeSemanticToken { get }
    var sizeAssetSmall: SizeSemanticToken { get }
    var sizeAssetMedium: SizeSemanticToken { get }
    var sizeAssetLarge: SizeSemanticToken { get }
    var sizeAssetXlarge: SizeSemanticToken { get }
    var sizeFlagHeight: SizeSemanticToken { get }
    var sizeCurrentIndicatorWidth: SizeSemanticToken { get }

    @available(*, deprecated, message: "Use spacePaddingBlockDensityCompactTopAlignmentTopTextContainer instead, will be removed soon")
    var spacePaddingBlockDensityCompactTopAlignmentTopText_container: SpaceSemanticToken { get }

    // MARK: - Old tokens to keep until components updates
    // Will be removed with next component update
    // See https://github.com/Orange-OpenSource/ouds-ios#1437

    var colorBgHover: MultipleColorSemanticToken { get }
    var colorBgPressed: MultipleColorSemanticToken { get }
    var colorBgLoading: MultipleColorSemanticToken { get }
    var colorBgFocus: MultipleColorSemanticToken { get }
    var colorContentLoader: MultipleColorSemanticToken { get }

    var borderRadius: BorderRadiusSemanticToken { get }
    var borderRadiusItemOnly: BorderRadiusSemanticToken { get }

    var spacePaddingBlockDefault: SpaceSemanticToken { get }
    var spacePaddingInlineErrorIcon: SpaceSemanticToken { get }

    var sizeMaxHeightAssetsContainer: SizeSemanticToken { get }
    var sizeErrorIcon: SizeSemanticToken { get }
    var sizeLoader: SizeSemanticToken { get }
}

// swiftlint:enable missing_docs
// swiftlint:enable identifier_name
