//
// Software Name: OUDSThemesContract iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for components using control item layout like `OUDSSwitch`, `OUDSCheckboxItem` and `OUDSRadioButton`
/// Use for tokens providers like `OrangeThemeControlItemComponentTokensProvider`.
///
/// - Since: 0.11.0
public protocol ControlItemComponentTokens {

    // MARK: - Sizes

    var sizeMinHeight: SizeSemanticToken { get }
    var sizeMinWidth: SizeSemanticToken { get }
    var sizeMaxWidth: SizeSemanticToken { get }
    var sizeMaxHeightAssetsContainer: SizeSemanticToken { get }
    var sizeIcon: SizeSemanticToken { get }
    var sizeErrorIcon: SizeSemanticToken { get }
    var sizeLoader: SizeSemanticToken { get }

    // MARK: - Colors

    var colorBgHover: MultipleColorSemanticTokens { get }
    var colorBgPressed: MultipleColorSemanticTokens { get }
    var colorBgLoading: MultipleColorSemanticTokens { get }
    var colorBgFocus: MultipleColorSemanticTokens { get }
    var colorContentLoader: MultipleColorSemanticTokens { get }

    // MARK: - Spaces

    var spaceColumnGap: SpaceSemanticToken { get }
    var spaceRowGap: SpaceSemanticToken { get }
    var spacePaddingBlock: SpaceSemanticToken { get }
    var spacePaddingInline: SpaceSemanticToken { get }
    var spacePaddingInlineErrorIcon: SpaceSemanticToken { get }

    // MARK: - Borders

    var borderRadius: BorderRadiusSemanticToken { get }
    var borderRadiusItemOnly: BorderRadiusSemanticToken { get }
}

// swiftlint:enable missing_docs
