//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for tags components like `OUDSInputTag`
/// Used for tokens providers like `OrangeThemeInputTagComponentTokensProvider`.
///
/// - Since: 0.17.0
public protocol InputTagComponentTokens {

    // MARK: - Colors

    var colorBgEnabled: MultipleColorSemanticToken { get }
    var colorBgHover: MultipleColorSemanticToken { get }
    var colorBgPressed: MultipleColorSemanticToken { get }
    var colorBgFocus: MultipleColorSemanticToken { get }
    var colorContentEnabled: MultipleColorSemanticToken { get }
    var colorContentHover: MultipleColorSemanticToken { get }
    var colorContentPressed: MultipleColorSemanticToken { get }
    var colorContentFocus: MultipleColorSemanticToken { get }
    var colorBorderEnabled: MultipleColorSemanticToken { get }
    var colorBorderHover: MultipleColorSemanticToken { get }
    var colorBorderPressed: MultipleColorSemanticToken { get }
    var colorBorderFocus: MultipleColorSemanticToken { get }

    // MARK: - Borders

    var borderWidthDefault: BorderWidthSemanticToken { get }
    var borderWidthDefaultInteraction: BorderWidthSemanticToken { get }
}

// swiftlint:enable missing_docs
