//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs
// swiftlint:disable identifier_name

/// Declares all component tokens for links components like `OUDSInputText`
/// Use for tokens providers like `OrangeThemeInputTextComponentTokensProvider`.
///
/// - Since: 0.10.0
public protocol InputTextComponentTokens {

    // MARK: - Sizes

    var inputTextSizeMaxWidth: SizeSemanticToken { get }
    var inputTextSizeMinWidth: SizeSemanticToken { get }

    // MARK: - Colors

    var inputTextColorBgDefaultDisabled: MultipleColorSemanticTokens { get }
    var inputTextColorBgDefaultEnabled: MultipleColorSemanticTokens { get }
    var inputTextColorBgDefaultFocus: MultipleColorSemanticTokens { get }
    var inputTextColorBgDefaultHover: MultipleColorSemanticTokens { get }
    var inputTextColorBgDefaultLoading: MultipleColorSemanticTokens { get }
    var inputTextColorBgDefaultPressed: MultipleColorSemanticTokens { get }
    var inputTextColorContentDefaultDisabled: MultipleColorSemanticTokens { get }
    var inputTextColorContentDefaultEnabled: MultipleColorSemanticTokens { get }
    var inputTextColorContentDefaultFocus: MultipleColorSemanticTokens { get }
    var inputTextColorContentDefaultHover: MultipleColorSemanticTokens { get }
    var inputTextColorContentDefaultLoading: MultipleColorSemanticTokens { get }
    var inputTextColorContentDefaultPressed: MultipleColorSemanticTokens { get }

    // MARK: - Spaces

    var inputTextSpaceInsetIconAlone: SpaceSemanticToken { get }
    var inputTextSpacePaddingBlock: SpaceSemanticToken { get }
    var inputTextSpacePaddingInlineContainerEnd: SpaceSemanticToken { get }
    var inputTextSpacePaddingInlineContainerStart: SpaceSemanticToken { get }
    var inputTextSpacePaddingInlineIconEnd: SpaceSemanticToken { get }
    var inputTextSpacePaddingInlinePrefixTextEnd: SpaceSemanticToken { get }
    var inputTextSpacePaddingInlineSuffixTextEnd: SpaceSemanticToken { get }
    var inputTextSpacePaddingInlineTextEnd: SpaceSemanticToken { get }
}

// swiftlint:enable missing_docs
// swiftlint:enable identifier_name
