//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for input components like `OUDSProgressIndicator`
/// Use for tokens providers like `OrangeThemeProgressIndicatorComponentTokensProvider`.
///
/// - Since: 3.0.0
public protocol ProgressIndicatorComponentTokens {

    // MARK: - Colors

    var colorContentTrack: MultipleColorSemanticToken { get }

    // MARK: - Borders

    var borderRadiusDefault: BorderRadiusSemanticToken { get }
    var borderRadiusRounded: BorderRadiusSemanticToken { get }

    // MARK: - Spaces

    var spacePaddingBlock: SpaceSemanticToken { get }
    var spaceColumnGap: SpaceSemanticToken { get }

    // MARK: - Sizes

    var sizeLinearIndicatorHeight: SizeSemanticToken { get }
}

// swiftlint:enable missing_docs
