//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable identifier_name
// swiftlint:disable missing_docs

/// Declares all component tokens for tags components like `OUDSQuantityInput`
/// Used for tokens providers like `OrangeThemeQuantityInputComponentTokensProvider`.
///
/// - Since: 0.17.0
public protocol QuantityInputComponentTokens {

    // MARK: - Spaces

    var spaceColumnGapDefault: SpaceSemanticToken { get }
    var spaceColumnGapLeadingIcon: SpaceSemanticToken { get }
    var spaceColumnGapQuantitySelector: SpaceSemanticToken { get }

    // MARK: - Sizes

    var sizeMinWidth: SizeSemanticToken { get }
    var sizeMaxWidth: SizeSemanticToken { get }
}

// swiftlint:enable identifier_name
// swiftlint:enable missing_docs
