//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for links components like `OUDSSelect`
/// Use for tokens providers like `OrangeThemeSelectComponentTokensProvider`.
///
/// - Since: 0.10.0
public protocol SelectComponentTokens {

    // MARK: - Size

    var selectSizeMaxHeightContainerIcon: SizeSemanticToken { get }
    var selectSizeMinHeight: SizeSemanticToken { get }
    var selectSizeMinHeightIconOnly: SizeSemanticToken { get }
    var selectSizeMinWidth: SizeSemanticToken { get }
    var selectSizeMinWidthIconOnly: SizeSemanticToken { get }
    var selectSizeCheckBox: SizeSemanticToken { get }
    var selectSizeIcon: SizeSemanticToken { get }
    var selectSizeLoader: SizeSemanticToken { get }

    // MARK: - Colors

    var selectColorBgDisabled: MultipleColorSemanticTokens { get }
    var selectColorBgEnabled: MultipleColorSemanticTokens { get }
    var selectColorBgFocus: MultipleColorSemanticTokens { get }
    var selectColorBgHover: MultipleColorSemanticTokens { get }
    var selectColorBgLoading: MultipleColorSemanticTokens { get }
    var selectColorBgPressed: MultipleColorSemanticTokens { get }
    var selectColorBorderDisabled: MultipleColorSemanticTokens { get }
    var selectColorBorderEnabled: MultipleColorSemanticTokens { get }
    var selectColorBorderHover: MultipleColorSemanticTokens { get }
    var selectColorBorderLoading: MultipleColorSemanticTokens { get }
    var selectColorBorderPressed: MultipleColorSemanticTokens { get }
    var selectColorContentDisabled: MultipleColorSemanticTokens { get }
    var selectColorContentEnabled: MultipleColorSemanticTokens { get }
    var selectColorContentFocus: MultipleColorSemanticTokens { get }
    var selectColorContentHelperTextDisabled: MultipleColorSemanticTokens { get }
    var selectColorContentHelperTextEnabled: MultipleColorSemanticTokens { get }
    var selectColorContentHelperTextFocus: MultipleColorSemanticTokens { get }
    var selectColorContentHelperTextHover: MultipleColorSemanticTokens { get }
    var selectColorContentHelperTextLoading: MultipleColorSemanticTokens { get }
    var selectColorContentHelperTextPressed: MultipleColorSemanticTokens { get }
    var selectColorContentHover: MultipleColorSemanticTokens { get }
    var selectColorContentLoading: MultipleColorSemanticTokens { get }
    var selectColorContentPressed: MultipleColorSemanticTokens { get }

    // MARK: - Space

    var selectSpaceColumnGap: SpaceSemanticToken { get }
    var selectSpacePaddingInset: SpaceSemanticToken { get }
    var selectSpaceRowGap: SpaceSemanticToken { get }
}

// swiftlint:enable missing_docs
