//
// Software Name: OUDSThemesContract iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for tags components like `OUDSTag`
/// Used for tokens providers like `OrangeThemeTagComponentTokensProvider`.
///
/// - Since: 0.10.0
public protocol TagComponentTokens {

    // MARK: - Borders

    var borderRadius: BorderRadiusSemanticToken { get }

    // MARK: - Sizes

    var sizeAssetDefault: SizeSemanticToken { get }
    var sizeAssetSmall: SizeSemanticToken { get }
    var sizeMinHeightDefault: SizeSemanticToken { get }
    var sizeMinWidthDefault: SizeSemanticToken { get }
    var sizeMinHeightSmall: SizeSemanticToken { get }
    var sizeMinWidthSmall: SizeSemanticToken { get }
    var sizeMinHeightInteractiveArea: SizeSemanticToken { get }

    // MARK: - Spaces

    var spacePaddingBlockSmall: SpaceSemanticToken { get }
    var spacePaddingBlockDefault: SpaceSemanticToken { get }
    var spacePaddingInlineSmall: SpaceSemanticToken { get }
    var spacePaddingInlineDefault: SpaceSemanticToken { get }
    var spacePaddingInlineAssetSmall: SpaceSemanticToken { get }
    var spacePaddingInlineAssetDefault: SpaceSemanticToken { get }
    var spaceInsetIconSmall: SpaceSemanticToken { get }
    var spaceInsetBulletSmall: SpaceSemanticToken { get }
    var spaceInsetLoaderSmall: SpaceSemanticToken { get }
    var spaceInsetIconDefault: SpaceSemanticToken { get }
    var spaceInsetBulletDefault: SpaceSemanticToken { get }
    var spaceInsetLoaderDefault: SpaceSemanticToken { get }
    var spaceColumnGapSmall: SpaceSemanticToken { get }
    var spaceColumnGapDefault: SpaceSemanticToken { get }
}

// swiftlint:enable missing_docs
