//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// Declares all component tokens for input components like `OUDSTextArea`
/// Used for tokens providers like `OrangeThemeTextAreaComponentTokensProvider`.
///
/// - Since: 0.17.0
public protocol TextAreaComponentTokens {

    // MARK: - Colors

    var colorBorderEnabled: MultipleColorSemanticToken { get }
    var colorBorderHover: MultipleColorSemanticToken { get }
    var colorBorderFocus: MultipleColorSemanticToken { get }

    // MARK: - Borders

    var borderRadiusDefault: BorderRadiusSemanticToken { get }
    var borderWidthDefault: BorderWidthSemanticToken { get }
    var borderWidthFocus: BorderWidthSemanticToken { get }

    // MARK: - Spaces

    var spacePaddingInlineDefault: SpaceSemanticToken { get }
    var spacePaddingBlock: SpaceSemanticToken { get }
    var spacePaddingBlockTopHelperText: SpaceSemanticToken { get }
    var spaceRowGapLabelInput: SpaceSemanticToken { get }

    // MARK: - Sizes

    var sizeMinHeightInput: SizeSemanticToken { get }
    var sizeMaxHeightInput: SizeSemanticToken { get }
    var sizeMaxHeightAssetsContainer: SizeSemanticToken { get }
    var sizeMinWidth: SizeSemanticToken { get }
    var sizeMaxWidth: SizeSemanticToken { get }
}

// swiftlint:enable missing_docs
