//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDS
import OUDSThemesSosh
import Testing

// swiftlint:disable function_body_length
// swiftlint:disable type_body_length

/// Checks if the closed semantic tokens of dimensions, as defined in the Sosh theme, have expected values and relationships
/// between them.
struct DimensionSemanticTokensValuesTests {

    private var theme: OUDSTheme

    init() {
        theme = SoshTheme()
    }

    @Test func dimensionsAreSmallerOneByOne() throws {
        #expect(theme.dimensions.dimensionNone < theme.dimensions.dimension12xs)
        #expect(theme.dimensions.dimension12xs < theme.dimensions.dimension11xs)
        #expect(theme.dimensions.dimension11xs < theme.dimensions.dimension10xs)
        #expect(theme.dimensions.dimension10xs < theme.dimensions.dimension9xs)
        #expect(theme.dimensions.dimension9xs < theme.dimensions.dimension8xs)
        #expect(theme.dimensions.dimension8xs < theme.dimensions.dimension7xs)
        #expect(theme.dimensions.dimension7xs < theme.dimensions.dimension6xs)
        #expect(theme.dimensions.dimension6xs < theme.dimensions.dimension5xs)
        #expect(theme.dimensions.dimension5xs < theme.dimensions.dimension4xs)
        #expect(theme.dimensions.dimension4xs < theme.dimensions.dimension3xs)
        #expect(theme.dimensions.dimension3xs < theme.dimensions.dimension2xs)
        #expect(theme.dimensions.dimension2xs < theme.dimensions.dimensionXs)
        #expect(theme.dimensions.dimensionXs < theme.dimensions.dimensionSm)
        #expect(theme.dimensions.dimensionSm < theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimensionMd < theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimensionLg < theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimensionXl < theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimension2xl < theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimension3xl < theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimension4xl < theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension5xl < theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension6xl < theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension7xl < theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension8xl < theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension9xl < theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension10xl < theme.dimensions.dimension11xl)
    }

    @Test func dimensionsAreAllUnique() throws {
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension12xs)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension11xs)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension10xs)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension9xs)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension8xs)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension7xs)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension6xs)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension5xs)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension4xs)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension3xs)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension2xs)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimensionXs)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimensionSm)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension11xs)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension10xs)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension9xs)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension8xs)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension7xs)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension6xs)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension5xs)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension4xs)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension3xs)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension2xs)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimensionXs)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimensionSm)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension12xs != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension10xs)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension9xs)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension8xs)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension7xs)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension6xs)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension5xs)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension4xs)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension3xs)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension2xs)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimensionXs)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimensionSm)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension11xs != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension9xs)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension8xs)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension7xs)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension6xs)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension5xs)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension4xs)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension3xs)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension2xs)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimensionXs)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimensionSm)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension10xs != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension8xs)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension7xs)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension6xs)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension5xs)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension4xs)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension3xs)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension2xs)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimensionXs)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimensionSm)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension9xs != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension7xs)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension6xs)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension5xs)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension4xs)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension3xs)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension2xs)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimensionXs)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimensionSm)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension8xs != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension6xs)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension5xs)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension4xs)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension3xs)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension2xs)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimensionXs)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimensionSm)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension7xs != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimension5xs)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimension4xs)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimension3xs)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimension2xs)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimensionXs)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimensionSm)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension6xs != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimension4xs)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimension3xs)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimension2xs)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimensionXs)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimensionSm)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension5xs != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimension3xs)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimension2xs)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimensionXs)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimensionSm)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension4xs != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimension2xs)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimensionXs)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimensionSm)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension3xs != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimensionXs)
        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimensionSm)
        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension2xs != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimensionXs != theme.dimensions.dimensionSm)
        #expect(theme.dimensions.dimensionXs != theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimensionXs != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimensionXs != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimensionXs != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimensionXs != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimensionXs != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimensionXs != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimensionXs != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimensionXs != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimensionXs != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimensionXs != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimensionXs != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimensionXs != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimensionSm != theme.dimensions.dimensionMd)
        #expect(theme.dimensions.dimensionSm != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimensionSm != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimensionSm != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimensionSm != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimensionSm != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimensionSm != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimensionSm != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimensionSm != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimensionSm != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimensionSm != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimensionSm != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimensionSm != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimensionMd != theme.dimensions.dimensionLg)
        #expect(theme.dimensions.dimensionMd != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimensionMd != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimensionMd != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimensionMd != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimensionMd != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimensionMd != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimensionMd != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimensionMd != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimensionMd != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimensionMd != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimensionMd != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimensionLg != theme.dimensions.dimensionXl)
        #expect(theme.dimensions.dimensionLg != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimensionLg != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimensionLg != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimensionLg != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimensionLg != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimensionLg != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimensionLg != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimensionLg != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimensionLg != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimensionLg != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimensionXl != theme.dimensions.dimension2xl)
        #expect(theme.dimensions.dimensionXl != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimensionXl != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimensionXl != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimensionXl != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimensionXl != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimensionXl != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimensionXl != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimensionXl != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimensionXl != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension2xl != theme.dimensions.dimension3xl)
        #expect(theme.dimensions.dimension2xl != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimension2xl != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension2xl != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension2xl != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension2xl != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension2xl != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension2xl != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension2xl != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension3xl != theme.dimensions.dimension4xl)
        #expect(theme.dimensions.dimension3xl != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension3xl != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension3xl != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension3xl != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension3xl != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension3xl != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension3xl != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension4xl != theme.dimensions.dimension5xl)
        #expect(theme.dimensions.dimension4xl != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension4xl != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension4xl != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension4xl != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension4xl != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension4xl != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension5xl != theme.dimensions.dimension6xl)
        #expect(theme.dimensions.dimension5xl != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension5xl != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension5xl != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension5xl != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension5xl != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension6xl != theme.dimensions.dimension7xl)
        #expect(theme.dimensions.dimension6xl != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension6xl != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension6xl != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension6xl != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension7xl != theme.dimensions.dimension8xl)
        #expect(theme.dimensions.dimension7xl != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension7xl != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension7xl != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension8xl != theme.dimensions.dimension9xl)
        #expect(theme.dimensions.dimension8xl != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension8xl != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension9xl != theme.dimensions.dimension10xl)
        #expect(theme.dimensions.dimension9xl != theme.dimensions.dimension11xl)

        #expect(theme.dimensions.dimension10xl != theme.dimensions.dimension11xl)
    }
}

// swiftlint:enable function_body_length
// swiftlint:enable type_body_length
