//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSFoundations
import SwiftUI

/// Kind of semantic tokens which will wrap a combination of ``FontLineHeightSemanticToken`` depending to size classes.
/// Allows to gather the multiple-value tokens from *Figma* inside one object.
/// If a font line height token exists with its value depending to the size class, it must be packed in such ``MultipleFontLineHeightSemanticToken`
///
/// ```swift
///         // Assuming in Figma with have a font letter spacing semantic token lineHeightLabelXLarge,
///         // two semantic font line height spacing tokens will be defined in Figma and generated by tokenator because
///         // its value can vary if compact or regular modes.
///         // They can be declared in protocol FontSemanticTokens,
///         // and defined automaticaly in OUDSTheme+FontSemanticTokens extension
///         var lineHeightLabelXLargeMobile: FontLineHeightSemanticToken { FontRawTokens.lineHeight450 }
///         var lineHeightLabelXLargeTablet: FontLineHeightSemanticToken { FontRawTokens.lineHeight450 }
///
///         // Then the develoment team declares an "higher" level line height semantic token for lineHeightLabelXLarge
///         // inside FontMultipleSemanticTokens protocol,
///         // and defined inside OUDSTheme+FontMultipleSemanticTokens extension
///         var lineHeightLabelXLarge: MultipleFontLineHeightSemanticToken {
///             MultipleFontLineHeightSemanticToken(compact: lineHeightLabelXLargeMobile, regular: lineHeightLabelXLargeTablet)
///         }
///
///         // If the same value is used whatever the size class is
///         var lineHeightLabelXLarge: MultipleFontLineHeightSemanticToken { MultipleFontLineHeightSemanticToken(lineHeightLabelXLargeMobile) }
///
///         // The theme exposes both generated font line height semantic tokens and "crafted" higher level color semantic tokens.
///         // It is recommended to use the higher level version as it is less error-prone.
/// ```
///
/// - Since: 0.8.0
public final class MultipleFontLineHeightSemanticToken: NSObject, Sendable, Comparable {

    /// For **extra-compact** and **compact** viewports
    public let compact: FontLineHeightSemanticToken

    /// For **regular** and **medium** viewports
    public let regular: FontLineHeightSemanticToken

    /// Initializes a new multiple font token with the same value for both *compact* and *regular* size classes
    /// - Parameter value: The `FontLineHeightSemanticToken` to apply if device in *compact* mode
    public init(_ value: FontLineHeightSemanticToken) {
        compact = value
        regular = value
    }

    /// Initializes a new multiple font token.
    /// - Parameters:
    ///    - compact: The `FontLineHeightSemanticToken` to apply if device in *compact* mode
    ///    - regular: The `FontLineHeightSemanticToken` to apply if device in *regular* mode
    public init(compact: FontLineHeightSemanticToken, regular: FontLineHeightSemanticToken) {
        self.compact = compact
        self.regular = regular
        if compact > regular {
            OL.warning("A multiple font line height semantic token as a compact value (\(compact)) bigger than the regular one (\(regular)), it's strange")
        }
    }

    deinit {}

    /// Returns `true` if `self` and `object` has the same `compact` and `regular` values and with `object`
    /// as a `MultipleFontTokens`. Otherwise returns `false`.
    /// `isEqual` override is preferred for `NSObject`.
    override public func isEqual(_ object: Any?) -> Bool {
        guard let object = object as? MultipleFontLineHeightSemanticToken else { return false }
        return compact == object.compact && regular == object.regular
    }

    // MARK: - Comparable

    /// Operator which will return `true` if `lhs` is smaller than `rhs`.
    /// By "smaller" we mean smaller `FontLineHeightSemanticToken`
    ///
    /// - Parameters:
    ///    - lhs: The font size semantic token we expect to be smaller than `rhs`
    ///    - rhs: The font size semantic tokenwe expect to be bigger than `lhs`
    /// - Returns Bool: `true` if `lhs` smaller than `rhs`, `false` otherwise
    public static func < (lhs: MultipleFontLineHeightSemanticToken, rhs: MultipleFontLineHeightSemanticToken) -> Bool {
        lhs.compact <= rhs.compact && lhs.regular <= rhs.regular
    }

    /// Returns the right line height semantic token according to the `userInterfaceSizeClass`.
    /// - Parameter userInterfaceSizeClass: The user interface size class, should be from `.verticalSizeClass`
    /// - Returns: The right line height semantic token
    public func lineHeight(for userInterfaceSizeClass: UserInterfaceSizeClass) -> FontLineHeightSemanticToken {
        userInterfaceSizeClass == .compact ? compact : regular
    }
}
