//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensRaw

/// Kind of semantic tokens which will wrap a combination of ``TypographyFontLineHeightSemanticToken`` depending to size classes.
/// Allows to gather the multiple-value tokens from *Figma* inside one object.
/// If a font line height token exists with its value depending to the size class, it must be packed in such ``MultipleFontLineHeightSemanticTokens`
///
/// ```swift
///         // Assuming in Figma with have a font letter spacing semantic token fontLineHeightLabelXLarge,
///         // two semantic font line height spacing tokens will be defined in Figma and generated by tokenator because
///         // its value can vary if compact or regular modes.
///         // They can be declared in protocol FontSemanticTokens,
///         // and defined automaticaly in OUDSTheme+FontSemanticTokens extension
///         var fontLineHeightLabelXLargeMobile: TypographyFontLineHeightSemanticToken { FontRawTokens.fontLineHeight450 }
///         var fontLineHeightLabelXLargeTablet: TypographyFontLineHeightSemanticToken { FontRawTokens.fontLineHeight450 }
///
///         // Then the develoment team declares an "higher" level line height semantic token for fontLineHeightLabelXLarge
///         // inside FontMultipleSemanticTokens protocol,
///         // and defined inside OUDSTheme+FontMultipleSemanticTokens extension
///         var fontLineHeightLabelXLarge: MultipleFontLineHeightSemanticTokens {
///             MultipleFontLineHeightSemanticTokens(compact: fontLineHeightLabelXLargeMobile, regular: fontLineHeightLabelXLargeTablet)
///         }
///
///         // If the same value is used whatever the size class is
///         var fontLineHeightLabelXLarge: MultipleFontLineHeightSemanticTokens { MultipleFontLineHeightSemanticTokens(fontLineHeightLabelXLargeMobile) }
///
///         // The theme exposes both generated font line height semantic tokens and "crafted" higher level color semantic tokens.
///         // It is recommended to use the higher level version as it is less error-prone.
/// ```
/// 
public final class MultipleFontLineHeightSemanticTokens: NSObject, Sendable {

    /// For **extra-compact** and **compact** viewports
    public let compact: FontLineHeightSemanticToken

    /// For **regular** and **medium** viewports
    public let regular: FontLineHeightSemanticToken

    /// Initializes a new multiple font token with the same value for both *compact* and *regular* size classes
    /// - Parameter value: The `TypographyFontLineHeightSemanticToken` to apply if device in *compact* mode
    public init(_ value: FontLineHeightSemanticToken) {
        self.compact = value
        self.regular = value
    }

    /// Initializes a new multiple font token.
    /// - Parameters:
    ///    - compact: The `TypographyFontLineHeightSemanticToken` to apply if device in *compact* mode
    ///    - regular: The `TypographyFontLineHeightSemanticToken` to apply if device in *regular* mode
    public init(compact: FontLineHeightSemanticToken, regular: FontLineHeightSemanticToken) {
        self.compact = compact
        self.regular = regular
    }

    deinit { }

    /// Returns `true` if `self` and `object` has the same `compact` and `regular` values and with `object`
    /// as a `MultipleFontTokens`. Otherwise returns `false`.
    /// `isEqual` override is preferred for `NSObject`.
    override public func isEqual(_ object: Any?) -> Bool {
        guard let object = object as? MultipleFontLineHeightSemanticTokens else { return false }
        return self.compact == object.compact && self.regular == object.regular
    }
}
