//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensRaw
import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable line_length

/// Defines basic values common to all themes for `ElevationCompositeSemanticTokens``.
/// These values can be overriden inside ``SoshThemeElevationSemanticTokensProvider`` subclasses
/// (in extensions or not, in the same module or not) thanks to the `@objc open` combination.
/// The aim of this extension is to make relationships between all semantic tokens for elevations and associated raw tokens.
/// The *tokenator* is not able to provide code for such "composite" objects because the *Figma* tool itself cannot manage that and does not output anything in its JSON to process.
/// It defines in fact box shadows effects.
extension SoshThemeElevationSemanticTokensProvider: ElevationCompositeSemanticTokens {

    @objc public final var elevationNone: ElevationCompositeSemanticToken {
        MultipleElevationCompositeRawTokens(ElevationCompositeRawToken(x: elevationXNone, y: elevationYNone, blur: elevationBlurNone, color: elevationColorNone))
    }

    @objc public final var elevationRaised: ElevationCompositeSemanticToken {
        MultipleElevationCompositeRawTokens(light: ElevationCompositeRawToken(x: elevationXRaised, y: elevationYRaised, blur: elevationBlurRaised, color: elevationColorRaisedLight),
                                            dark: ElevationCompositeRawToken(x: elevationXRaised, y: elevationYRaised, blur: elevationBlurRaised, color: elevationColorRaisedDark))
    }

    @objc public final var elevationDrag: ElevationCompositeSemanticToken {
        MultipleElevationCompositeRawTokens(light: ElevationCompositeRawToken(x: elevationXDrag, y: elevationYDrag, blur: elevationBlurDrag, color: elevationColorDragLight),
                                            dark: ElevationCompositeRawToken(x: elevationXDrag, y: elevationYDrag, blur: elevationBlurDrag, color: elevationColorDragDark))
    }

    @objc public final var elevationDefault: ElevationCompositeSemanticToken {
        MultipleElevationCompositeRawTokens(light: ElevationCompositeRawToken(x: elevationXDefault, y: elevationYDefault, blur: elevationBlurDefault, color: elevationColorDefaultLight),
                                            dark: ElevationCompositeRawToken(x: elevationXDefault, y: elevationYDefault, blur: elevationBlurDefault, color: elevationColorDefaultDark))
    }

    @objc public final var elevationEmphasized: ElevationCompositeSemanticToken {
        MultipleElevationCompositeRawTokens(light: ElevationCompositeRawToken(x: elevationXEmphasized, y: elevationYEmphasized, blur: elevationBlurEmphasized, color: elevationColorEmphasizedLight),
                                            dark: ElevationCompositeRawToken(x: elevationXEmphasized, y: elevationYEmphasized, blur: elevationBlurEmphasized, color: elevationColorEmphasizedDark))
    }

    @objc public final var elevationSticky: ElevationCompositeSemanticToken {
        MultipleElevationCompositeRawTokens(light: ElevationCompositeRawToken(x: elevationXSticky, y: elevationYSticky, blur: elevationBlurSticky, color: elevationColorStickyLight),
                                            dark: ElevationCompositeRawToken(x: elevationXSticky, y: elevationYSticky, blur: elevationBlurSticky, color: elevationColorStickyDark))
    }
}

// swiftlint:enable line_length
