//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

/// Defines provider objects for space semantic tokens (i.e. in the end `DimensionRawTokens`).
/// These values can be overriden inside ``SoshThemeSpaceSemanticTokensProvider`` subclasses
/// (in extensions or not, in the same module or not) thanks to the `@objc open` combination.
extension SoshThemeSpaceSemanticTokensProvider: SpaceMultipleSemanticTokens {

    // MARK: Semantic token - Spacing - Layout fluid

    @objc public final var scaledNone: MultipleSpaceSemanticToken { MultipleSpaceSemanticToken(compact: scaledNoneMobile, regular: scaledNoneTablet) }
    @objc public final var scaled3xsmall: MultipleSpaceSemanticToken { MultipleSpaceSemanticToken(compact: scaled3xsmallMobile, regular: scaled3xsmallTablet) }
    @objc public final var scaled2xsmall: MultipleSpaceSemanticToken { MultipleSpaceSemanticToken(compact: scaled2xsmallMobile, regular: scaled2xsmallTablet) }
    @objc public final var scaledXsmall: MultipleSpaceSemanticToken { MultipleSpaceSemanticToken(compact: scaledXsmallMobile, regular: scaledXsmallTablet) }
    @objc public final var scaledSmall: MultipleSpaceSemanticToken { MultipleSpaceSemanticToken(compact: scaledSmallMobile, regular: scaledSmallTablet) }
    @objc public final var scaledMedium: MultipleSpaceSemanticToken { MultipleSpaceSemanticToken(compact: scaledMediumMobile, regular: scaledMediumTablet) }
    @objc public final var scaledLarge: MultipleSpaceSemanticToken { MultipleSpaceSemanticToken(compact: scaledLargeMobile, regular: scaledLargeTablet) }
    @objc public final var scaledXlarge: MultipleSpaceSemanticToken { MultipleSpaceSemanticToken(compact: scaledXlargeMobile, regular: scaledXlargeTablet) }
    @objc public final var scaled2xlarge: MultipleSpaceSemanticToken { MultipleSpaceSemanticToken(compact: scaled2xlargeMobile, regular: scaled2xlargeTablet) }
    @objc public final var scaled3xlarge: MultipleSpaceSemanticToken { MultipleSpaceSemanticToken(compact: scaled3xlargeMobile, regular: scaled3xlargeTablet) }
}
