//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensRaw
import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable line_length
// swiftlint:disable identifier_name

/// Defines wrapper objects for `ColorSemanticToken`.
/// These values can be overriden inside `OUDSTheme` subclasses (in extensions or not, in the same module or not) thanks to the `@objc open` combination.
/// Some tokens do not have values assigned in the design system, and must be overriden.
/// Some tokens must be overiden in `OrangeTheme` side because they rely on Orange brand colors.
/// Helps to expose color semantic tokens with two values to use depending to the color scheme (*Figma* cannot manage such tokens and generate them).
extension OUDSTheme: ColorMultipleSemanticTokens {

    // MARK: Semantic token - Colors - Background

    @objc open var colorBgPrimary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgPrimaryLight, dark: colorBgPrimaryDark) }

    @objc open var colorBgSecondary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgSecondaryLight, dark: colorBgSecondaryDark) }

    @objc open var colorBgTertiary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgTertiaryLight, dark: colorBgTertiaryDark) }
    
    @objc open var colorBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgEmphasizedLight, dark: colorBgEmphasizedDark) }

    // WARNING: #124 - Colors to use are part of Orange Theme so are not reachable at this level, as a workaround add raw values
    @objc open var colorBgBrandPrimary: MultipleColorSemanticTokens { fatalError("🤖 Raw token unavailable for colorBgBrandPrimary!") }

    @objc open var colorBgStatusNeutral: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusNeutralLight, dark: colorBgStatusNeutralDark) }

    @objc open var colorBgStatusNeutralOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusNeutralOnBgEmphasizedLight, dark: colorBgStatusNeutralOnBgEmphasizedDark) }

    @objc open var colorBgStatusPositiveMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusPositiveMutedLight, dark: colorBgStatusPositiveMutedDark) }

    @objc open var colorBgStatusPositiveMutedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusPositiveMutedOnBgEmphasizedLight, dark: colorBgStatusPositiveMutedOnBgEmphasizedDark) }

    @objc open var colorBgStatusPositiveEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusPositiveEmphasizedLight, dark: colorBgStatusPositiveEmphasizedDark) }

    @objc open var colorBgStatusInfoMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusInfoMutedLight, dark: colorBgStatusInfoMutedDark) }

    @objc open var colorBgStatusInfoMutedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusInfoMutedOnBgEmphasizedLight, dark: colorBgStatusInfoMutedOnBgEmphasizedDark) }

    @objc open var colorBgStatusInfoEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusInfoEmphasizedLight, dark: colorBgStatusInfoEmphasizedDark) }

    @objc open var colorBgStatusWarningMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusWarningMutedLight, dark: colorBgStatusWarningMutedDark) }

    @objc open var colorBgStatusWarningMutedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusWarningMutedOnBgEmphasizedLight, dark: colorBgStatusWarningMutedOnBgEmphasizedDark) }

    @objc open var colorBgStatusWarningEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusWarningEmphasizedLight, dark: colorBgStatusWarningEmphasizedDark) }

    @objc open var colorBgStatusNegativeMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusNegativeMutedLight, dark: colorBgStatusNegativeMutedDark) }

    @objc open var colorBgStatusNegativeMutedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusNegativeMutedOnBgEmphasizedLight, dark: colorBgStatusNegativeMutedOnBgEmphasizedDark) }

    @objc open var colorBgStatusNegativeEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusNegativeEmphasizedLight, dark: colorBgStatusNegativeEmphasizedDark) }

    // WARNING: #124 - Colors to use are part of Orange Theme so are not reachable at this level, as a workaround add raw values
    @objc open var colorBgStatusAccentMuted: MultipleColorSemanticTokens { fatalError("🤖 Raw token unavailable for colorBgStatusAccentMuted!") }

    // WARNING: #124 - Colors to use are part of Orange Theme so are not reachable at this level, as a workaround add raw values
    @objc open var colorBgStatusAccentMutedOnBgEmphasized: MultipleColorSemanticTokens { fatalError("🤖 Raw token unavailable for colorBgStatusAccentMutedOnBgEmphasized!") }

    @objc open var colorBgStatusAccentEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBgStatusAccentEmphasizedLight, dark: colorBgStatusAccentEmphasizedDark) }

    // MARK: Semantic token - Colors - Content

    @objc open var colorContentDefault: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentDefaultLight, dark: colorContentDefaultDark) }

    @objc open var colorContentDefaultOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentDefaultOnBgEmphasizedLight, dark: colorContentDefaultOnBgEmphasizedDark) }

    @objc open var colorContentMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentMutedLight, dark: colorContentMutedDark) }

    @objc open var colorContentMutedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentMutedOnBgEmphasizedLight, dark: colorContentMutedOnBgEmphasizedDark) }

    @objc open var colorContentDisabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentDisabledLight, dark: colorContentDisabledDark) }

    @objc open var colorContentDisabledOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentDisabledOnBgEmphasizedLight, dark: colorContentDisabledOnBgEmphasizedDark) }

    // WARNING: #124 - Colors to use are part of Orange Theme so are not reachable at this level, as a workaround add raw values
    @objc open var colorContentBrandPrimary: MultipleColorSemanticTokens { fatalError("🤖 Raw token unavailable for colorContentBrandPrimary!") }

    @objc open var colorContentBrandPrimaryOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentBrandPrimaryOnBgEmphasizedLight, dark: colorContentBrandPrimaryOnBgEmphasizedDark) }

    @objc open var colorContentStatusPositive: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentStatusPositiveLight, dark: colorContentStatusPositiveDark) }

    @objc open var colorContentStatusInfo: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentStatusInfoLight, dark: colorContentStatusInfoDark) }

    @objc open var colorContentStatusWarning: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentStatusWarningLight, dark: colorContentStatusWarningDark) }

    @objc open var colorContentStatusNegative: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentStatusNegativeLight, dark: colorContentStatusNegativeDark) }

    @objc open var colorContentStatusAccent: MultipleColorSemanticTokens { fatalError("🤖 No value defined for colorContentStatusAccent!") }

    @objc open var colorContentOnActionDisabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnActionDisabledLight, dark: colorContentOnActionDisabledDark) }

    @objc open var colorContentOnActionDisabledOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnActionDisabledOnBgEmphasizedLight, dark: colorContentOnActionDisabledOnBgEmphasizedDark) }

    @objc open var colorContentOnActionNegative: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnActionNegativeLight, dark: colorContentOnActionNegativeDark) }

    @objc open var colorContentOnActionPrimaryEnabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnActionPrimaryEnabledLight, dark: colorContentOnActionPrimaryEnabledDark) }

    @objc open var colorContentOnActionPrimaryEnabledOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnActionPrimaryEnabledOnBgEmphasizedLight, dark: colorContentOnActionPrimaryEnabledOnBgEmphasizedDark) }

    @objc open var colorContentOnActionPrimaryFocus: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnActionPrimaryFocusLight, dark: colorContentOnActionPrimaryFocusDark) }

    @objc open var colorContentOnActionPrimaryFocusOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnActionPrimaryFocusOnBgEmphasizedLight, dark: colorContentOnActionPrimaryFocusOnBgEmphasizedDark) }

    @objc open var colorContentOnActionPrimaryHover: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnActionPrimaryHoverLight, dark: colorContentOnActionPrimaryHoverDark) }

    @objc open var colorContentOnActionPrimaryHoverOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnActionPrimaryHoverOnBgEmphasizedLight, dark: colorContentOnActionPrimaryHoverOnBgEmphasizedDark) }

    @objc open var colorContentOnActionPrimaryLoading: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnActionPrimaryLoadingLight, dark: colorContentOnActionPrimaryLoadingDark) }

    @objc open var colorContentOnActionPrimaryLoadingOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnActionPrimaryLoadingOnBgEmphasizedLight, dark: colorContentOnActionPrimaryLoadingOnBgEmphasizedDark) }

    @objc open var colorContentOnActionPrimaryPressed: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnActionPrimaryPressedLight, dark: colorContentOnActionPrimaryPressedDark) }

    @objc open var colorContentOnActionPrimaryPressedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnActionPrimaryPressedOnBgEmphasizedLight, dark: colorContentOnActionPrimaryPressedOnBgEmphasizedDark) }

    @objc open var colorContentOnBrandPrimary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnBrandPrimaryLight, dark: colorContentOnBrandPrimaryDark) }

    @objc open var colorContentOnStatusAccentEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusAccentEmphasizedLight, dark: colorContentOnStatusAccentEmphasizedDark) }

    @objc open var colorContentOnStatusAccentMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusAccentMutedLight, dark: colorContentOnStatusAccentMutedDark) }

    @objc open var colorContentOnStatusAccentMutedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusAccentMutedOnBgEmphasizedLight, dark: colorContentOnStatusAccentMutedOnBgEmphasizedDark) }

    @objc open var colorContentOnStatusInfoEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusInfoEmphasizedLight, dark: colorContentOnStatusInfoEmphasizedDark) }

    @objc open var colorContentOnStatusInfoMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusInfoMutedLight, dark: colorContentOnStatusInfoMutedDark) }

    @objc open var colorContentOnStatusInfoMutedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusInfoMutedOnBgEmphasizedLight, dark: colorContentOnStatusInfoMutedOnBgEmphasizedDark) }

    @objc open var colorContentOnStatusNegativeEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusNegativeEmphasizedLight, dark: colorContentOnStatusNegativeEmphasizedDark) }

    @objc open var colorContentOnStatusNegativeMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusNegativeMutedLight, dark: colorContentOnStatusNegativeMutedDark) }

    @objc open var colorContentOnStatusNegativeMutedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusNegativeMutedOnBgEmphasizedLight, dark: colorContentOnStatusNegativeMutedOnBgEmphasizedDark) }

    @objc open var colorContentOnStatusPositiveEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusPositiveEmphasizedLight, dark: colorContentOnStatusPositiveEmphasizedDark) }

    @objc open var colorContentOnStatusPositiveMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusPositiveMutedLight, dark: colorContentOnStatusPositiveMutedDark) }

    @objc open var colorContentOnStatusPositiveMutedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusPositiveMutedOnBgEmphasizedLight, dark: colorContentOnStatusPositiveMutedOnBgEmphasizedDark) }

    @objc open var colorContentOnStatusWarningEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusWarningEmphasizedLight, dark: colorContentOnStatusWarningEmphasizedDark) }

    @objc open var colorContentOnStatusWarningMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusWarningMutedLight, dark: colorContentOnStatusWarningMutedDark) }

    @objc open var colorContentOnStatusWarningMutedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorContentOnStatusWarningMutedOnBgEmphasizedLight, dark: colorContentOnStatusWarningMutedOnBgEmphasizedDark) }

    
    // MARK: Semantic token - Colors - Border

    @objc open var colorBorderDefault: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBorderDefaultLight, dark: colorBorderDefaultDark) }

    @objc open var colorBorderDefaultOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBorderDefaultOnBgEmphasizedLight, dark: colorBorderDefaultOnBgEmphasizedDark) }

    @objc open var colorBorderEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBorderEmphasizedLight, dark: colorBorderEmphasizedDark) }

    @objc open var colorBorderEmphasizedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBorderEmphasizedOnBgEmphasizedLight, dark: colorBorderEmphasizedOnBgEmphasizedDark) }

    @objc open var colorBorderFocus: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorBorderFocusLight, dark: colorBorderFocusDark) }

    // WARNING: #124 - Colors to use are part of Orange Theme so are not reachable at this level, as a workaround add raw values
    @objc open var colorBorderBrandPrimaryOnBgEmphasized: MultipleColorSemanticTokens { fatalError("🤖 Raw token unavailable for colorBorderBrandPrimaryOnBgEmphasized!") }

    // WARNING: #124 - Colors to use sont part of Orange Theme so sont not reachable at this level, as un workaround add raw values
    @objc open var colorBorderBrandPrimary: MultipleColorSemanticTokens { fatalError("🤖 Raw token unavailable for colorBorderBrandPrimary!") }

    @objc open var colorBorderStatusPositive: MultipleColorSemanticTokens { fatalError("🤖 No value defined for colorBorderStatusPositive!") }

    @objc open var colorBorderStatusInfo: MultipleColorSemanticTokens { fatalError("🤖 No value defined for colorBorderStatusInfo!") }

    @objc open var colorBorderStatusWarning: MultipleColorSemanticTokens { fatalError("🤖 No value defined for colorBorderStatusWarning!") }

    @objc open var colorBorderStatusNegative: MultipleColorSemanticTokens { fatalError("🤖 No value defined for colorBorderStatusNegative!") }

    @objc open var colorBorderStatusAccent: MultipleColorSemanticTokens { fatalError("🤖 No value defined for colorBorderStatusAccent!") }

    // MARK: Semantic token - Colors - Action

    @objc open var colorActionSelected: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionSelectedLight, dark: colorActionSelectedDark) }

    @objc open var colorActionSelectedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionSelectedOnBgEmphasizedLight, dark: colorActionSelectedOnBgEmphasizedDark) }

    @objc open var colorActionDisabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionDisabledLight, dark: colorActionDisabledDark) }

    @objc open var colorActionDisabledOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionDisabledOnBgEmphasizedLight, dark: colorActionDisabledOnBgEmphasizedDark) }

    @objc open var colorActionVisited: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionVisitedLight, dark: colorActionVisitedDark) }

    @objc open var colorActionVisitedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionVisitedOnBgEmphasizedLight, dark: colorActionVisitedOnBgEmphasizedLight) }

    @objc open var colorActionPrimaryEnabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionPrimaryEnabledLight, dark: colorActionPrimaryEnabledDark) }

    @objc open var colorActionPrimaryEnabledOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionPrimaryEnabledOnBgEmphasizedLight, dark: colorActionPrimaryEnabledOnBgEmphasizedDark) }

    @objc open var colorActionPrimaryHover: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionPrimaryHoverLight, dark: colorActionPrimaryHoverDark) }

    @objc open var colorActionPrimaryHoverOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionPrimaryHoverOnBgEmphasizedLight, dark: colorActionPrimaryHoverOnBgEmphasizedDark) }

    @objc open var colorActionPrimaryPressed: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionPrimaryPressedLight, dark: colorActionPrimaryPressedDark) }

    @objc open var colorActionPrimaryPressedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionPrimaryPressedOnBgEmphasizedLight, dark: colorActionPrimaryPressedOnBgEmphasizedDark) }

    @objc open var colorActionPrimaryLoading: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionPrimaryLoadingLight, dark: colorActionPrimaryLoadingDark) }

    @objc open var colorActionPrimaryLoadingOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionPrimaryLoadingOnBgEmphasizedLight, dark: colorActionPrimaryLoadingOnBgEmphasizedDark) }

    @objc open var colorActionPrimaryFocus: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionPrimaryFocusLight, dark: colorActionPrimaryFocusDark) }

    @objc open var colorActionPrimaryFocusOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionPrimaryFocusOnBgEmphasizedLight, dark: colorActionPrimaryFocusOnBgEmphasizedDark) }

    @objc open var colorActionSecondaryEnabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionSecondaryEnabledLight, dark: colorActionSecondaryEnabledDark) }

    @objc open var colorActionSecondaryEnabledOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionSecondaryEnabledOnBgEmphasizedLight, dark: colorActionSecondaryEnabledOnBgEmphasizedDark) }

    @objc open var colorActionSecondaryHover: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionSecondaryHoverLight, dark: colorActionSecondaryHoverDark) }

    @objc open var colorActionSecondaryHoverOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionSecondaryHoverOnBgEmphasizedLight, dark: colorActionSecondaryHoverOnBgEmphasizedDark) }

    @objc open var colorActionSecondaryPressed: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionSecondaryPressedLight, dark: colorActionSecondaryPressedDark) }

    @objc open var colorActionSecondaryPressedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionSecondaryPressedOnBgEmphasizedLight, dark: colorActionSecondaryPressedOnBgEmphasizedDark) }

    @objc open var colorActionSecondaryLoading: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionSecondaryLoadingLight, dark: colorActionSecondaryLoadingDark) }

    @objc open var colorActionSecondaryLoadingOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionSecondaryLoadingOnBgEmphasizedLight, dark: colorActionSecondaryLoadingOnBgEmphasizedDark) }

    @objc open var colorActionSecondaryFocus: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionSecondaryFocusLight, dark: colorActionSecondaryFocusDark) }

    @objc open var colorActionSecondaryFocusOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionSecondaryFocusOnBgEmphasizedLight, dark: colorActionSecondaryFocusOnBgEmphasizedDark) }

    @objc open var colorActionNegativeEnabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionNegativeEnabledLight, dark: colorActionNegativeEnabledDark) }

    @objc open var colorActionNegativeHover: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionNegativeHoverLight, dark: colorActionNegativeHoverDark) }

    @objc open var colorActionNegativePressed: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionNegativePressedLight, dark: colorActionNegativePressedDark) }

    @objc open var colorActionNegativeLoading: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionNegativeLoadingLight, dark: colorActionNegativeLoadingDark) }

    @objc open var colorActionNegativeFocus: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorActionNegativeFocusLight, dark: colorActionNegativeFocusDark) }

    // MARK: Semantic token - Colors - Always

    @objc open var colorAlwaysBlack: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorAlwaysBlackLight, dark: colorAlwaysBlackDark) }

    @objc open var colorAlwaysWhite: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorAlwaysWhiteLight, dark: colorAlwaysWhiteDark) }

    @objc open var colorAlwaysWarning: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorAlwaysWarningLight, dark: colorAlwaysWarningDark) }

    @objc open var colorAlwaysNegative: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorAlwaysNegativeLight, dark: colorAlwaysNegativeDark) }
    
    @objc open var colorAlwaysPositive: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorAlwaysPositiveLight, dark: colorAlwaysPositiveDark) }

    @objc open var colorAlwaysInfo: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorAlwaysInfoLight, dark: colorAlwaysInfoDark) }

    @objc open var colorAlwaysAccent: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorAlwaysAccentLight, dark: colorAlwaysAccentDark) }

    @objc open var colorAlwaysOnAccent: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorAlwaysOnAccentLight, dark: colorAlwaysOnAccentDark) }
        
    @objc open var colorAlwaysOnBlack: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorAlwaysOnBlackLight, dark: colorAlwaysOnBlackDark) }
    
    @objc open var colorAlwaysOnInfo: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorAlwaysOnInfoLight, dark: colorAlwaysOnInfoDark) }
    
    @objc open var colorAlwaysOnNegative: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorAlwaysOnNegativeLight, dark: colorAlwaysOnNegativeDark) }
    
    @objc open var colorAlwaysOnPositive: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorAlwaysOnPositiveLight, dark: colorAlwaysOnPositiveDark) }
    
    @objc open var colorAlwaysOnWarning: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorAlwaysOnWarningLight, dark: colorAlwaysOnWarningDark) }
    
    @objc open var colorAlwaysOnWhite: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorAlwaysOnWhiteLight, dark: colorAlwaysOnWhiteDark) }
    
    // MARK: Semantic token - Colors - Transparent

    @objc open var colorTransparentDefault: MultipleColorSemanticTokens { MultipleColorSemanticTokens(ColorRawTokens.colorTransparentBlack0) }

    // MARK: Semantic token - Colors - Elevation

    @objc open var colorElevationRaised: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorElevationRaisedLight, dark: colorElevationRaisedDark) }

    @objc open var colorElevationRaisedOnBgSecondary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorElevationRaisedOnBgSecondaryLight, dark: colorElevationRaisedOnBgSecondaryDark) }

    @objc open var colorElevationRaisedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorElevationRaisedOnBgEmphasizedLight, dark: colorElevationRaisedOnBgEmphasizedDark) }

    @objc open var colorElevationDrag: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorElevationDragLight, dark: colorElevationDragDark) }

    @objc open var colorElevationDragOnBgSecondary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorElevationDragOnBgSecondaryLight, dark: colorElevationDragOnBgSecondaryDark) }

    @objc open var colorElevationDragOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorElevationDragOnBgEmphasizedLight, dark: colorElevationDragOnBgEmphasizedDark) }

    @objc open var colorElevationOverlayDefault: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorElevationOverlayDefaultLight, dark: colorElevationOverlayDefaultDark) }

    @objc open var colorElevationOverlayDefaultOnBgSecondary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorElevationOverlayDefaultOnBgSecondaryLight, dark: colorElevationOverlayDefaultOnBgSecondaryDark) }

    @objc open var colorElevationOverlayDefaultOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorElevationOverlayDefaultOnBgEmphasizedLight, dark: colorElevationOverlayDefaultOnBgEmphasizedDark) }

    @objc open var colorElevationOverlayEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorElevationOverlayEmphasizedLight, dark: colorElevationOverlayEmphasizedDark) }

    @objc open var colorElevationOverlayEmphasizedOnBgSecondary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorElevationOverlayEmphasizedOnBgSecondaryLight, dark: colorElevationOverlayEmphasizedOnBgSecondaryDark) }

    @objc open var colorElevationOverlayEmphasizedOnBgEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorElevationOverlayEmphasizedOnBgEmphasizedLight, dark: colorElevationOverlayEmphasizedOnBgEmphasizedDark) }

    @objc open var colorElevationModal: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorElevationModalLight, dark: colorElevationModalDark) }

    // MARK: Semantic token - Colors - Decorative

    @objc open var colorDecorativeBrandPrimary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorDecorativeBrandPrimaryLight, dark: colorDecorativeBrandPrimaryDark) }

    @objc open var colorDecorativeBrandSecondary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorDecorativeBrandSecondaryLight, dark: colorDecorativeBrandSecondaryDark) }

    @objc open var colorDecorativeBrandTertiary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorDecorativeBrandTertiaryLight, dark: colorDecorativeBrandTertiaryDark) }

    @objc open var colorDecorativeNeutralMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorDecorativeNeutralMutedLight, dark: colorDecorativeNeutralMutedDark) }

    @objc open var colorDecorativeNeutralDefault: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorDecorativeNeutralDefaultLight, dark: colorDecorativeNeutralDefaultDark) }

    @objc open var colorDecorativeNeutralEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorDecorativeNeutralEmphasizedLight, dark: colorDecorativeNeutralEmphasizedDark) }

    @objc open var colorDecorativeAccent1Muted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent1MutedLight) }

    @objc open var colorDecorativeAccent1Default: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent1DefaultLight) }

    @objc open var colorDecorativeAccent1Emphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent1EmphasizedLight) }

    @objc open var colorDecorativeAccent2Muted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent2MutedLight) }

    @objc open var colorDecorativeAccent2Default: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent2DefaultLight) }

    @objc open var colorDecorativeAccent2Emphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent2EmphasizedLight) }

    @objc open var colorDecorativeAccent3Muted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent3MutedLight) }

    @objc open var colorDecorativeAccent3Default: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent3DefaultLight) }

    @objc open var colorDecorativeAccent3Emphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent3EmphasizedLight) }

    @objc open var colorDecorativeAccent4Muted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent4MutedLight) }

    @objc open var colorDecorativeAccent4Default: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent4DefaultLight) }

    @objc open var colorDecorativeAccent4Emphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent4EmphasizedLight) }

    @objc open var colorDecorativeAccent5Muted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent5MutedLight) }

    @objc open var colorDecorativeAccent5Default: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent5DefaultLight) }

    @objc open var colorDecorativeAccent5Emphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeAccent5EmphasizedLight) }

    @objc open var colorDecorativeSkinTint100: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeSkinTint100Light) }

    @objc open var colorDecorativeSkinTint200: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeSkinTint200Light) }

    @objc open var colorDecorativeSkinTint300: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeSkinTint300Light) }

    @objc open var colorDecorativeSkinTint400: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeSkinTint400Light) }

    @objc open var colorDecorativeSkinTint500: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeSkinTint500Light) }

    @objc open var colorDecorativeSkinTint600: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeSkinTint600Light) }

    @objc open var colorDecorativeSkinTint700: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeSkinTint700Light) }

    @objc open var colorDecorativeSkinTint800: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeSkinTint800Light) }

    @objc open var colorDecorativeSkinTint900: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorDecorativeSkinTint900Light) }

    // MARK: Semantic token - Colors - Chart

    @objc open var colorChartCategoricalNeutral: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartCategoricalNeutralLight, dark: colorChartCategoricalNeutralDark) }

    // WARNING: #124 - Colors to use sont part of Orange Theme so sont not reachable at this level, as un workaround add raw values
    @objc open var colorChartCategoricalBrand: MultipleColorSemanticTokens { fatalError("🤖 Raw token unavailable for colorChartCategoricalBrand!") }

    @objc open var colorChartCategoricalPositive: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorChartCategoricalPositiveLight) }

    @objc open var colorChartCategoricalNegative: MultipleColorSemanticTokens { MultipleColorSemanticTokens(colorChartCategoricalNegativeLight) }

    @objc open var colorChartCategoricalTier1: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartCategoricalTier1Light, dark: colorChartCategoricalTier1Dark) }

    @objc open var colorChartCategoricalTier2: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartCategoricalTier2Light, dark: colorChartCategoricalTier2Dark) }

    @objc open var colorChartCategoricalTier3: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartCategoricalTier3Light, dark: colorChartCategoricalTier3Dark) }

    @objc open var colorChartCategoricalTier4: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartCategoricalTier4Light, dark: colorChartCategoricalTier4Dark) }

    @objc open var colorChartCategoricalTier5: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartCategoricalTier5Light, dark: colorChartCategoricalTier5Dark) }

    @objc open var colorChartCategoricalTier6: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartCategoricalTier6Light, dark: colorChartCategoricalTier6Dark) }

    @objc open var colorChartCategoricalTier7: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartCategoricalTier7Light, dark: colorChartCategoricalTier7Dark) }

    @objc open var colorChartCategoricalTier8: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartCategoricalTier8Light, dark: colorChartCategoricalTier8Dark) }

    @objc open var colorChartCategoricalTier9: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartCategoricalTier9Light, dark: colorChartCategoricalTier9Dark) }

    @objc open var colorChartCategoricalTier10: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartCategoricalTier10Light, dark: colorChartCategoricalTier10Dark) }

    @objc open var colorChartSequentialAccent1Tint100: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent1Tint100Light, dark: colorChartSequentialAccent1Tint100Dark) }

    @objc open var colorChartSequentialAccent1Tint200: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent1Tint200Light, dark: colorChartSequentialAccent1Tint200Dark) }

    @objc open var colorChartSequentialAccent1Tint300: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent1Tint300Light, dark: colorChartSequentialAccent1Tint300Dark) }

    @objc open var colorChartSequentialAccent1Tint400: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent1Tint400Light, dark: colorChartSequentialAccent1Tint400Dark) }

    @objc open var colorChartSequentialAccent1Tint500: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent1Tint500Light, dark: colorChartSequentialAccent1Tint500Dark) }

    @objc open var colorChartSequentialAccent1Tint600: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent1Tint600Light, dark: colorChartSequentialAccent1Tint600Dark) }

    @objc open var colorChartSequentialAccent1Tint700: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent1Tint700Light, dark: colorChartSequentialAccent1Tint700Dark) }

    @objc open var colorChartSequentialAccent1Tint800: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent1Tint800Light, dark: colorChartSequentialAccent1Tint800Dark) }

    @objc open var colorChartSequentialAccent1Tint900: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent1Tint900Light, dark: colorChartSequentialAccent1Tint900Dark) }

    @objc open var colorChartSequentialAccent2Tint100: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent2Tint100Light, dark: colorChartSequentialAccent2Tint100Dark) }

    @objc open var colorChartSequentialAccent2Tint200: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent2Tint200Light, dark: colorChartSequentialAccent2Tint200Dark) }

    @objc open var colorChartSequentialAccent2Tint300: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent2Tint300Light, dark: colorChartSequentialAccent2Tint300Dark) }

    @objc open var colorChartSequentialAccent2Tint400: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent2Tint400Light, dark: colorChartSequentialAccent2Tint400Dark) }

    @objc open var colorChartSequentialAccent2Tint500: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent2Tint500Light, dark: colorChartSequentialAccent2Tint500Dark) }

    @objc open var colorChartSequentialAccent2Tint600: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent2Tint600Light, dark: colorChartSequentialAccent2Tint600Dark) }

    @objc open var colorChartSequentialAccent2Tint700: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent2Tint700Light, dark: colorChartSequentialAccent2Tint700Dark) }

    @objc open var colorChartSequentialAccent2Tint800: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent2Tint800Light, dark: colorChartSequentialAccent2Tint800Dark) }

    @objc open var colorChartSequentialAccent2Tint900: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent2Tint900Light, dark: colorChartSequentialAccent2Tint900Dark) }

    @objc open var colorChartSequentialAccent3Tint100: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent3Tint100Light, dark: colorChartSequentialAccent3Tint100Dark) }

    @objc open var colorChartSequentialAccent3Tint200: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent3Tint200Light, dark: colorChartSequentialAccent3Tint200Dark) }

    @objc open var colorChartSequentialAccent3Tint300: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent3Tint300Light, dark: colorChartSequentialAccent3Tint300Dark) }

    @objc open var colorChartSequentialAccent3Tint400: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent3Tint400Light, dark: colorChartSequentialAccent3Tint400Dark) }

    @objc open var colorChartSequentialAccent3Tint500: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent3Tint500Light, dark: colorChartSequentialAccent3Tint500Dark) }

    @objc open var colorChartSequentialAccent3Tint600: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent3Tint600Light, dark: colorChartSequentialAccent3Tint600Dark) }

    @objc open var colorChartSequentialAccent3Tint700: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent3Tint700Light, dark: colorChartSequentialAccent3Tint700Dark) }

    @objc open var colorChartSequentialAccent3Tint800: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent3Tint800Light, dark: colorChartSequentialAccent3Tint800Dark) }

    @objc open var colorChartSequentialAccent3Tint900: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent3Tint900Light, dark: colorChartSequentialAccent3Tint900Dark) }

    @objc open var colorChartSequentialAccent4Tint100: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent4Tint100Light, dark: colorChartSequentialAccent4Tint100Dark) }

    @objc open var colorChartSequentialAccent4Tint200: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent4Tint200Light, dark: colorChartSequentialAccent4Tint200Dark) }

    @objc open var colorChartSequentialAccent4Tint300: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent4Tint300Light, dark: colorChartSequentialAccent4Tint300Dark) }

    @objc open var colorChartSequentialAccent4Tint400: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent4Tint400Light, dark: colorChartSequentialAccent4Tint400Dark) }

    @objc open var colorChartSequentialAccent4Tint500: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent4Tint500Light, dark: colorChartSequentialAccent4Tint500Dark) }

    @objc open var colorChartSequentialAccent4Tint600: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent4Tint600Light, dark: colorChartSequentialAccent4Tint600Dark) }

    @objc open var colorChartSequentialAccent4Tint700: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent4Tint700Light, dark: colorChartSequentialAccent4Tint700Dark) }

    @objc open var colorChartSequentialAccent4Tint800: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent4Tint800Light, dark: colorChartSequentialAccent4Tint800Dark) }

    @objc open var colorChartSequentialAccent4Tint900: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent4Tint900Light, dark: colorChartSequentialAccent4Tint900Dark) }

    @objc open var colorChartSequentialAccent5Tint100: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent5Tint100Light, dark: colorChartSequentialAccent5Tint100Dark) }

    @objc open var colorChartSequentialAccent5Tint200: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent5Tint200Light, dark: colorChartSequentialAccent5Tint200Dark) }

    @objc open var colorChartSequentialAccent5Tint300: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent5Tint300Light, dark: colorChartSequentialAccent5Tint300Dark) }

    @objc open var colorChartSequentialAccent5Tint400: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent5Tint400Light, dark: colorChartSequentialAccent5Tint400Dark) }

    @objc open var colorChartSequentialAccent5Tint500: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent5Tint500Light, dark: colorChartSequentialAccent5Tint500Dark) }

    @objc open var colorChartSequentialAccent5Tint600: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent5Tint600Light, dark: colorChartSequentialAccent5Tint600Dark) }

    @objc open var colorChartSequentialAccent5Tint700: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent5Tint700Light, dark: colorChartSequentialAccent5Tint700Dark) }

    @objc open var colorChartSequentialAccent5Tint800: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent5Tint800Light, dark: colorChartSequentialAccent5Tint800Dark) }

    @objc open var colorChartSequentialAccent5Tint900: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colorChartSequentialAccent5Tint900Light, dark: colorChartSequentialAccent5Tint900Dark) }
}

// swiftlint:enable line_length
// swiftlint:enable identifier_name
