//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensRaw
import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable line_length

/// Defines wrapper objects for elevation color semantic  tokens using ``MultipleColorSemanticTokens`` so as to exposed colors for light and dark color schemes.
/// These values can be overriden inside `OUDSElevationSemanticTokensWrapper` subclasses (in extensions or not, in the same module or not) thanks to the `@objc open` combination.
extension OUDSElevationSemanticTokensWrapper: ElevationMultipleSemanticTokens {

    @objc open var elevationColorDefault: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: elevationColorDefaultLight, dark: elevationColorDefaultDark) }
    @objc open var elevationColorDrag: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: elevationColorDragLight, dark: elevationColorDragDark) }
    @objc open var elevationColorEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: elevationColorEmphasizedLight, dark: elevationColorEmphasizedDark) }
    @objc open var elevationColorNone: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: elevationColorNoneLight, dark: elevationColorNoneDark) }
    @objc open var elevationColorRaised: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: elevationColorRaisedLight, dark: elevationColorRaisedDark) }
    @objc open var elevationColorStickyDefault: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: elevationColorStickyDefaultLight, dark: elevationColorStickyDefaultDark) }
    @objc open var elevationColorStickyEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: elevationColorStickyEmphasizedLight, dark: elevationColorStickyEmphasizedDark) }
    @objc open var elevationColorStickyNavigationScrolled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: elevationColorStickyNavigationScrolledLight, dark: elevationColorStickyNavigationScrolledDark) }
}

// swiftlint:enable line_length
