//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// 🧬 Tokens version: 1.7.0 (Core OUDS)
// 🤖 Generated by Tokenator

extension DimensionRawTokens {
    /// Has for value 0
    public static let _0: DimensionRawToken = dimensionBase * 0 // 0px
    /// Has for value 4
    public static let _50: DimensionRawToken = dimensionBase * 1 // 4px
    /// Has for value 8
    public static let _100: DimensionRawToken = dimensionBase * 2 // 8px
    /// Has for value 12
    public static let _150: DimensionRawToken = dimensionBase * 3 // 12px
    /// Has for value 16
    public static let _200: DimensionRawToken = dimensionBase * 4 // 16px
    /// Has for value 20
    public static let _250: DimensionRawToken = dimensionBase * 5 // 20px
    /// Has for value 24
    public static let _300: DimensionRawToken = dimensionBase * 6 // 24px
    /// Has for value 28
    public static let _350: DimensionRawToken = dimensionBase * 7 // 28px
    /// Has for value 32
    public static let _400: DimensionRawToken = dimensionBase * 8 // 32px
    /// Has for value 36
    public static let _450: DimensionRawToken = dimensionBase * 9 // 36px
    /// Has for value 40
    public static let _500: DimensionRawToken = dimensionBase * 10 // 40px
    /// Has for value 44
    public static let _550: DimensionRawToken = dimensionBase * 11 // 44px
    /// Has for value 48
    public static let _600: DimensionRawToken = dimensionBase * 12 // 48px
    /// Has for value 52
    public static let _650: DimensionRawToken = dimensionBase * 13 // 52px
    /// Has for value 56
    public static let _700: DimensionRawToken = dimensionBase * 14 // 56px
    /// Has for value 60
    public static let _750: DimensionRawToken = dimensionBase * 15 // 60px
    /// Has for value 64
    public static let _800: DimensionRawToken = dimensionBase * 16 // 64px
    /// Has for value 68
    public static let _850: DimensionRawToken = dimensionBase * 17 // 68px
    /// Has for value 72
    public static let _900: DimensionRawToken = dimensionBase * 18 // 72px
    /// Has for value 76
    public static let _950: DimensionRawToken = dimensionBase * 19 // 76px
    /// Has for value 80
    public static let _1000: DimensionRawToken = dimensionBase * 20 // 80px
    /// Has for value 88
    public static let _1100: DimensionRawToken = dimensionBase * 22 // 88px
    /// Has for value 96
    public static let _1200: DimensionRawToken = dimensionBase * 24 // 96px
    /// Has for value 100
    public static let _1250: DimensionRawToken = dimensionBase * 25 // 100px
    /// Has for value 112
    public static let _1400: DimensionRawToken = dimensionBase * 28 // 112px
    /// Has for value 128
    public static let _1600: DimensionRawToken = dimensionBase * 32 // 128px
    /// Has for value 144
    public static let _1800: DimensionRawToken = dimensionBase * 36 // 144px
    /// Has for value 160
    public static let _2000: DimensionRawToken = dimensionBase * 40 // 160px
    /// Has for value 200
    public static let _2225: DimensionRawToken = dimensionBase * 50 // 200px
    /// Has for value 240
    public static let _2500: DimensionRawToken = dimensionBase * 60 // 240px
    /// Has for value 320
    public static let _3000: DimensionRawToken = dimensionBase * 80 // 320px
    /// Has for value 480
    public static let _4000: DimensionRawToken = dimensionBase * 120 // 480px
    /// Has for value 560
    public static let _5000: DimensionRawToken = dimensionBase * 140 // 560px
    /// Has for value 640
    public static let _6000: DimensionRawToken = dimensionBase * 160 // 640px
    /// Has for value 720
    public static let _7000: DimensionRawToken = dimensionBase * 180 // 720px
    /// Has for value 880
    public static let _9000: DimensionRawToken = dimensionBase * 220 // 880px
    /// Has for value 1040
    public static let _11000: DimensionRawToken = dimensionBase * 260 // 1040px
    /// Has for value 4
    public static let dimensionBase: Double = 4
    /// Has for value 1
    public static let outOfSystem25: DimensionRawToken = dimensionBase * 0.25 // 1px
    /// Has for value 2
    public static let outOfSystem50: DimensionRawToken = dimensionBase * 0.5 // 2px
    /// Has for value 3
    public static let outOfSystem75: DimensionRawToken = dimensionBase * 0.75 // 3px
    /// Has for value 6
    public static let outOfSystem150: DimensionRawToken = dimensionBase * 1.5 // 6px
    /// Has for value 10
    public static let outOfSystem250: DimensionRawToken = dimensionBase * 2.5 // 10px
}
