//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// 🧬 Tokens version: 1.9.0 (Core OUDS)
// 🤖 Generated by Tokenator

extension GridRawTokens {
    /// Has for value 320
    public static let minWidthExtraCompact: GridRawToken = 320
    /// Has for value 390
    public static let minWidthCompact: GridRawToken = 390
    /// Has for value 736
    public static let minWidthRegular: GridRawToken = 736
    /// Has for value 389
    public static let maxWidthExtraCompact: GridRawToken = 389
    /// Has for value 852
    public static let maxWidthCompact: GridRawToken = 852
    /// Has for value 1_336
    public static let maxWidthRegular: GridRawToken = 1_336
    /// Has for value 16
    public static let margin100: GridRawToken = DimensionRawTokens.base * 4 // 16 points
    /// Has for value 24
    public static let margin300: GridRawToken = DimensionRawTokens.base * 6 // 24 points
    /// Has for value 28
    public static let margin400: GridRawToken = DimensionRawTokens.base * 7 // 28 points
    /// Has for value 32
    public static let margin500: GridRawToken = DimensionRawTokens.base * 8 // 32 points
    /// Has for value 36
    public static let margin600: GridRawToken = DimensionRawTokens.base * 9 // 36 points
    /// Has for value 40
    public static let margin700: GridRawToken = DimensionRawTokens.base * 10 // 40 points
    /// Has for value 52
    public static let margin1000: GridRawToken = DimensionRawTokens.base * 13 // 52 points
    /// Has for value 56
    public static let margin1100: GridRawToken = DimensionRawTokens.base * 14 // 56 points
    /// Has for value 80
    public static let margin1700: GridRawToken = DimensionRawTokens.base * 20 // 80 points
    /// Has for value 112
    public static let margin2500: GridRawToken = DimensionRawTokens.base * 28 // 112 points
    /// Has for value 1
    public static let columnGap10: GridRawToken = DimensionRawTokens.base * 0.25 // 1 points
    /// Has for value 8
    public static let columnGap100: GridRawToken = DimensionRawTokens.base * 2 // 8 points
    /// Has for value 16
    public static let columnGap200: GridRawToken = DimensionRawTokens.base * 4 // 16 points
    /// Has for value 20
    public static let columnGap300: GridRawToken = DimensionRawTokens.base * 5 // 20 points
    /// Has for value 24
    public static let columnGap400: GridRawToken = DimensionRawTokens.base * 6 // 24 points
    /// Has for value 32
    public static let columnGap600: GridRawToken = DimensionRawTokens.base * 8 // 32 points
    /// Has for value 40
    public static let columnGap800: GridRawToken = DimensionRawTokens.base * 10 // 40 points
    /// Has for value 1
    public static let columnCount100: GridRawToken = 1
    /// Has for value 2
    public static let columnCount200: GridRawToken = 2
    /// Has for value 4
    public static let columnCount400: GridRawToken = 4
    /// Has for value 6
    public static let columnCount600: GridRawToken = 6
    /// Has for value 8
    public static let columnCount800: GridRawToken = 8
    /// Has for value 10
    public static let columnCount1000: GridRawToken = 10
    /// Has for value 12
    public static let columnCount1200: GridRawToken = 12
}
