//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

/// Defined as the group of all **raw tokens** related to **font**.
/// Values are defined in *FontRawTokens+Values.swift* file  generated by the tokenator and in *FontRawTokens+Composites.swift* updated manualy by the develoment team.
/// ``FontRawTokens`` are tokens to use for *font* things , i.e. kind of values to use to render texts.
/// These tokens define:
///     - the *font family* to apply (``FontFamilyRawToken``)
///     - the *font weight* (``FontWeightRawToken``),
///     - the *font size* (``FontSizeRawToken``)
///     - the line height (``FontLineHeightRawToken``)
///     - and the *font letter spacing* (``FontLetterSpacingRawToken``).
/// Combinations of these raw tokens can be made inside ``FontCompositeRawToken``, which are composite tokens defining in the end a specific font to apply.
///
/// Primitive types such as `Int` and `String` must be used to as to allow to use `@objc` keywords in extensions for overriding.
/// Such tokens are packed in a _Swift enum_ so as to gather them in one object with the suitable namespace and avoid to have just constants in nothing else
///  (i.e. publicly accessible from everywhere). More optimized than _struct_.
///
/// - Since: 0.8.0
public enum FontRawTokens {

    // ଘ( ･ω･)_/ﾟ･:*:･｡☆
    // Note: So as to help the tokenator, the values have been added in the Values folder
    // This trick helps also to write documentation for these tokens as the tokenator cannot generate documentation
}
