//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensRaw
import OUDSTokensSemantic

// 🧬 Tokens version: 2.7.0 (Orange Compact brand)
// 🤖 Generated by Tokenator

extension OrangeCompactThemeTextInputComponentTokensProvider: TextInputComponentTokens {
    /// Has for value token borders.radiusDefault (= 0)
    @objc public final var borderRadiusDefault: BorderRadiusSemanticToken { borders.radiusDefault }
    /// Has for value token borders.radiusMedium (= 8)
    @objc public final var borderRadiusRounded: BorderRadiusSemanticToken { borders.radiusMedium }
    /// Has for value token borders.widthDefault (= 1)
    @objc public final var borderWidthDefault: BorderWidthSemanticToken { borders.widthDefault }
    /// Has for value token borders.widthMedium (= 2)
    @objc public final var borderWidthFocus: BorderWidthSemanticToken { borders.widthMedium }
    /// Has for value token colors.borderDefault (= light: "#00000033" / dark: "#FFFFFF33")
    @objc public final var colorBorderEnabled: MultipleColorSemanticToken { colors.borderDefault }
    /// Has for value token colors.borderEmphasized (= light: "#000000FF" / dark: "#EEEEEEFF")
    @objc public final var colorBorderFocus: MultipleColorSemanticToken { colors.borderEmphasized }
    /// Has for value token colors.actionHover (= light: "#000000AD" / dark: "#FFFFFFA3")
    @objc public final var colorBorderHover: MultipleColorSemanticToken { colors.actionHover }
    /// Has for value token colors.borderEmphasized (= light: "#000000FF" / dark: "#EEEEEEFF")
    @objc public final var colorBorderLoading: MultipleColorSemanticToken { colors.borderEmphasized }
    /// Has for value token sizes.iconWithLabelLargeSizeXsmall (= 16)
    @objc public final var sizeCountrySelectorFlagHeight: SizeSemanticToken { sizes.iconWithLabelLargeSizeXsmall }
    /// Has for value token DimensionRawTokens._500 (= 40)
    @objc public final var sizeLabelMaxHeight: SizeSemanticToken { DimensionRawTokens._500 }
    /// Has for value token sizes.iconWithLabelLargeSizeSmall (= 20)
    @objc public final var sizeLeadingIcon: SizeSemanticToken { sizes.iconWithLabelLargeSizeSmall }
    /// Has for value token DimensionRawTokens._4000 (= 480)
    @objc public final var sizeMaxWidth: SizeSemanticToken { DimensionRawTokens._4000 }
    /// Has for value token DimensionRawTokens._650 (= 52)
    @objc public final var sizeMinHeight: SizeSemanticToken { DimensionRawTokens._650 }
    /// Has for value token DimensionRawTokens._2500 (= 240)
    @objc public final var sizeMinWidth: SizeSemanticToken { DimensionRawTokens._2500 }
    /// Has for value token dimensions._4xsmall (= 16)
    @objc public final var sizeVerticalDividerHeight: SizeSemanticToken { dimensions._4xsmall }
    /// Has for value token {ouds1f4a0_columnGapMedium (= 10)
    @objc public final var spaceColumnGapDefault: SpaceSemanticToken { {ouds1f4a0_columnGapMedium }
    /// Has for value token {ouds1f4a0_columnGapXsmall (= 6)
    @objc public final var spaceColumnGapInlineText: SpaceSemanticToken { {ouds1f4a0_columnGapXsmall }
    /// Has for value token {ouds1f4a0_columnGap2xsmall (= 4)
    @objc public final var spaceColumnGapLabelAsterisk: SpaceSemanticToken { {ouds1f4a0_columnGap2xsmall }
    /// Has for value token DimensionRawTokens.outOfSystem75 (= 3)
    @objc public final var spaceColumnGapLabelSmallAsterisk: SpaceSemanticToken { DimensionRawTokens.outOfSystem75 }
    /// Has for value token {ouds1f4a0_columnGapXsmall (= 6)
    @objc public final var spaceColumnGapTrailingErrorAction: SpaceSemanticToken { {ouds1f4a0_columnGapXsmall }
    /// Has for value token {ouds1f4a0_paddingBlock2xsmall (= 6)
    @objc public final var spacePaddingBlockDefault: SpaceSemanticToken { {ouds1f4a0_paddingBlock2xsmall }
    /// Has for value token {ouds1f4a0_paddingBlockXsmall (= 8)
    @objc public final var spacePaddingBlockTopHelperText: SpaceSemanticToken { {ouds1f4a0_paddingBlockXsmall }
    /// Has for value token {ouds1f4a0_paddingInlineXsmall (= 8)
    @objc public final var spacePaddingInlineCountrySelectorEnd: SpaceSemanticToken { {ouds1f4a0_paddingInlineXsmall }
    /// Has for value token {ouds1f4a0_paddingInlineSmall (= 10)
    @objc public final var spacePaddingInlineCountrySelectorStart: SpaceSemanticToken { {ouds1f4a0_paddingInlineSmall }
    /// Has for value token {ouds1f4a0_paddingInlineLarge (= 12)
    @objc public final var spacePaddingInlineDefault: SpaceSemanticToken { {ouds1f4a0_paddingInlineLarge }
    /// Has for value token {ouds1f4a0_paddingInline2xsmall (= 6)
    @objc public final var spacePaddingInlineTrailingAction: SpaceSemanticToken { {ouds1f4a0_paddingInline2xsmall }
    /// Has for value token {ouds1f4a0_rowGapNone (= 0)
    @objc public final var spaceRowGapLabelInput: SpaceSemanticToken { {ouds1f4a0_rowGapNone }
}
