//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensSemantic

// 🧬 Tokens version: 2.7.0 (Orange Compact brand)
// 🤖 Generated by Tokenator

// swiftlint:disable identifier_name

extension OrangeCompactThemeAccordionComponentTokensProvider: AccordionComponentTokens {
    /// Has for value token {ouds1f4a0_paddingBlock3xlarge (= 24)
    @objc public final var spacePaddingBlockBottomExpandContainerDefault: SpaceSemanticToken { {ouds1f4a0_paddingBlock3xlarge }
    /// Has for value token {ouds1f4a0_paddingBlock2xlarge (= 20)
    @objc public final var spacePaddingBlockBottomExpandContainerSmall: SpaceSemanticToken { {ouds1f4a0_paddingBlock2xlarge }
    /// Has for value token {ouds1f4a0_paddingBlockXsmall (= 8)
    @objc public final var spacePaddingBlockTopExpandContainer: SpaceSemanticToken { {ouds1f4a0_paddingBlockXsmall }
}

// swiftlint:enable identifier_name
