name: Report a bug
description: Tell us about a bug or issue you may have identified in OUDS iOS.
title: "When / For / In / On ... "
labels: ["🐞 bug", "🔍 triage"]
assignees: ["ludovic35", "pylapp"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-ios/issues) for duplicate or closed feature requests
          required: true
  - type: input
    id: device
    attributes:
      label: Your test device
      description: 
      placeholder: iPhone 13 pro
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: Device OS version
      description: 
      placeholder: iOS 15.1
    validations:
      required: true
  - type: input
    id: app-ouds-lib-version
    attributes:
      label: OUDS iOS library version
      placeholder: "1.0.0"
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: Design System Toolbox app version
      placeholder: 1.0.0
  - type: input
    id: app-build-number
    attributes:
      label: Design System Toolbox app build number
      placeholder: "1766065729"         
  - type: input
    id: app-build-type
    attributes:
      label: Design System Toolbox app build type
      placeholder: alpha, beta, prod, debug
    validations:
      required: false             
  - type: input
    id: app-orientation
    attributes:
      label: Design System Toolbox app orientation
      placeholder: Portrait and / or landscape
    validations:
      required: false
  - type: input
    id: app-language
    attributes:
      label: Design System Toolbox app language
      placeholder: English
    validations:
      required: false   
  - type: input
    id: device-language
    attributes:
      label: Device language
      placeholder: English
    validations:
      required: false   
  - type: input
    id: app-token-lib-version
    attributes:
      label: Tokens libraries versions embeded in the app
      placeholder: "Orange 1.1.0, Core 1.2.0, Sosh 1.0.0, ..."
    validations:
      required: false 
  - type: input
    id: xcode-version
    attributes:
      label: Xcode version
      placeholder: "Add 'xcodebuild -version' command outputs"
    validations:
      required: false
  - type: input
    id: swift-version
    attributes:
      label: Swift version
      placeholder: "Add 'swift --version' command outputs"
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue, including specific steps to reproduce with as much detail as possible. Do not forget to hide sensitive or personal data (phone numbers, accounts, messages, emails etc).
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Provide a description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: a11y-settings
    attributes:
      label: Accessibility settings
      description: Provide a description about the accessibility settings you have (vocalization with Voice Over, increased text sizes, keyboard navigation, high contrast, etc.)
    validations:
      required: true