name: Report a bug
description: Tell us about a bug or issue you may have identified in OUDS iOS.
title: "[Bug] "
labels: ["🐞 bug", "🔍 triage"]
assignees: ["ludovic35", "pylapp", "Tayebsed93"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched the backlog](https://github.com/Orange-OpenSource/ouds-ios/issues) for duplicate or closed feature requests
          required: true
  - type: input
    id: device
    attributes:
      label: Your test device
      description: 
      placeholder: iPhone 13 pro
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: 
      placeholder: iOS 15.1
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: App version
      placeholder: v1.0.1 (build 42)
    validations:
      required: true
  - type: input
    id: app-orientation
    attributes:
      label: App orientation
      placeholder: Portrait and / or landscape
    validations:
      required: false
  - type: input
    id: device-language
    attributes:
      label: Device language
      placeholder: Arabic
    validations:
      required: false
  - type: input
    id: app-language
    attributes:
      label: App language
      placeholder: English
    validations:
      required: false      
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue, including specific steps to reproduce with as much detail as possible. Do not forget to hide sensitive or personal data (phone numbers, accounts, messages, emails etc).
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Provide a description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: a11y-settings
    attributes:
      label: Accessibility settings
      description: Provide a description about the accessibility settings you have (vocalization with Voice Over, increased text sizes, keyboard navigation, high contrast, etc.)
    validations:
      required: true