name: Component Request
description: Please fill out the following details for your component creation / update request.
title: "For / Add component ..."
labels: ["🧰 library", "⚛️ component", "🔍 triage"]
assignees: ["ludovic35", "pylapp"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your need in details
    validations:
      required: true      
  - type: textarea
    id: motivation_context
    attributes:
      label: Motivation & Context
      description: Why is this evolution required? What problem does it solve?
  - type: checkboxes
    attributes:
      label: Types of change
      description: Please fill the suitable items in the list
      options:
        - label: Add new component
        - label: Update existing component  
  - type: checkboxes
    attributes:
      label: Checklist for Core Team
      description: Some points to check before any merge
      options:
        - label: Tokens library have been updated if needed
        - label: Technical Swift DocC documentation has been updated
        - label: AI agents skills files have been updated
        - label: Unit tests have been updated
        - label: UI tests have been updated
        - label: Accessibility has been considered with Voice Over navigation
        - label: Accessibility has been considered with Full Keyboard Access navigation
        - label: Accessibility has been considered with Switch Control navigation
        - label: Accessibility has been considered with reduced animations
        - label: Accessibility has been considered with Dynamic Types usages
        - label: Ecodesign has been considered with low power mode
        - label: Snapshots tests have been updated
        - label: Design System Toolbox has been updated
        - label: Tested on iOS
        - label: Tested on iPadOS
        - label: Tested on tvOS
        - label: Tested on macOS
        - label: Tested on visionOS
        - label: Tested on watchOS
        - label: Retrocompatibility has been checked, or broken API have been flagged as deprecated with a workaround