name: Design System Toolbox App Update Request
description: Please fill out the following details for your design system toolbox app update request.
title: "[Design System Toolbox] "
labels: ["📱 demo app", "🔍 triage"]
assignees: ["ludovic35", "pylapp"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your need in details. Which screens? Which tokens, components or modules?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Checklist for Core Team
      description: Some points to check before any merge
      options:
        - label: Tokens have been updated (if needed)
        - label: Documentations have been updated (if needed)
        - label: Unit tests have been updated and still pass
        - label: UI tests have been updated and still pass
        - label: Retrocompatibility has been checked, or broken API have been flagged as deprecated with a workaround