name: Module Request
description: Please fill out the following details for your module creation / update request.
title: "For / Add module ..."
labels: ["🧰 library", "🎇 module", "🔍 triage"]
assignees: ["ludovic35", "pylapp"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your need in details
    validations:
      required: true      
  - type: textarea
    id: motivation_context
    attributes:
      label: Motivation & Context
      description: Why is this evolution required? What problem does it solve?
  - type: checkboxes
    attributes:
      label: Types of change
      description: Please fill the suitable items in the list
      options:
        - label: Add new module
        - label: Update existing module  
  - type: checkboxes
    attributes:
      label: Checklist for Core Team
      description: Some points to check before any merge
      options:
        - label: Documentations have been updated
        - label: Tests have been updated if needed
        - label: Demo app has been updated if needed
        - label: Retrocompatibility has been checked, or broken API have been flagged as deprecated with a workaround