name: Token Update Request
description: Please fill out the following details for your token update request.
title: "[Token Update] - Title"
labels: ["📀 token", "🔍 triage"]
assignees: ["ludovic35", "pylapp", "Tayebsed93"]
body:
  - type: markdown
    attributes:
      value: |
        ### Type of tokens
        Please fill the checkboxes of the token type you want to update:
        - [ ] Raw token (i.e. associated to _SwiftUI_ or _Swift_ value)
        - [ ] Semantic token (i.e. pointing to a raw token)
        - [ ] Component token (i.e. pointing to a semantic token, used for a component)
    validations:
      required: true        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your need in details
    validations:
      required: true      
  - type: textarea
    id: motivation_context
    attributes:
      label: Motivation & Context
      description: Why is this change required? What problem does it solve?
    validations:
      required: true      
  - type: markdown
    attributes:
      value: |
        ### Types of change
        Please fill the suitable items in the list:
        - [ ] Add new tokens
        - [ ] Update existing tokens (i.e. change name or value)
        - [ ] Remove existing token
    validations:
      required: true        
  - type: markdown
    attributes:
      value: |
        ### Checklist for Core Team
        - [ ] Tokens have been updated
        - [ ] Documentation have been updated
        - [ ] Unit tests have been updated
        - [ ] Retrocompatibility has been checked, or broken API have been flagged as deprecated without a workaround

