name: Token Update Request
description: Please fill out the following details for your token update request.
title: "[Token Update] "
labels: ["📀 token", "🔍 triage"]
assignees: ["ludovic35", "pylapp", "Tayebsed93"]
body:
  - type: checkboxes
    attributes:
      label: Type of tokens
      description: Please fill the checkboxes of the token type you want to update
      options:
        - label: Raw token (i.e. associated to _SwiftUI_ or _Swift_ value)
        - label: Semantic token (i.e. pointing to a raw token)
        - label: Component token (i.e. pointing to a semantic token, used for a component)
    validations:
      required: true        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe your need in details
    validations:
      required: true      
  - type: textarea
    id: motivation_context
    attributes:
      label: Motivation & Context
      description: Why is this change required? What problem does it solve?
    validations:
      required: true     
  - type: checkboxes
    attributes:
      label: Types of change
      description: Please fill the suitable items in the list
      options:
        - label: Add new tokens
        - label: Update existing tokens (i.e. change name or value)
        - label: Remove existing token
    validations:
      required: true      
  - type: checkboxes
    attributes:
      label: Checklist for Core Team
      description: Some points to check before any merge
      options:
        - label: Tokens have been updated
        - label: Documentation have been updated
        - label: Unit tests have been updated
        - label: Retrocompatibility has been checked, or broken API has been flagged as deprecated with a workaround