//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **colors charts**.
/// It defines all ``ColorSemanticToken``  a theme must have for charts.
/// These tokens are then gathered inside ``MultipleColorSemanticTokens`` objects defined in ``ColorMultipleSemanticTokens``.
///
/// - Since: 0.17.0
public protocol ColorChartMultipleSemanticTokens {

    var border: MultipleColorSemanticTokens { get }
    var borderContrast: MultipleColorSemanticTokens { get }
    var categoricalTier1: MultipleColorSemanticTokens { get }
    var categoricalTier2: MultipleColorSemanticTokens { get }
    var categoricalTier3: MultipleColorSemanticTokens { get }
    var categoricalTier4: MultipleColorSemanticTokens { get }
    var categoricalTier5: MultipleColorSemanticTokens { get }
    var categoricalTier6: MultipleColorSemanticTokens { get }
    var categoricalTier7: MultipleColorSemanticTokens { get }
    var categoricalTier8: MultipleColorSemanticTokens { get }
    var categoricalTier9: MultipleColorSemanticTokens { get }
    var categoricalTier10: MultipleColorSemanticTokens { get }
    var functionalInfo: MultipleColorSemanticTokens { get }
    var functionalNegative: MultipleColorSemanticTokens { get }
    var functionalPositive: MultipleColorSemanticTokens { get }
    var functionalWarning: MultipleColorSemanticTokens { get }
    var gridlines: MultipleColorSemanticTokens { get }
    var highlight: MultipleColorSemanticTokens { get }
    var neutral: MultipleColorSemanticTokens { get }
}

// swiftlint:enable missing_docs
