//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **colors charts**.
/// It defines all ``ColorSemanticToken``  a theme must have for charts.
/// These tokens are then gathered inside ``MultipleColorSemanticToken`` objects defined in ``ColorMultipleSemanticTokens``.
///
/// - Since: 0.17.0
public protocol ColorChartMultipleSemanticTokens {

    var border: MultipleColorSemanticToken { get }
    var borderContrast: MultipleColorSemanticToken { get }
    var categoricalTier1: MultipleColorSemanticToken { get }
    var categoricalTier2: MultipleColorSemanticToken { get }
    var categoricalTier3: MultipleColorSemanticToken { get }
    var categoricalTier4: MultipleColorSemanticToken { get }
    var categoricalTier5: MultipleColorSemanticToken { get }
    var categoricalTier6: MultipleColorSemanticToken { get }
    var categoricalTier7: MultipleColorSemanticToken { get }
    var categoricalTier8: MultipleColorSemanticToken { get }
    var categoricalTier9: MultipleColorSemanticToken { get }
    var categoricalTier10: MultipleColorSemanticToken { get }
    var functionalInfo: MultipleColorSemanticToken { get }
    var functionalNegative: MultipleColorSemanticToken { get }
    var functionalPositive: MultipleColorSemanticToken { get }
    var functionalWarning: MultipleColorSemanticToken { get }
    var gridlines: MultipleColorSemanticToken { get }
    var highlight: MultipleColorSemanticToken { get }
    var neutral: MultipleColorSemanticToken { get }
}

// swiftlint:enable missing_docs
