//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs
// swiftlint:disable line_length

/// This is a group of semantic tokens for **colors** but using ``MultipleColorSemanticToken``.
///
/// In fact the ``MultipleColorSemanticToken`` class will help users (i.e. developers) to handle one semantic token for color containing values for light and dark modes.
/// Because *Figma* is not able to manage pair of values for one token, and its produced JSON does not reflect this mecanism, the *tokenator* cannot provide such ``MultipleColorSemanticToken``. Thus the "real" color semantic tokens are declared in ``ColorSemanticTokens`` protocol and defined inside  a `OUDSTheme`. These tokens are updated by the *tokenator*. Then they are gathered and wrapped so as to be used easily thanks to this ``ColorMultipleSemanticTokens`` which must be updated manually.
///
/// In few words:
///
/// ```swift
///         // Some color raw tokens, defined by the tokenator (in ColorRawTokens+Values.swift)
///         public static let colorDecorativeAmber100: ColorRawToken = "#FFF0CC00"
///         public static let colorDecorativeAmber200: ColorRawToken = "#FFE199FF"
///
///         // The color semantic tokens using them
///         // declared (in ColorSemanticTokens.swift) and defined (in OUDSTheme+ColorSemanticTokens.swift) by the tokenator
///         var bgPrimary: ColorSemanticTokens { ColorRawTokens.colorDecorativeAmber100 }
///         var bgPrimaryDark: ColorSemanticTokens { ColorRawTokens.colorDecorativeAmber200 }
///
///         // The 'higher level' color semantic tokens wrapping them and exposed to users
///         // declared (in this ColorMultipleSemanticTokens.swift) and defined manualy (in OUDSTheme+ColorMultipleSemanticTokens.swift)
///         var bgPrimary: MultipleColorSemanticToken { MultipleColorSemanticToken(: bgPrimaryLight, dark: bgPrimaryDark) }
///
///         // Thus users can in their components use bgPrimary as defined in their design system
///         // (even if they are still able to use 'lower level' semantic tokens but it is more error-prone)
/// ```
///
/// - Since: 0.8.0
public protocol ColorMultipleSemanticTokens {

    // NOTE: repository* color semantic tokens are closed
    // used indirectly and it seems to not be that much useful and relevant
    // to wrap them in MultipleColorSemanticToken.

    // MARK: - Color - Opacity

    var opacityLowest: MultipleColorSemanticToken { get }

    var opacityLower: MultipleColorSemanticToken { get }

    var opacityTransparent: MultipleColorSemanticToken { get }

    // MARK: - Color - Action

    var actionDisabled: MultipleColorSemanticToken { get }

    var actionEnabled: MultipleColorSemanticToken { get }

    var actionFocus: MultipleColorSemanticToken { get }

    var actionHighlighted: MultipleColorSemanticToken { get }

    var actionHover: MultipleColorSemanticToken { get }

    var actionLoading: MultipleColorSemanticToken { get }

    var actionNegativeEnabled: MultipleColorSemanticToken { get }

    var actionNegativeFocus: MultipleColorSemanticToken { get }

    var actionNegativeHover: MultipleColorSemanticToken { get }

    var actionNegativeLoading: MultipleColorSemanticToken { get }

    var actionNegativePressed: MultipleColorSemanticToken { get }

    var actionPressed: MultipleColorSemanticToken { get }

    var actionSelected: MultipleColorSemanticToken { get }

    var actionSupportEnabled: MultipleColorSemanticToken { get }

    var actionSupportDisabled: MultipleColorSemanticToken { get }

    var actionSupportFocus: MultipleColorSemanticToken { get }

    var actionSupportHover: MultipleColorSemanticToken { get }

    var actionSupportLoading: MultipleColorSemanticToken { get }

    var actionSupportPressed: MultipleColorSemanticToken { get }

    var actionVisited: MultipleColorSemanticToken { get }

    var actionReadOnlyPrimary: MultipleColorSemanticToken { get }

    var actionReadOnlySecondary: MultipleColorSemanticToken { get }

    var actionAccent: MultipleColorSemanticToken { get }

    // MARK: - Color - Background

    var bgPrimary: MultipleColorSemanticToken { get }

    var bgSecondary: MultipleColorSemanticToken { get }

    var bgTertiary: MultipleColorSemanticToken { get }

    var bgInverseHigh: MultipleColorSemanticToken { get }

    var bgInverseLow: MultipleColorSemanticToken { get }

    // MARK: - Color - Border

    var borderBrandPrimary: MultipleColorSemanticToken { get }

    var borderBrandSecondary: MultipleColorSemanticToken { get }

    var borderBrandTertiary: MultipleColorSemanticToken { get }

    var borderDefault: MultipleColorSemanticToken { get }

    var borderEmphasized: MultipleColorSemanticToken { get }

    var borderFocus: MultipleColorSemanticToken { get }

    var borderFocusInset: MultipleColorSemanticToken { get }

    var borderMuted: MultipleColorSemanticToken { get }

    var borderOnBrandPrimary: MultipleColorSemanticToken { get }

    var borderOnBrandSecondary: MultipleColorSemanticToken { get }

    var borderOnBrandTertiary: MultipleColorSemanticToken { get }

    var borderMinimal: MultipleColorSemanticToken { get }

    var borderStatusPositive: MultipleColorSemanticToken { get }

    var borderStatusInfo: MultipleColorSemanticToken { get }

    var borderStatusWarning: MultipleColorSemanticToken { get }

    var borderStatusNegative: MultipleColorSemanticToken { get }

    var borderStatusAccent: MultipleColorSemanticToken { get }

    // MARK: - Color - Content

    var contentBrandPrimary: MultipleColorSemanticToken { get }

    var contentBrandSecondary: MultipleColorSemanticToken { get }

    var contentBrandTertiary: MultipleColorSemanticToken { get }

    var contentDefault: MultipleColorSemanticToken { get }

    var contentDisabled: MultipleColorSemanticToken { get }

    var contentMuted: MultipleColorSemanticToken { get }

    var contentOnActionSelected: MultipleColorSemanticToken { get }

    var contentOnActionDisabled: MultipleColorSemanticToken { get }

    var contentOnActionEnabled: MultipleColorSemanticToken { get }

    var contentOnActionFocus: MultipleColorSemanticToken { get }

    var contentOnActionHighlighted: MultipleColorSemanticToken { get }

    var contentOnActionHover: MultipleColorSemanticToken { get }

    var contentOnActionLoading: MultipleColorSemanticToken { get }

    var contentOnActionPressed: MultipleColorSemanticToken { get }

    var contentOnBrandPrimary: MultipleColorSemanticToken { get }

    var contentOnBrandSecondary: MultipleColorSemanticToken { get }

    var contentOnBrandTertiary: MultipleColorSemanticToken { get }

    var contentOnStatusPositiveMuted: MultipleColorSemanticToken { get }

    var contentOnStatusPositiveEmphasized: MultipleColorSemanticToken { get }

    var contentInverse: MultipleColorSemanticToken { get }

    var contentOnStatusInfoMuted: MultipleColorSemanticToken { get }

    var contentOnStatusInfoEmphasized: MultipleColorSemanticToken { get }

    var contentOnStatusWarningMuted: MultipleColorSemanticToken { get }

    var contentOnStatusWarningEmphasized: MultipleColorSemanticToken { get }

    var contentOnStatusNegativeMuted: MultipleColorSemanticToken { get }

    var contentOnStatusNegativeEmphasized: MultipleColorSemanticToken { get }

    var contentOnStatusAccentMuted: MultipleColorSemanticToken { get }

    var contentOnStatusAccentEmphasized: MultipleColorSemanticToken { get }

    var contentStatusAccent: MultipleColorSemanticToken { get }

    var contentStatusInfo: MultipleColorSemanticToken { get }

    var contentStatusNegative: MultipleColorSemanticToken { get }

    var contentStatusPositive: MultipleColorSemanticToken { get }

    var contentStatusWarning: MultipleColorSemanticToken { get }

    // MARK: - Color - Overlay

    var overlayDropdown: MultipleColorSemanticToken { get }

    var overlayTooltip: MultipleColorSemanticToken { get }

    var overlayDrag: MultipleColorSemanticToken { get }

    var overlayModal: MultipleColorSemanticToken { get }

    // MARK: - Color - Surface

    var surfaceBrandPrimary: MultipleColorSemanticToken { get }

    var surfaceBrandSecondary: MultipleColorSemanticToken { get }

    var surfaceBrandTertiary: MultipleColorSemanticToken { get }

    var surfaceStatusAccentEmphasized: MultipleColorSemanticToken { get }

    var surfaceStatusAccentMuted: MultipleColorSemanticToken { get }

    var surfaceStatusInfoEmphasized: MultipleColorSemanticToken { get }

    var surfaceStatusInfoMuted: MultipleColorSemanticToken { get }

    var surfaceStatusNegativeEmphasized: MultipleColorSemanticToken { get }

    var surfaceStatusNegativeMuted: MultipleColorSemanticToken { get }

    var surfaceInverseHigh: MultipleColorSemanticToken { get }

    var surfaceInverseLow: MultipleColorSemanticToken { get }

    var surfacePrimary: MultipleColorSemanticToken { get }

    var surfaceSecondary: MultipleColorSemanticToken { get }

    var surfaceTertiary: MultipleColorSemanticToken { get }

    var surfaceStatusPositiveEmphasized: MultipleColorSemanticToken { get }

    var surfaceStatusPositiveMuted: MultipleColorSemanticToken { get }

    var surfaceStatusWarningEmphasized: MultipleColorSemanticToken { get }

    var surfaceStatusWarningMuted: MultipleColorSemanticToken { get }
}

// swiftlint:enable missing_docs
// swiftlint:enable line_length
