//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **color charts**.
///
/// - Since: 0.17.0
public protocol ColorChartSemanticTokens {

    var chartBorderLight: ColorSemanticToken { get }
    var chartBorderDark: ColorSemanticToken { get }

    var chartBorderContrastLight: ColorSemanticToken { get }
    var chartBorderContrastDark: ColorSemanticToken { get }

    var chartCategoricalTier1Light: ColorSemanticToken { get }
    var chartCategoricalTier1Dark: ColorSemanticToken { get }

    var chartCategoricalTier2Light: ColorSemanticToken { get }
    var chartCategoricalTier2Dark: ColorSemanticToken { get }

    var chartCategoricalTier3Light: ColorSemanticToken { get }
    var chartCategoricalTier3Dark: ColorSemanticToken { get }

    var chartCategoricalTier4Light: ColorSemanticToken { get }
    var chartCategoricalTier4Dark: ColorSemanticToken { get }

    var chartCategoricalTier5Light: ColorSemanticToken { get }
    var chartCategoricalTier5Dark: ColorSemanticToken { get }

    var chartCategoricalTier6Light: ColorSemanticToken { get }
    var chartCategoricalTier6Dark: ColorSemanticToken { get }

    var chartCategoricalTier7Light: ColorSemanticToken { get }
    var chartCategoricalTier7Dark: ColorSemanticToken { get }

    var chartCategoricalTier8Light: ColorSemanticToken { get }
    var chartCategoricalTier8Dark: ColorSemanticToken { get }

    var chartCategoricalTier9Light: ColorSemanticToken { get }
    var chartCategoricalTier9Dark: ColorSemanticToken { get }

    var chartCategoricalTier10Light: ColorSemanticToken { get }
    var chartCategoricalTier10Dark: ColorSemanticToken { get }

    var chartFunctionalInfoLight: ColorSemanticToken { get }
    var chartFunctionalInfoDark: ColorSemanticToken { get }

    var chartFunctionalNegativeLight: ColorSemanticToken { get }
    var chartFunctionalNegativeDark: ColorSemanticToken { get }

    var chartFunctionalPositiveLight: ColorSemanticToken { get }
    var chartFunctionalPositiveDark: ColorSemanticToken { get }

    var chartFunctionalWarningLight: ColorSemanticToken { get }
    var chartFunctionalWarningDark: ColorSemanticToken { get }

    var chartGridlinesLight: ColorSemanticToken { get }
    var chartGridlinesDark: ColorSemanticToken { get }

    var chartHighlightLight: ColorSemanticToken { get }
    var chartHighlightDark: ColorSemanticToken { get }

    var chartNeutralLight: ColorSemanticToken { get }
    var chartNeutralDark: ColorSemanticToken { get }
}

// swiftlint:enable missing_docs
