//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
// 
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
// 
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System 
//

// [File not generated by the tokenator]
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **colors modes** but using ``MultipleColorModeSemanticTokens``.
///
/// In fact the ``MultipleColorModeSemanticTokens`` class will help users (i.e. developers) to handle one semantic token for color mode containing values for light and dark modes.
/// 
/// In few words:
///
/// ```swift
///
///         // Tokenator defines seevral color mode semantic tokens
///         var modeOnBrandPrimaryLight: ColorModeSemanticToken { ColorModeRawTokens.monochromeLight }
///         var modeOnBrandPrimaryDark: ColorModeSemanticToken { ColorModeRawTokens.monochromeLight }
///
///         // They are packed
///         var modeOnBrandPrimary: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(modeOnBrandPrimary) }
/// ```
///
/// - Since: 0.13.0
public protocol ColorModeMultipleSemanticTokens {

    var modeOnBrandPrimary: MultipleColorModeSemanticTokens { get }

    var modeOnBrandSecondary: MultipleColorModeSemanticTokens { get }

    var modeOnBrandTertiary: MultipleColorModeSemanticTokens { get }

    var modeOnStatusAccentEmphasized: MultipleColorModeSemanticTokens { get }

    var modeOnStatusAccentMuted: MultipleColorModeSemanticTokens { get }

    var modeOnStatusInfoEmphasized: MultipleColorModeSemanticTokens { get }

    var modeOnStatusInfoMuted: MultipleColorModeSemanticTokens { get }

    var modeOnStatusNegativeEmphasized: MultipleColorModeSemanticTokens { get }

    var modeOnStatusNegativeMuted: MultipleColorModeSemanticTokens { get }

    var modeOnStatusNeutralEmphasized: MultipleColorModeSemanticTokens { get }

    var modeOnStatusNeutralMuted: MultipleColorModeSemanticTokens { get }

    var modeOnStatusPositiveEmphasized: MultipleColorModeSemanticTokens { get }

    var modeOnStatusPositiveMuted: MultipleColorModeSemanticTokens { get }

    var modeOnStatusWarningEmphasized: MultipleColorModeSemanticTokens { get }

    var modeOnStatusWarningMuted: MultipleColorModeSemanticTokens { get }
}

// swiftlint:enable missing_docs
