//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs
// swiftlint:disable identifier_name

/// This is a group of semantic tokens for **colors**.
/// It defines all ``ColorSemanticToken``  a theme must have.
/// These tokens are then gathered inside ``MultipleColorSemanticTokens`` objects defined in ``ColorMultipleSemanticTokens``.
/// If it possible a theme won't have such semantic tokens of colors defined as not specified nor used in Figma.
/// Thus the value for these tokens will be "ouds-forbidden-color-value" as returned by the tokenator.
/// Thus if the token is still used, even if explained in the documentation it should not,
/// this special value won't be successfully parsed as color and the app will crash like expected.
///
/// - Since: 0.8.0
public protocol ColorSemanticTokens {

    // MARK: - Color - Opacity

    var opacityLowestLight: ColorSemanticToken { get }
    var opacityLowestDark: ColorSemanticToken { get }

    var opacityLowerLight: ColorSemanticToken { get }
    var opacityLowerDark: ColorSemanticToken { get }

    var opacityTransparentLight: ColorSemanticToken { get }
    var opacityTransparentDark: ColorSemanticToken { get }

    // MARK: - Color - Action

    var actionDisabledLight: ColorSemanticToken { get }
    var actionDisabledDark: ColorSemanticToken { get }

    var actionEnabledLight: ColorSemanticToken { get }
    var actionEnabledDark: ColorSemanticToken { get }

    var actionFocusLight: ColorSemanticToken { get }
    var actionFocusDark: ColorSemanticToken { get }

    var actionHighlightedLight: ColorSemanticToken { get }
    var actionHighlightedDark: ColorSemanticToken { get }

    var actionHoverLight: ColorSemanticToken { get }
    var actionHoverDark: ColorSemanticToken { get }

    var actionLoadingLight: ColorSemanticToken { get }
    var actionLoadingDark: ColorSemanticToken { get }

    var actionNegativeEnabledLight: ColorSemanticToken { get }
    var actionNegativeEnabledDark: ColorSemanticToken { get }

    var actionNegativeFocusLight: ColorSemanticToken { get }
    var actionNegativeFocusDark: ColorSemanticToken { get }

    var actionNegativeHoverLight: ColorSemanticToken { get }
    var actionNegativeHoverDark: ColorSemanticToken { get }

    var actionNegativeLoadingLight: ColorSemanticToken { get }
    var actionNegativeLoadingDark: ColorSemanticToken { get }

    var actionNegativePressedLight: ColorSemanticToken { get }
    var actionNegativePressedDark: ColorSemanticToken { get }

    var actionPressedLight: ColorSemanticToken { get }
    var actionPressedDark: ColorSemanticToken { get }

    var actionSelectedLight: ColorSemanticToken { get }
    var actionSelectedDark: ColorSemanticToken { get }

    var actionSupportEnabledLight: ColorSemanticToken { get }
    var actionSupportEnabledDark: ColorSemanticToken { get }

    var actionSupportDisabledLight: ColorSemanticToken { get }
    var actionSupportDisabledDark: ColorSemanticToken { get }

    var actionSupportFocusLight: ColorSemanticToken { get }
    var actionSupportFocusDark: ColorSemanticToken { get }

    var actionSupportHoverLight: ColorSemanticToken { get }
    var actionSupportHoverDark: ColorSemanticToken { get }

    var actionSupportLoadingLight: ColorSemanticToken { get }
    var actionSupportLoadingDark: ColorSemanticToken { get }

    var actionSupportPressedLight: ColorSemanticToken { get }
    var actionSupportPressedDark: ColorSemanticToken { get }

    var actionVisitedLight: ColorSemanticToken { get }
    var actionVisitedDark: ColorSemanticToken { get }

    // MARK: - Color - Always

    var colorAlwaysBlack: ColorSemanticToken { get }
    var colorAlwaysOnBlack: ColorSemanticToken { get }
    var colorAlwaysOnWhite: ColorSemanticToken { get }
    var colorAlwaysWhite: ColorSemanticToken { get }

    // MARK: - Color - Background

    var bgInverseLowLight: ColorSemanticToken { get }
    var bgInverseLowDark: ColorSemanticToken { get }

    var bgInverseHighLight: ColorSemanticToken { get }
    var bgInverseHighDark: ColorSemanticToken { get }

    var bgPrimaryLight: ColorSemanticToken { get }
    var bgPrimaryDark: ColorSemanticToken { get }

    var bgSecondaryLight: ColorSemanticToken { get }
    var bgSecondaryDark: ColorSemanticToken { get }

    var bgTertiaryLight: ColorSemanticToken { get }
    var bgTertiaryDark: ColorSemanticToken { get }

    // MARK: - Color - Borders

    var borderBrandPrimaryLight: ColorSemanticToken { get }
    var borderBrandPrimaryDark: ColorSemanticToken { get }

    var borderDefaultLight: ColorSemanticToken { get }
    var borderDefaultDark: ColorSemanticToken { get }

    var borderEmphasizedLight: ColorSemanticToken { get }
    var borderEmphasizedDark: ColorSemanticToken { get }

    var borderFocusLight: ColorSemanticToken { get }
    var borderFocusDark: ColorSemanticToken { get }

    var borderFocusInsetLight: ColorSemanticToken { get }
    var borderFocusInsetDark: ColorSemanticToken { get }

    var borderMutedLight: ColorSemanticToken { get }
    var borderMutedDark: ColorSemanticToken { get }

    var borderOnBrandPrimaryLight: ColorSemanticToken { get }
    var borderOnBrandPrimaryDark: ColorSemanticToken { get }

    // MARK: - Color - Content

    var contentBrandPrimaryLight: ColorSemanticToken { get }
    var contentBrandPrimaryDark: ColorSemanticToken { get }

    var contentDefaultLight: ColorSemanticToken { get }
    var contentDefaultDark: ColorSemanticToken { get }

    var contentDisabledLight: ColorSemanticToken { get }
    var contentDisabledDark: ColorSemanticToken { get }

    var contentMutedLight: ColorSemanticToken { get }
    var contentMutedDark: ColorSemanticToken { get }

    var contentOnActionSelectedLight: ColorSemanticToken { get }
    var contentOnActionSelectedDark: ColorSemanticToken { get }

    var contentOnActionDisabledLight: ColorSemanticToken { get }
    var contentOnActionDisabledDark: ColorSemanticToken { get }

    var contentOnActionEnabledLight: ColorSemanticToken { get }
    var contentOnActionEnabledDark: ColorSemanticToken { get }

    var contentOnActionFocusLight: ColorSemanticToken { get }
    var contentOnActionFocusDark: ColorSemanticToken { get }

    var contentOnActionHighlightedLight: ColorSemanticToken { get }
    var contentOnActionHighlightedDark: ColorSemanticToken { get }

    var contentOnActionHoverLight: ColorSemanticToken { get }
    var contentOnActionHoverDark: ColorSemanticToken { get }

    var contentOnActionLoadingLight: ColorSemanticToken { get }
    var contentOnActionLoadingDark: ColorSemanticToken { get }

    var contentOnActionPressedLight: ColorSemanticToken { get }
    var contentOnActionPressedDark: ColorSemanticToken { get }

    var contentOnBrandPrimaryLight: ColorSemanticToken { get }
    var contentOnBrandPrimaryDark: ColorSemanticToken { get }

    var contentOnStatusPositiveMutedLight: ColorSemanticToken { get }
    var contentOnStatusPositiveMutedDark: ColorSemanticToken { get }

    var contentOnStatusPositiveEmphasizedLight: ColorSemanticToken { get }
    var contentOnStatusPositiveEmphasizedDark: ColorSemanticToken { get }

    var contentInverseLight: ColorSemanticToken { get }
    var contentInverseDark: ColorSemanticToken { get }

    var contentOnStatusNegativeMutedLight: ColorSemanticToken { get }
    var contentOnStatusNegativeMutedDark: ColorSemanticToken { get }

    var contentOnStatusNegativeEmphasizedLight: ColorSemanticToken { get }
    var contentOnStatusNegativeEmphasizedDark: ColorSemanticToken { get }

    var contentOnStatusWarningMutedLight: ColorSemanticToken { get }
    var contentOnStatusWarningMutedDark: ColorSemanticToken { get }

    var contentOnStatusWarningEmphasizedLight: ColorSemanticToken { get }
    var contentOnStatusWarningEmphasizedDark: ColorSemanticToken { get }

    var contentOnStatusAccentMutedLight: ColorSemanticToken { get }
    var contentOnStatusAccentMutedDark: ColorSemanticToken { get }

    var contentOnStatusAccentEmphasizedLight: ColorSemanticToken { get }
    var contentOnStatusAccentEmphasizedDark: ColorSemanticToken { get }

    var contentStatusInfoLight: ColorSemanticToken { get }
    var contentStatusInfoDark: ColorSemanticToken { get }

    var contentStatusNegativeLight: ColorSemanticToken { get }
    var contentStatusNegativeDark: ColorSemanticToken { get }

    var contentStatusPositiveLight: ColorSemanticToken { get }
    var contentStatusPositiveDark: ColorSemanticToken { get }

    var contentStatusWarningLight: ColorSemanticToken { get }
    var contentStatusWarningDark: ColorSemanticToken { get }

    // MARK: - Color - Overlay

    var overlayDropdownLight: ColorSemanticToken { get }
    var overlayDropdownDark: ColorSemanticToken { get }

    var overlayDragLight: ColorSemanticToken { get }
    var overlayDragDark: ColorSemanticToken { get }

    var overlayModalLight: ColorSemanticToken { get }
    var overlayModalDark: ColorSemanticToken { get }

    // MARK: - Color - Surface

    var surfaceBrandPrimaryLight: ColorSemanticToken { get }
    var surfaceBrandPrimaryDark: ColorSemanticToken { get }

    var surfaceBrandSecondaryLight: ColorSemanticToken { get }
    var surfaceBrandSecondaryDark: ColorSemanticToken { get }

    var surfaceBrandTertiaryLight: ColorSemanticToken { get }
    var surfaceBrandTertiaryDark: ColorSemanticToken { get }

    var surfaceStatusAccentEmphasizedLight: ColorSemanticToken { get }
    var surfaceStatusAccentEmphasizedDark: ColorSemanticToken { get }

    var surfaceStatusAccentMutedLight: ColorSemanticToken { get }
    var surfaceStatusAccentMutedDark: ColorSemanticToken { get }

    var surfaceStatusInfoEmphasizedLight: ColorSemanticToken { get }
    var surfaceStatusInfoEmphasizedDark: ColorSemanticToken { get }

    var surfaceStatusInfoMutedLight: ColorSemanticToken { get }
    var surfaceStatusInfoMutedDark: ColorSemanticToken { get }

    var surfaceStatusNegativeEmphasizedLight: ColorSemanticToken { get }
    var surfaceStatusNegativeEmphasizedDark: ColorSemanticToken { get }

    var surfaceStatusNegativeMutedLight: ColorSemanticToken { get }
    var surfaceStatusNegativeMutedDark: ColorSemanticToken { get }

    var surfaceInverseLowLight: ColorSemanticToken { get }
    var surfaceInverseLowDark: ColorSemanticToken { get }

    var surfaceInverseHighLight: ColorSemanticToken { get }
    var surfaceInverseHighDark: ColorSemanticToken { get }

    var surfacePrimaryLight: ColorSemanticToken { get }
    var surfacePrimaryDark: ColorSemanticToken { get }

    var surfaceSecondaryLight: ColorSemanticToken { get }
    var surfaceSecondaryDark: ColorSemanticToken { get }

    var surfaceTertiaryLight: ColorSemanticToken { get }
    var surfaceTertiaryDark: ColorSemanticToken { get }

    var surfaceStatusPositiveEmphasizedLight: ColorSemanticToken { get }
    var surfaceStatusPositiveEmphasizedDark: ColorSemanticToken { get }

    var surfaceStatusPositiveMutedLight: ColorSemanticToken { get }
    var surfaceStatusPositiveMutedDark: ColorSemanticToken { get }

    var surfaceStatusWarningEmphasizedLight: ColorSemanticToken { get }
    var surfaceStatusWarningEmphasizedDark: ColorSemanticToken { get }

    var surfaceStatusWarningMutedLight: ColorSemanticToken { get }
    var surfaceStatusWarningMutedDark: ColorSemanticToken { get }

    // MARK: - Color - Repository

    var repositoryAccentHigh: ColorSemanticToken { get }
    var repositoryAccentHigher: ColorSemanticToken { get }
    var repositoryAccentHighest: ColorSemanticToken { get }
    var repositoryAccentMedium: ColorSemanticToken { get }
    var repositoryAccentLow: ColorSemanticToken { get }
    var repositoryAccentLower: ColorSemanticToken { get }
    var repositoryAccentLowest: ColorSemanticToken { get }

    var repositoryInfoHigh: ColorSemanticToken { get }
    var repositoryInfoHigher: ColorSemanticToken { get }
    var repositoryInfoHighest: ColorSemanticToken { get }
    var repositoryInfoMedium: ColorSemanticToken { get }
    var repositoryInfoLow: ColorSemanticToken { get }
    var repositoryInfoLower: ColorSemanticToken { get }
    var repositoryInfoLowest: ColorSemanticToken { get }

    var repositoryNegativeHigh: ColorSemanticToken { get }
    var repositoryNegativeHigher: ColorSemanticToken { get }
    var repositoryNegativeHighest: ColorSemanticToken { get }
    var repositoryNegativeMedium: ColorSemanticToken { get }
    var repositoryNegativeLow: ColorSemanticToken { get }
    var repositoryNegativeLower: ColorSemanticToken { get }
    var repositoryNegativeLowest: ColorSemanticToken { get }

    var repositoryNeutralEmphasizedBlack: ColorSemanticToken { get }
    var repositoryNeutralEmphasizedHigh: ColorSemanticToken { get }
    var repositoryNeutralEmphasizedHigher: ColorSemanticToken { get }
    var repositoryNeutralEmphasizedHighest: ColorSemanticToken { get }
    var repositoryNeutralEmphasizedMedium: ColorSemanticToken { get }
    var repositoryNeutralEmphasizedLow: ColorSemanticToken { get }

    var repositoryNeutralMutedLower: ColorSemanticToken { get }
    var repositoryNeutralMutedLowest: ColorSemanticToken { get }
    var repositoryNeutralMutedWhite: ColorSemanticToken { get }

    var repositoryOpacityBlackHigh: ColorSemanticToken { get }
    var repositoryOpacityBlackHigher: ColorSemanticToken { get }
    var repositoryOpacityBlackHighest: ColorSemanticToken { get }
    var repositoryOpacityBlackLow: ColorSemanticToken { get }
    var repositoryOpacityBlackLower: ColorSemanticToken { get }
    var repositoryOpacityBlackLowest: ColorSemanticToken { get }
    var repositoryOpacityBlackMedium: ColorSemanticToken { get }
    var repositoryOpacityBlackMediumLow: ColorSemanticToken { get }
    var repositoryOpacityBlackMediumHigh: ColorSemanticToken { get }
    var repositoryOpacityBlackTransparent: ColorSemanticToken { get }

    var repositoryOpacityInfoLow: ColorSemanticToken { get }
    var repositoryOpacityInfoMedium: ColorSemanticToken { get }
    var repositoryOpacityAccentLow: ColorSemanticToken { get }
    var repositoryOpacityAccentMedium: ColorSemanticToken { get }
    var repositoryOpacityNegativeLow: ColorSemanticToken { get }
    var repositoryOpacityNegativeMedium: ColorSemanticToken { get }
    var repositoryOpacityPositiveLow: ColorSemanticToken { get }
    var repositoryOpacityPositiveMedium: ColorSemanticToken { get }
    var repositoryOpacityWarningLow: ColorSemanticToken { get }
    var repositoryOpacityWarningMedium: ColorSemanticToken { get }
    var repositoryOpacityWhiteHigh: ColorSemanticToken { get }
    var repositoryOpacityWhiteHigher: ColorSemanticToken { get }
    var repositoryOpacityWhiteHighest: ColorSemanticToken { get }
    var repositoryOpacityWhiteMedium: ColorSemanticToken { get }
    var repositoryOpacityWhiteMediumLow: ColorSemanticToken { get }
    var repositoryOpacityWhiteLow: ColorSemanticToken { get }
    var repositoryOpacityWhiteLower: ColorSemanticToken { get }
    var repositoryOpacityWhiteLowest: ColorSemanticToken { get }
    var repositoryOpacityWhiteTransparent: ColorSemanticToken { get }
    var repositoryOpacityPrimaryLow: ColorSemanticToken { get }
    var repositoryOpacityPrimaryLower: ColorSemanticToken { get }
    var repositoryOpacityPrimaryLowest: ColorSemanticToken { get }
    var repositoryOpacityPrimaryMedium: ColorSemanticToken { get }
    var repositoryOpacityPrimaryHigh: ColorSemanticToken { get }
    var repositoryOpacityPrimaryHigher: ColorSemanticToken { get }
    var repositoryOpacityPrimaryHighest: ColorSemanticToken { get }

    var repositoryPositiveMedium: ColorSemanticToken { get }
    var repositoryPositiveHigh: ColorSemanticToken { get }
    var repositoryPositiveHigher: ColorSemanticToken { get }
    var repositoryPositiveHighest: ColorSemanticToken { get }
    var repositoryPositiveLow: ColorSemanticToken { get }
    var repositoryPositiveLower: ColorSemanticToken { get }
    var repositoryPositiveLowest: ColorSemanticToken { get }

    var repositoryPrimaryHighest: ColorSemanticToken { get }
    var repositoryPrimaryHigher: ColorSemanticToken { get }
    var repositoryPrimaryHigh: ColorSemanticToken { get }
    var repositoryPrimaryMedium: ColorSemanticToken { get }
    var repositoryPrimaryLow: ColorSemanticToken { get }
    var repositoryPrimaryLower: ColorSemanticToken { get }
    var repositoryPrimaryLowest: ColorSemanticToken { get }

    var repositorySecondaryHighest: ColorSemanticToken { get }
    var repositorySecondaryHigher: ColorSemanticToken { get }
    var repositorySecondaryHigh: ColorSemanticToken { get }
    var repositorySecondaryMedium: ColorSemanticToken { get }
    var repositorySecondaryLow: ColorSemanticToken { get }
    var repositorySecondaryLower: ColorSemanticToken { get }
    var repositorySecondaryLowest: ColorSemanticToken { get }

    var repositoryTertiaryHighest: ColorSemanticToken { get }
    var repositoryTertiaryHigher: ColorSemanticToken { get }
    var repositoryTertiaryHigh: ColorSemanticToken { get }
    var repositoryTertiaryMedium: ColorSemanticToken { get }
    var repositoryTertiaryLow: ColorSemanticToken { get }
    var repositoryTertiaryLower: ColorSemanticToken { get }
    var repositoryTertiaryLowest: ColorSemanticToken { get }

    var repositoryWarningMedium: ColorSemanticToken { get }
    var repositoryWarningHigh: ColorSemanticToken { get }
    var repositoryWarningHigher: ColorSemanticToken { get }
    var repositoryWarningHighest: ColorSemanticToken { get }
    var repositoryWarningLow: ColorSemanticToken { get }
    var repositoryWarningLower: ColorSemanticToken { get }
    var repositoryWarningLowest: ColorSemanticToken { get }
}

// swiftlint:enable missing_docs
// swiftlint:enable identifier_name
