//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **dimensions**.
/// It defines all ``DimensionSemanticToken`` a theme must have.
/// Any dimension semantic token must be declared there.
///
/// These dimension semantic tokens should not be overriden by design.
/// They are considered as "closed" tokens but still defined in this library so as to keep consistancy between Figma specifications
/// and library. The tokens are not hidden from developers.
///
/// - Since: 0.16.0
public protocol DimensionSemanticTokens {

    var dimensionNone: DimensionSemanticToken { get }

    var dimensionXsmall: DimensionSemanticToken { get }
    var dimension2xsmall: DimensionSemanticToken { get }
    var dimension3xsmall: DimensionSemanticToken { get }
    var dimension4xsmall: DimensionSemanticToken { get }
    var dimension5xsmall: DimensionSemanticToken { get }
    var dimension6xsmall: DimensionSemanticToken { get }
    var dimension7xsmall: DimensionSemanticToken { get }
    var dimension8xsmall: DimensionSemanticToken { get }
    var dimension9xsmall: DimensionSemanticToken { get }
    var dimension10xsmall: DimensionSemanticToken { get }
    var dimension11xsmall: DimensionSemanticToken { get }
    var dimension12xsmall: DimensionSemanticToken { get }

    var dimensionSmall: DimensionSemanticToken { get }

    var dimensionMedium: DimensionSemanticToken { get }

    var dimensionLarge: DimensionSemanticToken { get }

    var dimensionXlarge: DimensionSemanticToken { get }
    var dimension2xlarge: DimensionSemanticToken { get }
    var dimension3xlarge: DimensionSemanticToken { get }
    var dimension4xlarge: DimensionSemanticToken { get }
    var dimension5xlarge: DimensionSemanticToken { get }
    var dimension6xlarge: DimensionSemanticToken { get }
    var dimension7xlarge: DimensionSemanticToken { get }
    var dimension8xlarge: DimensionSemanticToken { get }
    var dimension9xlarge: DimensionSemanticToken { get }
    var dimension10xlarge: DimensionSemanticToken { get }
    var dimension11xlarge: DimensionSemanticToken { get }
}

// swiftlint:enable missing_docs
