//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **elevations**.
/// It defines all elevation semantic tokens a theme must have (``ElevationXSemanticToken``, ``ElevationYSemanticToken``,
/// ``ElevationBlurSemanticToken`` and ``ElevationColorSemanticToken``).
/// However the composite tokens (here for box shadows) are defined in ``ElevationCompositeSemanticTokens`` because the *tokenator*
/// is not able to generate them yet, and they must be defined elsewhere to not be deleted.
/// Any elevation semantic token must be declared there (except ``ElevationCompositeSemanticTokens``)
///
/// - Since: 0.8.0
public protocol ElevationSemanticTokens {

    // MARK: Semantic token - Elevation - X

    var elevationXNone: ElevationXSemanticToken { get }
    var elevationXRaised: ElevationXSemanticToken { get }
    var elevationXDefault: ElevationXSemanticToken { get }
    var elevationXEmphasized: ElevationXSemanticToken { get }
    var elevationXDrag: ElevationXSemanticToken { get }
    var elevationXSticky: ElevationXSemanticToken { get }

    // MARK: Semantic token - Elevation - Y

    var elevationYNone: ElevationYSemanticToken { get }
    var elevationYRaised: ElevationYSemanticToken { get }
    var elevationYDefault: ElevationYSemanticToken { get }
    var elevationYEmphasized: ElevationYSemanticToken { get }
    var elevationYDrag: ElevationYSemanticToken { get }
    var elevationYSticky: ElevationYSemanticToken { get }

    // MARK: Semantic token - Elevation - Blur

    var elevationBlurNone: ElevationBlurSemanticToken { get }
    var elevationBlurRaised: ElevationBlurSemanticToken { get }
    var elevationBlurDefault: ElevationBlurSemanticToken { get }
    var elevationBlurEmphasized: ElevationBlurSemanticToken { get }
    var elevationBlurDrag: ElevationBlurSemanticToken { get }
    var elevationBlurSticky: ElevationBlurSemanticToken { get }

    // MARK: Semantic token - Elevation - Color

    var elevationColorNone: ElevationColorSemanticToken { get }
    var elevationColorDefaultLight: ElevationColorSemanticToken { get }
    var elevationColorDefaultDark: ElevationColorSemanticToken { get }
    var elevationColorRaisedLight: ElevationColorSemanticToken { get }
    var elevationColorRaisedDark: ElevationColorSemanticToken { get }
    var elevationColorDragLight: ElevationColorSemanticToken { get }
    var elevationColorDragDark: ElevationColorSemanticToken { get }
    var elevationColorEmphasizedLight: ElevationColorSemanticToken { get }
    var elevationColorEmphasizedDark: ElevationColorSemanticToken { get }
    var elevationColorStickyLight: ElevationColorSemanticToken { get }
    var elevationColorStickyDark: ElevationColorSemanticToken { get }
}

// swiftlint:enable missing_docs
