//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **fonts**, but only **composite tokens** in the end.
/// There are splitted and not declared in ``FontSemanticTokens`` as the *tokenator* tool parsing *Figma* JSON to Swift code is not able to manage them.
/// Thus we need to declare them in another file to prevent them to be erased.
///
/// It defines all composite font semantic tokens a theme must have, i.e. tokens including properties for font family, font weight, font size or line height for example.
///
/// This protocol makes themes able to provide and override `FontCompositeSemanticToken` gathered in ``MultipleFontCompositeSemanticToken`` instances.
/// This `FontCompositeSemanticToken` is not managed by tokenator yet as it is composed by several properties.
///
/// This ``FontCompositeSemanticTokens`` protocol contains a set of ``MultipleFontCompositeSemanticToken``.
/// They can be applied to views and components using the helpers provided through `View`, loading four the the font famoly to use:
///
/// ```swift
///      @Environment(\.theme) var theme
///
///      // Apply theme.fonts.displayLarge
///      Text("Foo bar wizz").displayLarge(theme)
///
///      // Apply theme.fonts.headingMedium
///      Text("Foo bar wizz").headingMedium(theme)
///
///      // Apply theme.fonts.bodyDefaultSmall
///      Text("Foo bar wizz").bodyDefaultSmall(theme)
///
///      // Etc.
/// ```
///
/// - Since: 0.8.0
public protocol FontCompositeSemanticTokens {

    // MARK: - Semantic tokens - Typography - Composites - Display

    var displayLarge: MultipleFontCompositeSemanticToken { get }
    var displayMedium: MultipleFontCompositeSemanticToken { get }
    var displaySmall: MultipleFontCompositeSemanticToken { get }

    // MARK: - Semantic tokens - Typography - Composites - Heading

    var headingXLarge: MultipleFontCompositeSemanticToken { get }
    var headingLarge: MultipleFontCompositeSemanticToken { get }
    var headingMedium: MultipleFontCompositeSemanticToken { get }
    var headingSmall: MultipleFontCompositeSemanticToken { get }

    // MARK: - Semantic tokens - Typography - Composites - Body

    var bodyDefaultLarge: MultipleFontCompositeSemanticToken { get }
    var bodyDefaultMedium: MultipleFontCompositeSemanticToken { get }
    var bodyDefaultSmall: MultipleFontCompositeSemanticToken { get }
    var bodyModerateLarge: MultipleFontCompositeSemanticToken { get }
    var bodyModerateSmall: MultipleFontCompositeSemanticToken { get }
    var bodyModerateMedium: MultipleFontCompositeSemanticToken { get }
    var bodyStrongLarge: MultipleFontCompositeSemanticToken { get }
    var bodyStrongMedium: MultipleFontCompositeSemanticToken { get }
    var bodyStrongSmall: MultipleFontCompositeSemanticToken { get }

    // MARK: - Semantic tokens - Typography - Composites - Label

    var labelDefaultXLarge: MultipleFontCompositeSemanticToken { get }
    var labelDefaultLarge: MultipleFontCompositeSemanticToken { get }
    var labelDefaultMedium: MultipleFontCompositeSemanticToken { get }
    var labelDefaultSmall: MultipleFontCompositeSemanticToken { get }
    var labelModerateXLarge: MultipleFontCompositeSemanticToken { get }
    var labelModerateLarge: MultipleFontCompositeSemanticToken { get }
    var labelModerateMedium: MultipleFontCompositeSemanticToken { get }
    var labelModerateSmall: MultipleFontCompositeSemanticToken { get }
    var labelStrongXLarge: MultipleFontCompositeSemanticToken { get }
    var labelStrongLarge: MultipleFontCompositeSemanticToken { get }
    var labelStrongMedium: MultipleFontCompositeSemanticToken { get }
    var labelStrongSmall: MultipleFontCompositeSemanticToken { get }

    // MARK: - Semantic tokens - Typography - Composites - Code

    var codeMedium: MultipleFontCompositeSemanticToken { get }
}

// swiftlint:enable missing_docs
