//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **fonts**, but only **composite tokens** in the end.
/// There are splitted and not declared in ``FontSemanticTokens`` as the *tokenator* tool parsing *Figma* JSON to Swift code is not able to manage them.
/// Thus we need to declare them in another file to prevent them to be erased.
///
/// It defines all composite font semantic tokens a theme must have, i.e. tokens including properties for font family, font weight, font size or line height for example.
///
/// This protocol makes themes able to provide and override `FontCompositeRawToken` gathered in ``MultipleFontCompositeSemanticTokens`` instances.
/// This `FontCompositeRawToken` is not managed by tokenator yet as it is composed by several properties.
///
/// This ``FontCompositeSemanticTokens`` protocol contains a set of ``MultipleFontCompositeSemanticTokens``.
/// They can be applied to views and components using the helpers provided through `View`, loading four the the font famoly to use:
///
/// ```swift
///      @Environment(\.theme) var theme
///
///      // Apply theme.fonts.displayLarge
///      Text("Foo bar wizz").displayLarge(theme)
///
///      // Apply theme.fonts.headingMedium
///      Text("Foo bar wizz").headingMedium(theme)
///
///      // Apply theme.fonts.bodyDefaultSmall
///      Text("Foo bar wizz").bodyDefaultSmall(theme)
///
///      // Etc.
/// ```
///
/// - Since: 0.8.0
public protocol FontCompositeSemanticTokens {

    // MARK: - Semantic tokens - Typography - Composites - Display

    var displayLarge: MultipleFontCompositeSemanticTokens { get }
    var displayMedium: MultipleFontCompositeSemanticTokens { get }
    var displaySmall: MultipleFontCompositeSemanticTokens { get }

    // MARK: - Semantic tokens - Typography - Composites - Heading

    var headingXLarge: MultipleFontCompositeSemanticTokens { get }
    var headingLarge: MultipleFontCompositeSemanticTokens { get }
    var headingMedium: MultipleFontCompositeSemanticTokens { get }
    var headingSmall: MultipleFontCompositeSemanticTokens { get }

    // MARK: - Semantic tokens - Typography - Composites - Body

    var bodyDefaultLarge: MultipleFontCompositeSemanticTokens { get }
    var bodyDefaultMedium: MultipleFontCompositeSemanticTokens { get }
    var bodyDefaultSmall: MultipleFontCompositeSemanticTokens { get }
    var bodyModerateLarge: MultipleFontCompositeSemanticTokens { get }
    var bodyModerateSmall: MultipleFontCompositeSemanticTokens { get }
    var bodyModerateMedium: MultipleFontCompositeSemanticTokens { get }
    var bodyStrongLarge: MultipleFontCompositeSemanticTokens { get }
    var bodyStrongMedium: MultipleFontCompositeSemanticTokens { get }
    var bodyStrongSmall: MultipleFontCompositeSemanticTokens { get }

    // MARK: - Semantic tokens - Typography - Composites - Label

    var labelDefaultXLarge: MultipleFontCompositeSemanticTokens { get }
    var labelDefaultLarge: MultipleFontCompositeSemanticTokens { get }
    var labelDefaultMedium: MultipleFontCompositeSemanticTokens { get }
    var labelDefaultSmall: MultipleFontCompositeSemanticTokens { get }
    var labelModerateXLarge: MultipleFontCompositeSemanticTokens { get }
    var labelModerateLarge: MultipleFontCompositeSemanticTokens { get }
    var labelModerateMedium: MultipleFontCompositeSemanticTokens { get }
    var labelModerateSmall: MultipleFontCompositeSemanticTokens { get }
    var labelStrongXLarge: MultipleFontCompositeSemanticTokens { get }
    var labelStrongLarge: MultipleFontCompositeSemanticTokens { get }
    var labelStrongMedium: MultipleFontCompositeSemanticTokens { get }
    var labelStrongSmall: MultipleFontCompositeSemanticTokens { get }

    // MARK: - Semantic tokens - Typography - Composites - Code

    var codeMedium: MultipleFontCompositeSemanticTokens { get }
}

// swiftlint:enable missing_docs
