//
// Software Name: OUDSThemesContract iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **font**.
/// It defines all font semantic tokens a theme must have
/// (``FontFamilySemanticToken``, ``FontWeightSemanticToken``, ``FontSizeSemanticToken``, ``FontLineHeightSemanticToken``).
/// However the composite tokens (here the ones gathering each type of semantic token here) are defined in ``FontCompositeSemanticTokens`` because the *tokenator*
/// is not able to generate them yet, and they must be defined elsewhere to not be deleted.
/// Any font semantic token must be declared there (except ``FontCompositeSemanticTokens``).
///
/// - Since: 0.8.0
public protocol FontSemanticTokens {

    // MARK: - Semantic token - Typography - Font - Family

    var familySystem: FontFamilySemanticToken { get }
    var familyCode: FontFamilySemanticToken { get }
    var familyBody: FontFamilySemanticToken { get }
    var familyDisplay: FontFamilySemanticToken { get }
    var familyHeading: FontFamilySemanticToken { get }
    var familyLabel: FontFamilySemanticToken { get }

    // MARK: - Semantic token - Typography - Font - Weight

    var weightCode: FontWeightSemanticToken { get }
    var weightBodyDefault: FontWeightSemanticToken { get }
    var weightBodyModerate: FontWeightSemanticToken { get }
    var weightBodyStrong: FontWeightSemanticToken { get }
    var weightDisplay: FontWeightSemanticToken { get }
    var weightHeading: FontWeightSemanticToken { get }
    var weightLabelDefault: FontWeightSemanticToken { get }
    var weightLabelModerate: FontWeightSemanticToken { get }
    var weightLabelStrong: FontWeightSemanticToken { get }
    var weightSystemDefault: FontWeightSemanticToken { get }
    var weightSystemStrong: FontWeightSemanticToken { get }

    // MARK: - Semantic token - Typography - Font - Size

    var sizeDisplayLargeMobile: FontSizeSemanticToken { get }
    var sizeDisplayLargeTablet: FontSizeSemanticToken { get }
    var sizeDisplayMediumMobile: FontSizeSemanticToken { get }
    var sizeDisplayMediumTablet: FontSizeSemanticToken { get }
    var sizeDisplaySmallMobile: FontSizeSemanticToken { get }
    var sizeDisplaySmallTablet: FontSizeSemanticToken { get }
    var sizeHeadingXlargeMobile: FontSizeSemanticToken { get }
    var sizeHeadingXlargeTablet: FontSizeSemanticToken { get }
    var sizeHeadingLargeMobile: FontSizeSemanticToken { get }
    var sizeHeadingLargeTablet: FontSizeSemanticToken { get }
    var sizeHeadingMediumMobile: FontSizeSemanticToken { get }
    var sizeHeadingMediumTablet: FontSizeSemanticToken { get }
    var sizeHeadingSmallMobile: FontSizeSemanticToken { get }
    var sizeHeadingSmallTablet: FontSizeSemanticToken { get }
    var sizeBodyLargeMobile: FontSizeSemanticToken { get }
    var sizeBodyLargeTablet: FontSizeSemanticToken { get }
    var sizeBodyMediumMobile: FontSizeSemanticToken { get }
    var sizeBodyMediumTablet: FontSizeSemanticToken { get }
    var sizeBodySmallMobile: FontSizeSemanticToken { get }
    var sizeBodySmallTablet: FontSizeSemanticToken { get }
    var sizeLabelXlarge: FontSizeSemanticToken { get }
    var sizeLabelLarge: FontSizeSemanticToken { get }
    var sizeLabelMedium: FontSizeSemanticToken { get }
    var sizeLabelSmall: FontSizeSemanticToken { get }
    var sizeCodeMedium: FontSizeSemanticToken { get }

    // MARK: - Semantic token - Typography - Font - Line height

    var lineHeightDisplayLargeMobile: FontLineHeightSemanticToken { get }
    var lineHeightDisplayLargeTablet: FontLineHeightSemanticToken { get }
    var lineHeightDisplayMediumMobile: FontLineHeightSemanticToken { get }
    var lineHeightDisplayMediumTablet: FontLineHeightSemanticToken { get }
    var lineHeightDisplaySmallMobile: FontLineHeightSemanticToken { get }
    var lineHeightDisplaySmallTablet: FontLineHeightSemanticToken { get }
    var lineHeightHeadingXlargeMobile: FontLineHeightSemanticToken { get }
    var lineHeightHeadingXlargeTablet: FontLineHeightSemanticToken { get }
    var lineHeightHeadingLargeMobile: FontLineHeightSemanticToken { get }
    var lineHeightHeadingLargeTablet: FontLineHeightSemanticToken { get }
    var lineHeightHeadingMediumMobile: FontLineHeightSemanticToken { get }
    var lineHeightHeadingMediumTablet: FontLineHeightSemanticToken { get }
    var lineHeightHeadingSmallMobile: FontLineHeightSemanticToken { get }
    var lineHeightHeadingSmallTablet: FontLineHeightSemanticToken { get }
    var lineHeightBodyLargeMobile: FontLineHeightSemanticToken { get }
    var lineHeightBodyLargeTablet: FontLineHeightSemanticToken { get }
    var lineHeightBodyMediumMobile: FontLineHeightSemanticToken { get }
    var lineHeightBodyMediumTablet: FontLineHeightSemanticToken { get }
    var lineHeightBodySmallMobile: FontLineHeightSemanticToken { get }
    var lineHeightBodySmallTablet: FontLineHeightSemanticToken { get }
    var lineHeightLabelXlarge: FontLineHeightSemanticToken { get }
    var lineHeightLabelLarge: FontLineHeightSemanticToken { get }
    var lineHeightLabelMedium: FontLineHeightSemanticToken { get }
    var lineHeightLabelSmall: FontLineHeightSemanticToken { get }
    var lineHeightCodeMedium: FontLineHeightSemanticToken { get }

    // MARK: - Semantic token - Typography - Font - Letter spacing

    var letterSpacingDisplayLargeMobile: FontLetterSpacingSemanticToken { get }
    var letterSpacingDisplayLargeTablet: FontLetterSpacingSemanticToken { get }
    var letterSpacingDisplayMediumMobile: FontLetterSpacingSemanticToken { get }
    var letterSpacingDisplayMediumTablet: FontLetterSpacingSemanticToken { get }
    var letterSpacingDisplaySmallMobile: FontLetterSpacingSemanticToken { get }
    var letterSpacingDisplaySmallTablet: FontLetterSpacingSemanticToken { get }
    var letterSpacingHeadingXlargeMobile: FontLetterSpacingSemanticToken { get }
    var letterSpacingHeadingXlargeTablet: FontLetterSpacingSemanticToken { get }
    var letterSpacingHeadingLargeMobile: FontLetterSpacingSemanticToken { get }
    var letterSpacingHeadingLargeTablet: FontLetterSpacingSemanticToken { get }
    var letterSpacingHeadingMediumMobile: FontLetterSpacingSemanticToken { get }
    var letterSpacingHeadingMediumTablet: FontLetterSpacingSemanticToken { get }
    var letterSpacingHeadingSmallMobile: FontLetterSpacingSemanticToken { get }
    var letterSpacingHeadingSmallTablet: FontLetterSpacingSemanticToken { get }
    var letterSpacingBodyLargeMobile: FontLetterSpacingSemanticToken { get }
    var letterSpacingBodyLargeTablet: FontLetterSpacingSemanticToken { get }
    var letterSpacingBodyMediumMobile: FontLetterSpacingSemanticToken { get }
    var letterSpacingBodyMediumTablet: FontLetterSpacingSemanticToken { get }
    var letterSpacingBodySmallMobile: FontLetterSpacingSemanticToken { get }
    var letterSpacingBodySmallTablet: FontLetterSpacingSemanticToken { get }
    var letterSpacingLabelXlarge: FontLetterSpacingSemanticToken { get }
    var letterSpacingLabelLarge: FontLetterSpacingSemanticToken { get }
    var letterSpacingLabelMedium: FontLetterSpacingSemanticToken { get }
    var letterSpacingLabelSmall: FontLetterSpacingSemanticToken { get }
    var letterSpacingCodeMedium: FontLetterSpacingSemanticToken { get }
}

// swiftlint:enable missing_docs
