//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs
// swiftlint:disable line_length

/// This is a group of semantic tokens for **fonts** but using ``MultipleFontLetterSpacingSemanticToken`` for *letter spacings*,
/// ``MultipleFontLineHeightSemanticToken`` for *line heights* and ``MultipleFontSizeSemanticToken`` for *font sizes*.
///
/// In fact these ``MultipleFontLetterSpacingSemanticToken``, ``MultipleFontLineHeightSemanticToken`` and  ``MultipleFontSizeSemanticToken`` classes will help users
/// (i.e. developers) to handle one semantic token for font things depending to size class (wether it could be compact / mobile or regular / tablet).
/// Because *Figma* is not able to manage pair of values for one token, and its produced JSON does not reflect this mecanism, the *tokenator* cannot provide
/// such ``MultipleFontLetterSpacingSemanticToken``, ``MultipleFontLineHeightSemanticToken`` and ``MultipleFontSizeSemanticToken`` tokens.
/// Thus the "real" letter spacing, line height and font size tokens are declared in ``FontSemanticTokens`` protocol and defined inside `OUDSTheme` (to be overridable then by subthemes).
/// These tokens are updated by the *tokenator*.
/// Then they are gathered and wrapped so as to be used easily thanks to this ``FontMultipleSemanticTokens`` which must be updated manually.
///
/// However the composite tokens (here the ones gathering each type of semantic token here) are defined in ``FontCompositeSemanticTokens`` because the *tokenator*
/// is not able to generate them yet, and they must be defined elsewhere to not be deleted.
///
/// In few words:
/// ```swift
///         // Some font size raw tokens, defined by the tokenator (in FontRawTokens+Values.swift)
///         public static let size850: FontSizeRawToken = 40
///         public static let size1450: FontSizeRawToken = 64
///
///         // The font size semantic tokens using them
///         // declared (in FontMultipleSemanticTokens.swift) and defined (in OUDSTheme+FontSemanticTokens.swift) by the tokenator
///         var sizeDisplayLargeMobile: FontSizeSemanticToken { FontRawTokens.size850 }
///         var sizeDisplayLargeTablet: FontSizeSemanticToken { FontRawTokens.size1450 }
///
///         // The 'higher level' font semantic tokens wrapping them and exposed to users
///         // declared (in this FontMultipleSemanticTokens.swift) and defined manualy (in OUDSTheme+FontMultipleSemanticTokens.swift)
///         var sizeDisplayLarge: MultipleFontSizeSemanticToken { MultipleFontSizeSemanticToken(compact: sizeDisplayLargeMobile, regular: sizeDisplayLargeTablet) }
///
///         // Thus users can in their components use colorNone as defined in their design system
///         // (even if they are still able to use 'lower level' semantic tokens but it is more error-prone)
/// ```
///
/// - Since: 0.8.0
public protocol FontMultipleSemanticTokens {

    // MARK: - Semantic token - Typography - Font - Size

    var sizeDisplayLarge: MultipleFontSizeSemanticToken { get }
    var sizeDisplayMedium: MultipleFontSizeSemanticToken { get }
    var sizeDisplaySmall: MultipleFontSizeSemanticToken { get }
    var sizeHeadingXlarge: MultipleFontSizeSemanticToken { get }
    var sizeHeadingLarge: MultipleFontSizeSemanticToken { get }
    var sizeHeadingMedium: MultipleFontSizeSemanticToken { get }
    var sizeHeadingSmall: MultipleFontSizeSemanticToken { get }
    var sizeBodyLarge: MultipleFontSizeSemanticToken { get }
    var sizeBodyMedium: MultipleFontSizeSemanticToken { get }
    var sizeBodySmall: MultipleFontSizeSemanticToken { get }

    // MARK: - Semantic token - Typography - Font - Line height

    var lineHeightDisplayLarge: MultipleFontLineHeightSemanticToken { get }
    var lineHeightDisplayMedium: MultipleFontLineHeightSemanticToken { get }
    var lineHeightDisplaySmall: MultipleFontLineHeightSemanticToken { get }
    var lineHeightHeadingXlarge: MultipleFontLineHeightSemanticToken { get }
    var lineHeightHeadingLarge: MultipleFontLineHeightSemanticToken { get }
    var lineHeightHeadingMedium: MultipleFontLineHeightSemanticToken { get }
    var lineHeightHeadingSmall: MultipleFontLineHeightSemanticToken { get }
    var lineHeightBodyLarge: MultipleFontLineHeightSemanticToken { get }
    var lineHeightBodyMedium: MultipleFontLineHeightSemanticToken { get }
    var lineHeightBodySmall: MultipleFontLineHeightSemanticToken { get }

    // MARK: - Semantic token - Typography - Font - Letter spacing

    var letterSpacingDisplayLarge: MultipleFontLetterSpacingSemanticToken { get }
    var letterSpacingDisplayMedium: MultipleFontLetterSpacingSemanticToken { get }
    var letterSpacingDisplaySmall: MultipleFontLetterSpacingSemanticToken { get }
    var letterSpacingHeadingXlarge: MultipleFontLetterSpacingSemanticToken { get }
    var letterSpacingHeadingLarge: MultipleFontLetterSpacingSemanticToken { get }
    var letterSpacingHeadingMedium: MultipleFontLetterSpacingSemanticToken { get }
    var letterSpacingHeadingSmall: MultipleFontLetterSpacingSemanticToken { get }
    var letterSpacingBodyLarge: MultipleFontLetterSpacingSemanticToken { get }
    var letterSpacingBodyMedium: MultipleFontLetterSpacingSemanticToken { get }
    var letterSpacingBodySmall: MultipleFontLetterSpacingSemanticToken { get }
}

// swiftlint:enable missing_docs
// swiftlint:enable line_length
