//
// Software Name: OUDSThemesContract iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **grids**.
/// It defines all `GridSemanticToken` a theme must have.
/// Any grid semantic token must be declared there.
///
/// - Since: 0.8.0
public protocol GridSemanticTokens {

    // MARK: Semantic token - Grid - iOS Extra compact

    var extraCompactMinWidth: GridSemanticToken { get }
    var extraCompactMaxWidth: GridSemanticToken { get }
    var extraCompactMargin: GridSemanticToken { get }
    var extraCompactColumnGap: GridSemanticToken { get }

    // MARK: Semantic token - Grid - iOS Compact

    var compactMinWidth: GridSemanticToken { get }
    var compactMaxWidth: GridSemanticToken { get }
    var compactMargin: GridSemanticToken { get }
    var compactColumnGap: GridSemanticToken { get }

    // MARK: Semantic token - Grid - iOS Regular

    var regularMinWidth: GridSemanticToken { get }
    var regularMaxWidth: GridSemanticToken { get }
    var regularMargin: GridSemanticToken { get }
    var regularColumnGap: GridSemanticToken { get }
}

// swiftlint:enable missing_docs
