//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **opacity.**
/// It defines all ``OpacitySemanticToken`` a theme must have.
/// Any opacity semantic token must be declared there as providers like `OrangeThemeOpacitySemanticTokensProvider` will then expose them through `OUDSTheme`.
///
/// - Since: 0.8.0
public protocol OpacitySemanticTokens {

    var invisible: OpacitySemanticToken { get }
    var weakest: OpacitySemanticToken { get }
    var weaker: OpacitySemanticToken { get }
    var weak: OpacitySemanticToken { get }
    var medium: OpacitySemanticToken { get }
    var strong: OpacitySemanticToken { get }
    var opaque: OpacitySemanticToken { get }
    var disabled: OpacitySemanticToken { get }
}

// swiftlint:enable missing_docs
