//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
// 
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
// 
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System 
//

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs
// swiftlint:disable line_length

/// This is a group of semantic tokens for **size** but using ``MultipleSizeSemanticTokens``
///
/// In fact the ``MultipleSizeSemanticTokens`` class will help users (i.e. developers) to handle one semantic token for size containing values for compact and regular viewports / size classes.
/// Because *Figma* is not able to manage pair of values for one token, and its produced JSON does not reflect this mecanism, the *tokenator* cannot provide such ``MultipleSizeSemanticTokens``.
/// A major part the "real" size semantic tokens are declared in ``SizeSemanticTokens`` protocol and defined inside `OUDSTheme` (to be overridable then by subthemes), and othershere.
/// These tokens are updated by the *tokenator*.
/// Then they are gathered and wrapped so as to be used easily thanks to this ``MultipleSizeSemanticTokens`` which must be updated manually.
///
/// In few words:
/// ```swift
///         // Some sizing raw tokens, defined by the tokenator (in DimensionRawTokens+Values.swift)
///         public static let dimension550: DimensionRawToken = 44
///         public static let dimension650: DimensionRawToken = 52
///
///         // The sizing semantic tokens using them,
///         // declared (in SizeSemanticTokens.swift) and defined (in OUDSTheme+SizeSemanticTokens.swift) by the tokenator
///         var sizeIconWithHeadingXLargeShortMobile: SizeSemanticToken { DimensionRawTokens.dimension550 }
///         var sizeIconWithHeadingXLargeShortTablet: SizeSemanticToken { DimensionRawTokens.dimension650 }
///
///         // The 'higher level' size semantic tokens wrapping them and exposed to users,
///         // declared (in SizeMultipleSemanticTokens.swift) and defined (in OUDSTheme+SizeMultipleSemanticTokens.swift) manualy
///         var sizeIconWithHeadingXLargeShort: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithHeadingXLargeShortMobile, regular: sizeIconWithHeadingXLargeShortTablet) }
///
///         // Thus users can in their components use sizeIconWithHeadingXLargeShort as defined in their design system
///         // (even if they are still able to use 'lower level' semantic tokens but it is more error-prone)
/// ```
/// 
public protocol SizeMultipleSemanticTokens {

    // MARK: - Semantic token - Sizing - Icon with typography

    var sizeIconWithHeadingXLargeShort: MultipleSizeSemanticTokens { get }
    var sizeIconWithHeadingXLargeMedium: MultipleSizeSemanticTokens { get }
    var sizeIconWithHeadingXLargeTall: MultipleSizeSemanticTokens { get }

    var sizeIconWithHeadingLargeShort: MultipleSizeSemanticTokens { get }
    var sizeIconWithHeadingLargeMedium: MultipleSizeSemanticTokens { get }
    var sizeIconWithHeadingLargeTall: MultipleSizeSemanticTokens { get }

    var sizeIconWithHeadingMediumShort: MultipleSizeSemanticTokens { get }
    var sizeIconWithHeadingMediumMedium: MultipleSizeSemanticTokens { get }
    var sizeIconWithHeadingMediumTall: MultipleSizeSemanticTokens { get }

    var sizeIconWithHeadingSmallShort: MultipleSizeSemanticTokens { get }
    var sizeIconWithHeadingSmallMedium: MultipleSizeSemanticTokens { get }
    var sizeIconWithHeadingSmallTall: MultipleSizeSemanticTokens { get }

    var sizeIconWithBodyLargeShort: MultipleSizeSemanticTokens { get }
    var sizeIconWithBodyLargeMedium: MultipleSizeSemanticTokens { get }
    var sizeIconWithBodyLargeTall: MultipleSizeSemanticTokens { get }

    var sizeIconWithBodyMediumShort: MultipleSizeSemanticTokens { get }
    var sizeIconWithBodyMediumMedium: MultipleSizeSemanticTokens { get }
    var sizeIconWithBodyMediumTall: MultipleSizeSemanticTokens { get }

    var sizeIconWithBodySmallShort: MultipleSizeSemanticTokens { get }
    var sizeIconWithBodySmallMedium: MultipleSizeSemanticTokens { get }
    var sizeIconWithBodySmallTall: MultipleSizeSemanticTokens { get }

    // MARK: - Semantic token - Sizing - Max width typography

    var sizeMaxWidthTypeDisplayLarge: MultipleSizeSemanticTokens { get }
    var sizeMaxWidthTypeDisplayMedium: MultipleSizeSemanticTokens { get }
    var sizeMaxWidthTypeDisplaySmall: MultipleSizeSemanticTokens { get }

    var sizeMaxWidthTypeHeadingXLarge: MultipleSizeSemanticTokens { get }
    var sizeMaxWidthTypeHeadingLarge: MultipleSizeSemanticTokens { get }
    var sizeMaxWidthTypeHeadingMedium: MultipleSizeSemanticTokens { get }
    var sizeMaxWidthTypeHeadingSmall: MultipleSizeSemanticTokens { get }

    var sizeMaxWidthTypeBodyLarge: MultipleSizeSemanticTokens { get }
    var sizeMaxWidthTypeBodyMedium: MultipleSizeSemanticTokens { get }
    var sizeMaxWidthTypeBodySmall: MultipleSizeSemanticTokens { get }
}

// swiftlint:enable missing_docs
// swiftlint:enable line_length
