//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs
// swiftlint:disable identifier_name

/// This is a group of semantic tokens for **sizing**.
/// It defines all ``SizeSemanticToken`` a theme must have.
/// Any size semantic token must be declared there.
///
/// - Since: 0.8.0
public protocol SizeSemanticTokens {

    // MARK: - Semantic token - Sizing - Icon with typography

    var sizeIconWithHeadingXlargeSizeSmallMobile: SizeSemanticToken { get }
    var sizeIconWithHeadingXlargeSizeSmallTablet: SizeSemanticToken { get }
    var sizeIconWithHeadingXlargeSizeMediumMobile: SizeSemanticToken { get }
    var sizeIconWithHeadingXlargeSizeMediumTablet: SizeSemanticToken { get }
    var sizeIconWithHeadingXlargeSizeLargeMobile: SizeSemanticToken { get }
    var sizeIconWithHeadingXlargeSizeLargeTablet: SizeSemanticToken { get }

    var sizeIconWithHeadingLargeSizeSmallMobile: SizeSemanticToken { get }
    var sizeIconWithHeadingLargeSizeSmallTablet: SizeSemanticToken { get }
    var sizeIconWithHeadingLargeSizeMediumMobile: SizeSemanticToken { get }
    var sizeIconWithHeadingLargeSizeMediumTablet: SizeSemanticToken { get }
    var sizeIconWithHeadingLargeSizeLargeMobile: SizeSemanticToken { get }
    var sizeIconWithHeadingLargeSizeLargeTablet: SizeSemanticToken { get }

    var sizeIconWithHeadingMediumSizeSmallMobile: SizeSemanticToken { get }
    var sizeIconWithHeadingMediumSizeSmallTablet: SizeSemanticToken { get }
    var sizeIconWithHeadingMediumSizeMediumMobile: SizeSemanticToken { get }
    var sizeIconWithHeadingMediumSizeMediumTablet: SizeSemanticToken { get }
    var sizeIconWithHeadingMediumSizeLargeMobile: SizeSemanticToken { get }
    var sizeIconWithHeadingMediumSizeLargeTablet: SizeSemanticToken { get }

    var sizeIconWithHeadingSmallSizeSmallMobile: SizeSemanticToken { get }
    var sizeIconWithHeadingSmallSizeSmallTablet: SizeSemanticToken { get }
    var sizeIconWithHeadingSmallSizeMediumMobile: SizeSemanticToken { get }
    var sizeIconWithHeadingSmallSizeMediumTablet: SizeSemanticToken { get }
    var sizeIconWithHeadingSmallSizeLargeMobile: SizeSemanticToken { get }
    var sizeIconWithHeadingSmallSizeLargeTablet: SizeSemanticToken { get }

    var sizeIconWithBodyLargeSizeSmallMobile: SizeSemanticToken { get }
    var sizeIconWithBodyLargeSizeSmallTablet: SizeSemanticToken { get }
    var sizeIconWithBodyLargeSizeMediumMobile: SizeSemanticToken { get }
    var sizeIconWithBodyLargeSizeMediumTablet: SizeSemanticToken { get }
    var sizeIconWithBodyLargeSizeLargeMobile: SizeSemanticToken { get }
    var sizeIconWithBodyLargeSizeLargeTablet: SizeSemanticToken { get }

    var sizeIconWithBodyMediumSizeSmallMobile: SizeSemanticToken { get }
    var sizeIconWithBodyMediumSizeSmallTablet: SizeSemanticToken { get }
    var sizeIconWithBodyMediumSizeMediumMobile: SizeSemanticToken { get }
    var sizeIconWithBodyMediumSizeMediumTablet: SizeSemanticToken { get }
    var sizeIconWithBodyMediumSizeLargeMobile: SizeSemanticToken { get }
    var sizeIconWithBodyMediumSizeLargeTablet: SizeSemanticToken { get }

    var sizeIconWithBodySmallSizeSmallMobile: SizeSemanticToken { get }
    var sizeIconWithBodySmallSizeSmallTablet: SizeSemanticToken { get }
    var sizeIconWithBodySmallSizeMediumMobile: SizeSemanticToken { get }
    var sizeIconWithBodySmallSizeMediumTablet: SizeSemanticToken { get }
    var sizeIconWithBodySmallSizeLargeMobile: SizeSemanticToken { get }
    var sizeIconWithBodySmallSizeLargeTablet: SizeSemanticToken { get }

    // MARK: - Semantic token - Sizing - Max width typography

    var sizeMaxWidthTypeDisplayLargeMobile: SizeSemanticToken { get }
    var sizeMaxWidthTypeDisplayLargeTablet: SizeSemanticToken { get }
    var sizeMaxWidthTypeDisplayMediumMobile: SizeSemanticToken { get }
    var sizeMaxWidthTypeDisplayMediumTablet: SizeSemanticToken { get }
    var sizeMaxWidthTypeDisplaySmallMobile: SizeSemanticToken { get }
    var sizeMaxWidthTypeDisplaySmallTablet: SizeSemanticToken { get }

    var sizeMaxWidthTypeHeadingXlargeMobile: SizeSemanticToken { get }
    var sizeMaxWidthTypeHeadingXlargeTablet: SizeSemanticToken { get }
    var sizeMaxWidthTypeHeadingLargeMobile: SizeSemanticToken { get }
    var sizeMaxWidthTypeHeadingLargeTablet: SizeSemanticToken { get }
    var sizeMaxWidthTypeHeadingMediumMobile: SizeSemanticToken { get }
    var sizeMaxWidthTypeHeadingMediumTablet: SizeSemanticToken { get }
    var sizeMaxWidthTypeHeadingSmallMobile: SizeSemanticToken { get }
    var sizeMaxWidthTypeHeadingSmallTablet: SizeSemanticToken { get }

    var sizeMaxWidthTypeBodyLargeMobile: SizeSemanticToken { get }
    var sizeMaxWidthTypeBodyLargeTablet: SizeSemanticToken { get }
    var sizeMaxWidthTypeBodyMediumMobile: SizeSemanticToken { get }
    var sizeMaxWidthTypeBodyMediumTablet: SizeSemanticToken { get }
    var sizeMaxWidthTypeBodySmallMobile: SizeSemanticToken { get }
    var sizeMaxWidthTypeBodySmallTablet: SizeSemanticToken { get }

    // MARK: - Semantic token - Sizing - Icon with typography

    var sizeIconWithLabelXlargeSizeSmall: SizeSemanticToken { get }
    var sizeIconWithLabelXlargeSizeMedium: SizeSemanticToken { get }
    var sizeIconWithLabelXlargeSizeLarge: SizeSemanticToken { get }

    var sizeIconWithLabelLargeSizeXsmall: SizeSemanticToken { get }
    var sizeIconWithLabelLargeSizeSmall: SizeSemanticToken { get }
    var sizeIconWithLabelLargeSizeMedium: SizeSemanticToken { get }
    var sizeIconWithLabelLargeSizeLarge: SizeSemanticToken { get }
    var sizeIconWithLabelLargeSizeXlarge: SizeSemanticToken { get }

    var sizeIconWithLabelMediumSizeXsmall: SizeSemanticToken { get }
    var sizeIconWithLabelMediumSizeSmall: SizeSemanticToken { get }
    var sizeIconWithLabelMediumSizeMedium: SizeSemanticToken { get }
    var sizeIconWithLabelMediumSizeLarge: SizeSemanticToken { get }

    var sizeIconWithLabelSmallSizeXsmall: SizeSemanticToken { get }
    var sizeIconWithLabelSmallSizeSmall: SizeSemanticToken { get }
    var sizeIconWithLabelSmallSizeMedium: SizeSemanticToken { get }
    var sizeIconWithLabelSmallSizeLarge: SizeSemanticToken { get }

    // MARK: - Semantic token - Sizing - Icon decorative

    var sizeIconDecorative4xsmall: SizeSemanticToken { get }
    var sizeIconDecorative3xsmall: SizeSemanticToken { get }
    var sizeIconDecorative2xsmall: SizeSemanticToken { get }
    var sizeIconDecorativeXsmall: SizeSemanticToken { get }
    var sizeIconDecorativeSmall: SizeSemanticToken { get }
    var sizeIconDecorativeMedium: SizeSemanticToken { get }
    var sizeIconDecorativeLarge: SizeSemanticToken { get }
    var sizeIconDecorativeXlarge: SizeSemanticToken { get }
    var sizeIconDecorative2xlarge: SizeSemanticToken { get }

    // MARK: - Semantic token - Sizing - Interactive area

    var sizeMinInteractiveArea: SizeSemanticToken { get }
}

// swiftlint:enable missing_docs
// swiftlint:enable identifier_name
