//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs

/// This is a group of semantic tokens for **spacing**.
/// It defines all ``SpaceSemanticToken`` a theme must have.
/// Any space semantic token must be declared there.
///
/// - Since: 0.8.0
public protocol SpaceSemanticTokens {

    // MARK: Semantic token - Spacing - Scaled

    var spaceScaledNoneMobile: SpaceSemanticToken { get }
    var spaceScaledNoneTablet: SpaceSemanticToken { get }
    var spaceScaled3xsMobile: SpaceSemanticToken { get }
    var spaceScaled3xsTablet: SpaceSemanticToken { get }
    var spaceScaled2xsMobile: SpaceSemanticToken { get }
    var spaceScaled2xsTablet: SpaceSemanticToken { get }
    var spaceScaledXsMobile: SpaceSemanticToken { get }
    var spaceScaledXsTablet: SpaceSemanticToken { get }
    var spaceScaledSmMobile: SpaceSemanticToken { get }
    var spaceScaledSmTablet: SpaceSemanticToken { get }
    var spaceScaledMdMobile: SpaceSemanticToken { get }
    var spaceScaledMdTablet: SpaceSemanticToken { get }
    var spaceScaledLgMobile: SpaceSemanticToken { get }
    var spaceScaledLgTablet: SpaceSemanticToken { get }
    var spaceScaledXlMobile: SpaceSemanticToken { get }
    var spaceScaledXlTablet: SpaceSemanticToken { get }
    var spaceScaled2xlMobile: SpaceSemanticToken { get }
    var spaceScaled2xlTablet: SpaceSemanticToken { get }
    var spaceScaled3xlMobile: SpaceSemanticToken { get }
    var spaceScaled3xlTablet: SpaceSemanticToken { get }

    // MARK: Semantic token - Spacing - Fixed

    var spaceFixedNone: SpaceSemanticToken { get }
    var spaceFixed3xs: SpaceSemanticToken { get }
    var spaceFixed2xs: SpaceSemanticToken { get }
    var spaceFixedXs: SpaceSemanticToken { get }
    var spaceFixedSm: SpaceSemanticToken { get }
    var spaceFixedMd: SpaceSemanticToken { get }
    var spaceFixedLg: SpaceSemanticToken { get }
    var spaceFixedXl: SpaceSemanticToken { get }
    var spaceFixed2xl: SpaceSemanticToken { get }
    var spaceFixed3xl: SpaceSemanticToken { get }
    var spaceFixed4xl: SpaceSemanticToken { get }
    var spaceFixed5xl: SpaceSemanticToken { get }

    // MARK: Semantic token - Spacing - Padding - Padding inline

    var spacePaddingInlineNone: SpaceSemanticToken { get }
    var spacePaddingInlineSmash: SpaceSemanticToken { get }
    var spacePaddingInlineShortest: SpaceSemanticToken { get }
    var spacePaddingInlineShorter: SpaceSemanticToken { get }
    var spacePaddingInlineShort: SpaceSemanticToken { get }
    var spacePaddingInlineMedium: SpaceSemanticToken { get }
    var spacePaddingInlineTall: SpaceSemanticToken { get }
    var spacePaddingInlineTaller: SpaceSemanticToken { get }
    var spacePaddingInlineTallest: SpaceSemanticToken { get }
    var spacePaddingInlineSpacious: SpaceSemanticToken { get }
    var spacePaddingInlineHuge: SpaceSemanticToken { get }

    // MARK: Semantic token - Spacing - Padding - Padding stack

    var spacePaddingBlockNone: SpaceSemanticToken { get }
    var spacePaddingBlockSmash: SpaceSemanticToken { get }
    var spacePaddingBlockShortest: SpaceSemanticToken { get }
    var spacePaddingBlockShorter: SpaceSemanticToken { get }
    var spacePaddingBlockShort: SpaceSemanticToken { get }
    var spacePaddingBlockMedium: SpaceSemanticToken { get }
    var spacePaddingBlockTall: SpaceSemanticToken { get }
    var spacePaddingBlockTaller: SpaceSemanticToken { get }
    var spacePaddingBlockTallest: SpaceSemanticToken { get }
    var spacePaddingBlockSpacious: SpaceSemanticToken { get }
    var spacePaddingBlockHuge: SpaceSemanticToken { get }

    // MARK: Semantic token - Spacing - Padding - Padding inset

    var spaceInsetNone: SpaceSemanticToken { get }
    var spaceInsetSmash: SpaceSemanticToken { get }
    var spaceInsetShortest: SpaceSemanticToken { get }
    var spaceInsetShorter: SpaceSemanticToken { get }
    var spaceInsetShort: SpaceSemanticToken { get }
    var spaceInsetMedium: SpaceSemanticToken { get }
    var spaceInsetTall: SpaceSemanticToken { get }
    var spaceInsetTaller: SpaceSemanticToken { get }
    var spaceInsetTallest: SpaceSemanticToken { get }
    var spaceInsetSpacious: SpaceSemanticToken { get }

    // MARK: Semantic token - Spacing - Padding - Column Gap

    var spaceColumnGapNone: SpaceSemanticToken { get }
    var spaceColumnGapSmash: SpaceSemanticToken { get }
    var spaceColumnGapShortest: SpaceSemanticToken { get }
    var spaceColumnGapShorter: SpaceSemanticToken { get }
    var spaceColumnGapShort: SpaceSemanticToken { get }
    var spaceColumnGapMedium: SpaceSemanticToken { get }
    var spaceColumnGapTall: SpaceSemanticToken { get }
    var spaceColumnGapTaller: SpaceSemanticToken { get }
    var spaceColumnGapTallest: SpaceSemanticToken { get }

    // MARK: Semantic token - Spacing - Padding - Row Gap

    var spaceRowGapNone: SpaceSemanticToken { get }
    var spaceRowGapSmash: SpaceSemanticToken { get }
    var spaceRowGapShortest: SpaceSemanticToken { get }
    var spaceRowGapShorter: SpaceSemanticToken { get }
    var spaceRowGapShort: SpaceSemanticToken { get }
    var spaceRowGapMedium: SpaceSemanticToken { get }
    var spaceRowGapTall: SpaceSemanticToken { get }
}

// swiftlint:enable missing_docs
