//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable missing_docs
// swiftlint:disable line_length

/// This is a group of semantic tokens for **spacings** but using ``MultipleSpaceSemanticTokens``.
///
/// In fact the ``MultipleSpaceSemanticTokens`` class will help users (i.e. developers) to handle one semantic token for spacing containing values for compact (mobile) or regular (tablet) size classes.
/// Because *Figma* is not able to manage pair of values for one token, and its produced JSON does not reflect this mecanism, the *tokenator* cannot provide such ``MultipleSpaceSemanticTokens``.
/// Thus the "real" color semantic tokens are declared in ``SpaceSemanticTokens`` protocol and defined inside `OUDSTheme` (to be overridable then by subthemes).
/// These tokens are updated by the *tokenator*. Then they are gathered and wrapped so as to be used easily thanks to this ``SpaceMultipleSemanticTokens`` which must be updated manually.
///
/// Each token declared in this protocol must have its version *Mobile* and *Tablet* declared in ``SpaceSemanticTokens`` protocol in order to define ``MultipleSpaceSemanticTokens`` for each pair of them.
///
/// In few words:
/// ```swift
///         // Some spacing raw tokens, defined by the tokenator (in DimensionRawTokens+Values.swift)
///         public static let dimension0: DimensionRawToken = 0
///         public static let dimension25: DimensionRawToken = 2
///
///         // The spacing semantic tokens using them,
///         // declared (in SpaceSemanticTokens.swift) and defined (in OUDSTheme+SpaceSemanticTokens.swift) by the tokenator
///         var spaceScaledNoneMobile: SpaceSemanticToken { DimensionRawTokens.dimension0 }
///         var spaceScaledNoneTablet: SpaceSemanticToken { DimensionRawTokens.dimension25 }
///
///         // The 'higher level' spacing semantic tokens wrapping them and exposed to users,
///         // declared (in SpaceMultipleSemanticTokens.swift) and defined (in OUDSTheme+SpaceMultipleSemanticTokens.swift) manualy
///         var spaceScaledNone: MultipleSpaceSemanticTokens { MultipleSpaceSemanticTokens(compact: spaceScaledNoneMobile, regular: spaceScaledNoneTablet) }
///
///         // Thus users can in their components use spaceScaledNone as defined in their design system
///         // (even if they are still able to use 'lower level' semantic tokens but it is more error-prone)
/// ```
///
/// - Since: 0.8.0
public protocol SpaceMultipleSemanticTokens {

    // MARK: Semantic token - Spacing - Scaled

    var spaceScaledNone: MultipleSpaceSemanticTokens { get }
    var spaceScaledSmash: MultipleSpaceSemanticTokens { get }
    var spaceScaledShortest: MultipleSpaceSemanticTokens { get }
    var spaceScaledShorter: MultipleSpaceSemanticTokens { get }
    var spaceScaledShort: MultipleSpaceSemanticTokens { get }
    var spaceScaledMedium: MultipleSpaceSemanticTokens { get }
    var spaceScaledTall: MultipleSpaceSemanticTokens { get }
    var spaceScaledTaller: MultipleSpaceSemanticTokens { get }
    var spaceScaledTallest: MultipleSpaceSemanticTokens { get }
    var spaceScaledSpacious: MultipleSpaceSemanticTokens { get }
}

// swiftlint:enable missing_docs
// swiftlint:enable line_length
