//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
// 
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
// 
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System 
//

import OUDSTokensRaw

// ଘ( ･ω･)_/ﾟ･:*:･｡☆
// [File to generate with the tokenator]

/// This is a group of semantic tokens for **typography**.
/// It defines all typography semantic tokens a theme must have
/// (`TypographyFontFamilySemanticToken`, `TypographyFontWeightSemanticToken`, `TypographyFontSizeSemanticToken`, `TypographyFontLineHeightSemanticToken`).
///
/// In the future this file should be generated by a parser converting Figma JSON to Swift code.
public protocol TypographySemanticTokens {

    // MARK: - Semantic token - Typography - Font - Family

    // TODO: Should we suffix our tokens names by "iOS"?

    var fontFamily: TypographyFontFamilyRawToken { get }
    var fontFamilyDisplay: TypographyFontFamilySemanticToken { get }
    var fontFamilyHeading: TypographyFontFamilySemanticToken { get }
    var fontFamilyBody: TypographyFontFamilySemanticToken { get }
    var fontFamilyLabel: TypographyFontFamilySemanticToken { get }
    var fontFamilyCode: TypographyFontFamilySemanticToken { get }

    // MARK: - Semantic token - Typography - Font - Weight

    var fontWeightDefault: TypographyFontWeightSemanticToken { get }
    var fontWeightStrong: TypographyFontWeightSemanticToken { get }
    var fontWeightDisplay: TypographyFontWeightSemanticToken { get }
    var fontWeightHeading: TypographyFontWeightSemanticToken { get }
    var fontWeightBodyDefault: TypographyFontWeightSemanticToken { get }
    var fontWeightBodyStrong: TypographyFontWeightSemanticToken { get }
    var fontWeightLabelDefault: TypographyFontWeightSemanticToken { get }
    var fontWeightLabelStrong: TypographyFontWeightSemanticToken { get }
    var fontWeightCode: TypographyFontWeightSemanticToken { get }

    // MARK: - Semantic token - Typography - Font - Size - Mobile (extra-compact/compact)

    var fontSizeMobileDisplayLarge: TypographyFontSizeSemanticToken { get }
    var fontSizeMobileDisplayMedium: TypographyFontSizeSemanticToken { get }
    var fontSizeMobileDisplaySmall: TypographyFontSizeSemanticToken { get }
    var fontSizeMobileHeadingXLarge: TypographyFontSizeSemanticToken { get }
    var fontSizeMobileHeadingLarge: TypographyFontSizeSemanticToken { get }
    var fontSizeMobileHeadingMedium: TypographyFontSizeSemanticToken { get }
    var fontSizeMobileHeadingSmall: TypographyFontSizeSemanticToken { get }
    var fontSizeMobileBodyLarge: TypographyFontSizeSemanticToken { get }
    var fontSizeMobileBodyMedium: TypographyFontSizeSemanticToken { get }
    var fontSizeMobileBodySmall: TypographyFontSizeSemanticToken { get }

    // MARK: - Semantic token - Typography - Font - Size - Tablet (regular/medium

    var fontSizeTabletDisplayLarge: TypographyFontSizeSemanticToken { get }
    var fontSizeTabletDisplayMedium: TypographyFontSizeSemanticToken { get }
    var fontSizeTabletDisplaySmall: TypographyFontSizeSemanticToken { get }
    var fontSizeTabletHeadingXLarge: TypographyFontSizeSemanticToken { get }
    var fontSizeTabletHeadingLarge: TypographyFontSizeSemanticToken { get }
    var fontSizeTabletHeadingMedium: TypographyFontSizeSemanticToken { get }
    var fontSizeTabletHeadingSmall: TypographyFontSizeSemanticToken { get }
    var fontSizeTabletBodyLarge: TypographyFontSizeSemanticToken { get }
    var fontSizeTabletBodyMedium: TypographyFontSizeSemanticToken { get }
    var fontSizeTabletBodySmall: TypographyFontSizeSemanticToken { get }

    // MARK: - Semantic token - Typography - Font - Size - Others

    var fontSizeLabelXLarge: TypographyFontSizeSemanticToken { get }
    var fontSizeLabelLarge: TypographyFontSizeSemanticToken { get }
    var fontSizeLabelMedium: TypographyFontSizeSemanticToken { get }
    var fontSizeLabelSmall: TypographyFontSizeSemanticToken { get }
    var fontSizeCodeMedium: TypographyFontSizeSemanticToken { get }
    var fontSizeCodeSmall: TypographyFontSizeSemanticToken { get }

    // MARK: - Semantic token - Typography - Font - Line height - Mobile (extra-compact/compact)

    var fontLineHeightMobileDisplayLarge: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightMobileDisplayMedium: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightMobileDisplaySmall: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightMobileHeadingXLarge: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightMobileHeadingLarge: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightMobileHeadingMedium: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightMobileHeadingSmall: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightMobileBodyLarge: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightMobileBodyMedium: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightMobileBodySmall: TypographyFontLineHeightSemanticToken { get }

    // MARK: - Semantic token - Typography - Font - Line height - Tablet (regular/medium)

    var fontLineHeightTabletDisplayLarge: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightTabletDisplayMedium: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightTabletDisplaySmall: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightTabletHeadingXLarge: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightTabletHeadingLarge: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightTabletHeadingMedium: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightTabletHeadingSmall: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightTabletBodyLarge: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightTabletBodyMedium: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightTabletBodySmall: TypographyFontLineHeightSemanticToken { get }

    // MARK: - Semantic token - Typography - Font - Line height - Others

    var fontLineHeightLabelXLarge: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightLabelLarge: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightLabelMedium: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightLabelSmall: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightCodeMedium: TypographyFontLineHeightSemanticToken { get }
    var fontLineHeightCodeSmall: TypographyFontLineHeightSemanticToken { get }

    // MARK: - Semantic token - Typography - Font - Letter spacing
    // TODO: Missing details about the types of the associated raw tokens

    // MARK: - Semantic tokens - Typography - Composites - Display

    var typeDisplayLarge: MultipleTypographyTokens { get }
    var typeDisplayMedium: MultipleTypographyTokens { get }
    var typeDisplaySmall: MultipleTypographyTokens { get }

    // MARK: - Semantic tokens - Typography - Composites - Heading

    var typeHeadingXLarge: MultipleTypographyTokens { get }
    var typeHeadingLarge: MultipleTypographyTokens { get }
    var typeHeadingMedium: MultipleTypographyTokens { get }
    var typeHeadingSmall: MultipleTypographyTokens { get }

    // MARK: - Semantic tokens - Typography - Composites - Body

    var typeBodyDefaultLarge: MultipleTypographyTokens { get }
    var typeBodyDefaultMedium: MultipleTypographyTokens { get }
    var typeBodyDefaultSmall: MultipleTypographyTokens { get }
    var typeBodyStrongLarge: MultipleTypographyTokens { get }
    var typeBodyStrongMedium: MultipleTypographyTokens { get }
    var typeBodyStrongSmall: MultipleTypographyTokens { get }

    // MARK: - Semantic tokens - Typography - Composites - Label

    var typeLabelDefaultXLarge: MultipleTypographyTokens { get }
    var typeLabelDefaultLarge: MultipleTypographyTokens { get }
    var typeLabelDefaultMedium: MultipleTypographyTokens { get }
    var typeLabelDefaultSmall: MultipleTypographyTokens { get }
    var typeLabelStrongXLarge: MultipleTypographyTokens { get }
    var typeLabelStrongLarge: MultipleTypographyTokens { get }
    var typeLabelStrongMedium: MultipleTypographyTokens { get }
    var typeLabelStrongSmall: MultipleTypographyTokens { get }

    // MARK: - Semantic tokens - Typography - Composites - Code

    var typeCodeMedium: MultipleTypographyTokens { get }
    var typeCodeSmall: MultipleTypographyTokens { get }
}
