//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensSemantic

// 🧬 Tokens version: 2.1.0 (Wireframe brand)
// 🤖 Generated by Tokenator

// swiftlint:disable line_length

extension WireframeThemeButtonComponentTokensProvider: ButtonComponentTokens {
    /// Has for value token colors.surfaceBrandSecondary
    @objc public final var buttonColorBgBrandEnabled: MultipleColorSemanticTokens { colors.surfaceBrandSecondary }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositorySecondaryHigh, dark: colors.colorRepositorySecondaryLower)
    @objc public final var buttonColorBgBrandHover: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositorySecondaryHigh, dark: colors.colorRepositorySecondaryLower) }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositorySecondaryHigher, dark: colors.colorRepositorySecondaryLowest)
    @objc public final var buttonColorBgBrandPressed: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositorySecondaryHigher, dark: colors.colorRepositorySecondaryLowest) }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositorySecondaryHigher, dark: colors.colorRepositorySecondaryLowest)
    @objc public final var buttonColorBgBrandLoading: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositorySecondaryHigher, dark: colors.colorRepositorySecondaryLowest) }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositorySecondaryHigh, dark: colors.colorRepositorySecondaryLower)
    @objc public final var buttonColorBgBrandFocus: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositorySecondaryHigh, dark: colors.colorRepositorySecondaryLower) }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositoryOpacityPrimaryLowest, dark: colors.colorRepositoryOpacityPrimaryMedium)
    @objc public final var buttonColorBgDefaultEnabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositoryOpacityPrimaryLowest, dark: colors.colorRepositoryOpacityPrimaryMedium) }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositoryOpacityPrimaryLower, dark: colors.colorRepositoryOpacityPrimaryHigh)
    @objc public final var buttonColorBgDefaultHover: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositoryOpacityPrimaryLower, dark: colors.colorRepositoryOpacityPrimaryHigh) }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositoryOpacityPrimaryLow, dark: colors.colorRepositoryOpacityPrimaryHigher)
    @objc public final var buttonColorBgDefaultPressed: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositoryOpacityPrimaryLow, dark: colors.colorRepositoryOpacityPrimaryHigher) }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositoryOpacityPrimaryLow, dark: colors.colorRepositoryOpacityPrimaryHigher)
    @objc public final var buttonColorBgDefaultLoading: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositoryOpacityPrimaryLow, dark: colors.colorRepositoryOpacityPrimaryHigher) }
    /// Has for value token colors.actionDisabled
    @objc public final var buttonColorBgDefaultDisabled: MultipleColorSemanticTokens { colors.actionDisabled }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositoryOpacityPrimaryLower, dark: colors.colorRepositoryOpacityPrimaryHigh)
    @objc public final var buttonColorBgDefaultFocus: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositoryOpacityPrimaryLower, dark: colors.colorRepositoryOpacityPrimaryHigh) }
    /// Has for value token colors.actionSupportHover
    @objc public final var buttonColorBgMinimalHover: MultipleColorSemanticTokens { colors.actionSupportHover }
    /// Has for value token colors.actionSupportPressed
    @objc public final var buttonColorBgMinimalPressed: MultipleColorSemanticTokens { colors.actionSupportPressed }
    /// Has for value token colors.actionSupportFocus
    @objc public final var buttonColorBgMinimalFocus: MultipleColorSemanticTokens { colors.actionSupportFocus }
    /// Has for value token colors.contentOnBrandSecondary
    @objc public final var buttonColorContentBrandEnabled: MultipleColorSemanticTokens { colors.contentOnBrandSecondary }
    /// Has for value token colors.contentOnActionHover
    @objc public final var buttonColorContentBrandHover: MultipleColorSemanticTokens { colors.contentOnActionHover }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositoryNeutralMutedWhite, dark: colors.colorRepositoryNeutralEmphasizedBlack)
    @objc public final var buttonColorContentBrandPressed: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositoryNeutralMutedWhite, dark: colors.colorRepositoryNeutralEmphasizedBlack) }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositoryNeutralMutedWhite, dark: colors.colorRepositoryNeutralEmphasizedBlack)
    @objc public final var buttonColorContentBrandLoading: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositoryNeutralMutedWhite, dark: colors.colorRepositoryNeutralEmphasizedBlack) }
    /// Has for value token colors.contentOnActionFocus
    @objc public final var buttonColorContentBrandFocus: MultipleColorSemanticTokens { colors.contentOnActionFocus }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositoryPrimaryHigh, dark: colors.colorRepositoryPrimaryLower)
    @objc public final var buttonColorContentDefaultEnabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositoryPrimaryHigh, dark: colors.colorRepositoryPrimaryLower) }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositoryPrimaryHigh, dark: colors.colorRepositoryPrimaryLower)
    @objc public final var buttonColorContentDefaultHover: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositoryPrimaryHigh, dark: colors.colorRepositoryPrimaryLower) }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositoryPrimaryHigh, dark: colors.colorRepositoryPrimaryLower)
    @objc public final var buttonColorContentDefaultPressed: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositoryPrimaryHigh, dark: colors.colorRepositoryPrimaryLower) }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositoryPrimaryHigh, dark: colors.colorRepositoryPrimaryLower)
    @objc public final var buttonColorContentDefaultLoading: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositoryPrimaryHigh, dark: colors.colorRepositoryPrimaryLower) }
    /// Has for value token colors.actionDisabled
    @objc public final var buttonColorContentDefaultDisabled: MultipleColorSemanticTokens { colors.actionDisabled }
    /// Has for value token MultipleColorSemanticTokens(light: colors.colorRepositoryPrimaryHigh, dark: colors.colorRepositoryPrimaryLower)
    @objc public final var buttonColorContentDefaultFocus: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: colors.colorRepositoryPrimaryHigh, dark: colors.colorRepositoryPrimaryLower) }
    /// Has for value token colors.actionEnabled
    @objc public final var buttonColorContentMinimalEnabled: MultipleColorSemanticTokens { colors.actionEnabled }
    /// Has for value token colors.actionHover
    @objc public final var buttonColorContentMinimalHover: MultipleColorSemanticTokens { colors.actionHover }
    /// Has for value token colors.actionPressed
    @objc public final var buttonColorContentMinimalPressed: MultipleColorSemanticTokens { colors.actionPressed }
    /// Has for value token colors.actionLoading
    @objc public final var buttonColorContentMinimalLoading: MultipleColorSemanticTokens { colors.actionLoading }
    /// Has for value token colors.actionDisabled
    @objc public final var buttonColorContentMinimalDisabled: MultipleColorSemanticTokens { colors.actionDisabled }
    /// Has for value token colors.actionFocus
    @objc public final var buttonColorContentMinimalFocus: MultipleColorSemanticTokens { colors.actionFocus }
    /// Has for value token colors.opacityTransparent
    @objc public final var buttonColorBorderDefaultEnabled: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent
    @objc public final var buttonColorBorderDefaultHover: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent
    @objc public final var buttonColorBorderDefaultPressed: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent
    @objc public final var buttonColorBorderDefaultLoading: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent
    @objc public final var buttonColorBorderDefaultDisabled: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent
    @objc public final var buttonColorBorderDefaultFocus: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token borders.radiusDefault
    @objc public final var buttonBorderRadiusDefault: BorderRadiusSemanticToken { borders.radiusDefault }
    /// Has for value token borders.radiusDefault
    @objc public final var buttonBorderRadiusRounded: BorderRadiusSemanticToken { borders.radiusDefault }
    /// Has for value token borders.radiusPill
    @objc public final var buttonBorderRadiusSocial: BorderRadiusSemanticToken { borders.radiusPill }
    /// Has for value token borders.widthNone
    @objc public final var buttonBorderWidthDefault: BorderWidthSemanticToken { borders.widthNone }
    /// Has for value token borders.widthNone
    @objc public final var buttonBorderWidthDefaultInteraction: BorderWidthSemanticToken { borders.widthNone }
    /// Has for value token borders.widthNone
    @objc public final var buttonBorderWidthDefaultInteractionMono: BorderWidthSemanticToken { borders.widthNone }
    /// Has for value token spaces.spaceInsetMedium
    @objc public final var buttonSpaceInsetIconOnly: SpaceSemanticToken { spaces.spaceInsetMedium }
    /// Has for value token spaces.spacePaddingBlockMedium
    @objc public final var buttonSpacePaddingBlock: SpaceSemanticToken { spaces.spacePaddingBlockMedium }
    /// Has for value token spaces.spacePaddingInline3xlarge
    @objc public final var buttonSpacePaddingInlineStartIconEnd: SpaceSemanticToken { spaces.spacePaddingInline3xlarge }
    /// Has for value token spaces.spacePaddingInline3xlarge
    @objc public final var buttonSpacePaddingInlineEndIconStart: SpaceSemanticToken { spaces.spacePaddingInline3xlarge }
    /// Has for value token spaces.spacePaddingInline4xlarge
    @objc public final var buttonSpacePaddingInlineIconNone: SpaceSemanticToken { spaces.spacePaddingInline4xlarge }
    /// Has for value token spaces.spacePaddingInlineXlarge
    @objc public final var buttonSpacePaddingInlineIconStart: SpaceSemanticToken { spaces.spacePaddingInlineXlarge }
    /// Has for value token spaces.spacePaddingInlineLarge
    @objc public final var buttonSpacePaddingInlineChevronStart: SpaceSemanticToken { spaces.spacePaddingInlineLarge }
    /// Has for value token spaces.spacePaddingInlineLarge
    @objc public final var buttonSpacePaddingInlineChevronEnd: SpaceSemanticToken { spaces.spacePaddingInlineLarge }
    /// Has for value token spaces.spaceColumnGapSmall
    @objc public final var buttonSpaceColumnGapIcon: SpaceSemanticToken { spaces.spaceColumnGapSmall }
    /// Has for value token spaces.spaceColumnGapXsmall
    @objc public final var buttonSpaceColumnGapChevron: SpaceSemanticToken { spaces.spaceColumnGapXsmall }
    /// Has for value token spaces.spaceColumnGap2xsmall
    @objc public final var buttonSpaceColumnGapIconChevron: SpaceSemanticToken { spaces.spaceColumnGap2xsmall }
    /// Has for value token sizes.sizeIconWithLabelLargeSizeXsmall
    @objc public final var buttonSizeIcon: SizeSemanticToken { sizes.sizeIconWithLabelLargeSizeXsmall }
    /// Has for value token sizes.sizeIconWithLabelLargeSizeSmall
    @objc public final var buttonSizeIconOnly: SizeSemanticToken { sizes.sizeIconWithLabelLargeSizeSmall }
    /// Has for value token sizes.sizeIconWithLabelLargeSizeXsmall
    @objc public final var buttonSizeLoader: SizeSemanticToken { sizes.sizeIconWithLabelLargeSizeXsmall }
    /// Has for value token sizes.sizeMinInteractiveArea
    @objc public final var buttonSizeMinHeight: SizeSemanticToken { sizes.sizeMinInteractiveArea }
    /// Has for value token sizes.sizeMinInteractiveArea
    @objc public final var buttonSizeMinWidth: SizeSemanticToken { sizes.sizeMinInteractiveArea }
    /// Has for value token sizes.sizeMinInteractiveArea
    @objc public final var buttonSizeMaxHeightIconOnly: SizeSemanticToken { sizes.sizeMinInteractiveArea }
}

// swiftlint:enable line_length
