//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensSemantic

// 🧬 Tokens version: 1.1.0 (Wireframe brand)
// 🤖 Generated by Tokenator

extension WireframeThemePinCodeInputComponentTokensProvider: PinCodeInputComponentTokens {
    /// Has for value token spaces.spaceColumnGapMd
    @objc public final var pinCodeInputSpaceColumnGapDigitInput: SpaceSemanticToken { spaces.spaceColumnGapMd }
    /// Has for value token dimensions.dimensionLg
    @objc public final var pinCodeInputSizeMinWidth: SizeSemanticToken { dimensions.dimensionLg }
    /// Has for value token dimensions.dimension3xl
    @objc public final var pinCodeInputSizeMaxWidth: SizeSemanticToken { dimensions.dimension3xl }
}
