//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// 🤖 Generated by Tokenator

/// Gathers the components and themes versions exposed through Tokenator based on Figma tokens
public enum OUDSVersions {

    // MARK: - Themes versions

    /// Version of the Core tokens library
    public static let themeCoreVersion = "1.3.0"
    /// Version of the Orange core tokens library
    public static let themeOrangeCoreVersion = "1.1.0"
    /// Version of the Orange brand tokens library
    public static let themeOrangeBrandVersion = "1.3.0"
    /// Version of the Sosh core tokens library
    public static let themeSoshCoreVersion = "1.1.0"
    /// Version of the Sosh brand tokens library
    public static let themeSoshBrandVersion = "1.3.0"
    /// Version of the Orange Business Tools brand tokens library
    public static let themeOrangeBusinessToolsBrandVersion = "1.3.0"
    /// Version fo the Orange Inverse brand tokens library
    public static let themeOrangeInverseBrandVersion = "1.3.0"

    // MARK: - Components versions - Actions

    /// Version of the Figma specifications for the component button
    public static let componentButtonVersion = "2.1.0"

    // MARK: - Components versions - Navigation

    /// Version of the Figma specifications for the component link
    public static let componentLinkVersion = "2.1.0"

    // MARK: - Components versions - Input

    /// Version of the Figma specifications for the component checkbox
    public static let componentCheckboxVersion = "2.1.0"
    /// Version of the Figma specifications for the component chip
    public static let componentChipVersion = "1.2.0"
    /// Version of the Figma specifications for the component radio button
    public static let componentRadioButtonVersion = "1.1.0"
    /// Version of the Figma specifications for the component switch
    public static let componentSwitchVersion = "1.2.0"

    // MARK: - Components versions - Tag

    /// Version of the Figma specifications for the component badge
    public static let componentBadgeVersion = "1.1.0"
    /// Version of the Figma specifications for the component skeleton
    public static let componentSkeletonVersion = "1.0.0"
    /// Version of the Figma specifications for the component tag
    public static let componentTagVersion = "1.1.0"

    // MARK: - Components versions - Divider

    /// Version of the Figma specifications for the component divider
    public static let componentDividerVersion = "1.0.0"

    // MARK: - Components versions - Content display

    /// Version of the Figma specifications for the component bullet list
    public static let componentBulletListVersion = "1.0.0"
}
