//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensRaw
import OUDSTokensSemantic

// 🧬 Tokens version: 2.1.0 (Sosh brand)
// 🤖 Generated by Tokenator

extension SoshThemeControlItemComponentTokensProvider: ControlItemComponentTokens {
    /// Has for value token colors.actionSupportHover
    @objc public final var controlItemColorBgHover: MultipleColorSemanticTokens { colors.actionSupportHover }
    /// Has for value token colors.actionSupportPressed
    @objc public final var controlItemColorBgPressed: MultipleColorSemanticTokens { colors.actionSupportPressed }
    /// Has for value token colors.actionSupportLoading
    @objc public final var controlItemColorBgLoading: MultipleColorSemanticTokens { colors.actionSupportLoading }
    /// Has for value token colors.actionSupportFocus
    @objc public final var controlItemColorBgFocus: MultipleColorSemanticTokens { colors.actionSupportFocus }
    /// Has for value token colors.contentDefault
    @objc public final var controlItemColorContentLoader: MultipleColorSemanticTokens { colors.contentDefault }
    /// Has for value token borders.radiusNone
    @objc public final var controlItemBorderRadius: BorderRadiusSemanticToken { borders.radiusNone }
    /// Has for value token borders.radiusDefault
    @objc public final var controlItemBorderRadiusItemOnly: BorderRadiusSemanticToken { borders.radiusDefault }
    /// Has for value token spaces.spacePaddingBlockMedium
    @objc public final var controlItemSpacePaddingBlock: SpaceSemanticToken { spaces.spacePaddingBlockMedium }
    /// Has for value token spaces.spacePaddingInlineLarge
    @objc public final var controlItemSpacePaddingInline: SpaceSemanticToken { spaces.spacePaddingInlineLarge }
    /// Has for value token spaces.spacePaddingInline4xsmall
    @objc public final var controlItemSpacePaddingInlineErrorIcon: SpaceSemanticToken { spaces.spacePaddingInline4xsmall }
    /// Has for value token spaces.spaceColumnGapMedium
    @objc public final var controlItemSpaceColumnGap: SpaceSemanticToken { spaces.spaceColumnGapMedium }
    /// Has for value token spaces.spaceRowGapNone
    @objc public final var controlItemSpaceRowGap: SpaceSemanticToken { spaces.spaceRowGapNone }
    /// Has for value token sizes.sizeIconWithLabelLargeSizeMedium
    @objc public final var controlItemSizeIcon: SizeSemanticToken { sizes.sizeIconWithLabelLargeSizeMedium }
    /// Has for value token sizes.sizeIconWithLabelLargeSizeSmall
    @objc public final var controlItemSizeErrorIcon: SizeSemanticToken { sizes.sizeIconWithLabelLargeSizeSmall }
    /// Has for value token sizes.sizeIconWithLabelLargeSizeSmall
    @objc public final var controlItemSizeLoader: SizeSemanticToken { sizes.sizeIconWithLabelLargeSizeSmall }
    /// Has for value token DimensionRawTokens._650
    @objc public final var controlItemSizeMinHeight: SizeSemanticToken { DimensionRawTokens._650 }
    /// Has for value token DimensionRawTokens._1200
    @objc public final var controlItemSizeMaxHeightAssetsContainer: SizeSemanticToken { DimensionRawTokens._1200 }
    /// Has for value token DimensionRawTokens._2000
    @objc public final var controlItemSizeMinWidth: SizeSemanticToken { DimensionRawTokens._2000 }
    /// Has for value token DimensionRawTokens._4000
    @objc public final var controlItemSizeMaxWidth: SizeSemanticToken { DimensionRawTokens._4000 }
}
