//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensRaw
import OUDSTokensSemantic

// 🧬 Tokens version: 2.5.0 (Sosh brand)
// 🤖 Generated by Tokenator

extension SoshThemeLinkComponentTokensProvider: LinkComponentTokens {
    /// Has for value token colors.contentDefault (= light: "#000000FF" / dark: "#E9EEF1FF")
    @objc public final var colorContentEnabled: MultipleColorSemanticToken { colors.contentDefault }
    /// Has for value token colors.actionHover (= light: "#000000FF" / dark: "#E9EEF1FF")
    @objc public final var colorContentHover: MultipleColorSemanticToken { colors.actionHover }
    /// Has for value token colors.actionPressed (= light: "#0173C1FF" / dark: "#FFEF66FF")
    @objc public final var colorContentPressed: MultipleColorSemanticToken { colors.actionPressed }
    /// Has for value token colors.actionFocus (= light: "#000000FF" / dark: "#E9EEF1FF")
    @objc public final var colorContentFocus: MultipleColorSemanticToken { colors.actionFocus }
    /// Has for value token colors.actionEnabled (= light: "#DE034BFF" / dark: "#5DBCFEFF")
    @objc public final var colorChevronEnabled: MultipleColorSemanticToken { colors.actionEnabled }
    /// Has for value token MultipleColorSemanticToken(light: colors.contentBrandPrimaryLight, dark: colors.actionEnabledDark) (= light: "#DE034BFF" / dark: "#5DBCFEFF")
    @objc public final var colorChevronHover: MultipleColorSemanticToken { MultipleColorSemanticToken(light: colors.contentBrandPrimaryLight, dark: colors.actionEnabledDark) }
    /// Has for value token colors.actionPressed (= light: "#0173C1FF" / dark: "#FFEF66FF")
    @objc public final var colorChevronPressed: MultipleColorSemanticToken { colors.actionPressed }
    /// Has for value token colors.actionEnabled (= light: "#DE034BFF" / dark: "#5DBCFEFF")
    @objc public final var colorChevronFocus: MultipleColorSemanticToken { colors.actionEnabled }
    /// Has for value token spaces.paddingInlineNone (= 0)
    @objc public final var spacePaddingInline: SpaceSemanticToken { spaces.paddingInlineNone }
    /// Has for value token spaces.paddingBlockMedium (= 12)
    @objc public final var spacePaddingBlock: SpaceSemanticToken { spaces.paddingBlockMedium }
    /// Has for value token spaces.columnGapSmall (= 8)
    @objc public final var spaceColumnGapIconDefault: SpaceSemanticToken { spaces.columnGapSmall }
    /// Has for value token spaces.columnGapXsmall (= 6)
    @objc public final var spaceColumnGapIconSmall: SpaceSemanticToken { spaces.columnGapXsmall }
    /// Has for value token spaces.columnGap2xsmall (= 4)
    @objc public final var spaceColumnGapChevronDefault: SpaceSemanticToken { spaces.columnGap2xsmall }
    /// Has for value token spaces.columnGap2xsmall (= 4)
    @objc public final var spaceColumnGapChevronSmall: SpaceSemanticToken { spaces.columnGap2xsmall }
    /// Has for value token sizes.iconWithLabelLargeSizeXsmall (= 20)
    @objc public final var sizeIconDefault: SizeSemanticToken { sizes.iconWithLabelLargeSizeXsmall }
    /// Has for value token sizes.iconWithLabelMediumSizeSmall (= 16)
    @objc public final var sizeIconSmall: SizeSemanticToken { sizes.iconWithLabelMediumSizeSmall }
    /// Has for value token sizes.minInteractiveArea (= 48)
    @objc public final var sizeMinHeightDefault: SizeSemanticToken { sizes.minInteractiveArea }
    /// Has for value token sizes.minInteractiveArea (= 48)
    @objc public final var sizeMinWidthDefault: SizeSemanticToken { sizes.minInteractiveArea }
    /// Has for value token DimensionRawTokens._550 (= 44)
    @objc public final var sizeMinHeightSmall: SizeSemanticToken { DimensionRawTokens._550 }
    /// Has for value token DimensionRawTokens._550 (= 44)
    @objc public final var sizeMinWidthSmall: SizeSemanticToken { DimensionRawTokens._550 }
}
