//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

#if !os(watchOS) && !os(tvOS)
import SwiftUI

// swiftlint:disable line_length

/// The data to use to populate the picker of ``OUDSCheckboxItem`` objects.
/// Each property in this ``OUDSCheckboxPickerData`` is used to define the suitable ``OUDSCheckboxItem``.
///
/// - Since: 0.14.0
public struct OUDSCheckboxPickerData<Tag> where Tag: Hashable {

    /// The identifier, supposed to be unique, to discriminate the element.
    /// This value will be exposed as selection inside the ``OUDSCheckboxPicker``.
    let tag: Tag

    /// The label, main text, the ``OUDSCheckboxItem`` must have
    let label: String

    /// An optional helper text the ``OUDSCheckboxItem`` can have
    let description: String?

    /// An optional image the ``OUDSCheckboxItem`` can have, encapsulating the asset, flip flag and rendering mode
    let icon: OUDSImage?

    /// Define if the ``OUDSCheckboxItem`` is reversed or not
    let isReversed: Bool

    /// Define if the ``OUDSCheckboxItem`` is in error context or not
    let isError: Bool

    /// Define if the ``OUDSCheckboxItem`` is in read only mode or not
    let isReadOnly: Bool

    /// Define if the ``OUDSCheckboxItem`` has a divider not
    let hasDivider: Bool

    /// If needed, and because the items in the ``OUDSRadioPicker`` are generated by the picker, the accesibility identifier to add to the generated item.
    /// Can be useful for automated tests for examples or anything else.
    /// By default is nil as the logic of identifiers is in the hand of the users.
    let accessibilityIdentifier: String?

    /// Defines the data to use to define the checkbox items (``OUDSCheckboxItem``)
    ///
    /// ```swift
    ///     OUDSCheckboxPickerData(tag: "option1", label: "Option 1")
    ///
    ///     OUDSCheckboxPickerData(tag: "option2",
    ///                            label: "Option 2",
    ///                            image: OUDSImage(asset: Image(systemName: "flame")))
    ///
    ///     // Raw (non-tinted) image:
    ///     OUDSCheckboxPickerData(tag: "option3",
    ///                            label: "Option 3",
    ///                            image: OUDSImage(asset: Image(decorative: "il_brand"), renderingMode: .original))
    /// ```
    ///
    /// - Parameters:
    ///    - tag: a value to discriminate one checkbox to another
    ///    - label: the mandatory text to add to ``OUDSCheckboxItem``
    ///    - description: An optional text, default set to nil
    ///    - image: An optional ``OUDSImage`` encapsulating the asset, its flip flag and its rendering mode. Default set to `nil`.
    ///    - isReversed: True to use to reversed layout of the ``OUDSCheckboxItem``, false otherwise (default)
    ///    - isError: True if in an error context, false otherwise (default)
    ///    - isReadOnly: True if read only, false otherwise (default)
    ///    - hasDivider: True if a divider must be added for the current ``OUDSCheckboxItem``, false otherwise (default)
    ///    - accessibilityIdentifier: The accessibility identifier to add to the item, nil by default
    ///
    /// **Remark: If `label` and `description` strings are wording keys from strings catalog stored in `Bundle.main`, they are automatically localized. Else, prefer to
    /// provide the localized string if key is stored in another bundle.**
    public init(tag: Tag,
                label: String,
                description: String? = nil,
                image: OUDSImage? = nil,
                isReversed: Bool = false,
                isError: Bool = false,
                isReadOnly: Bool = false,
                hasDivider: Bool = false,
                accessibilityIdentifier: String? = nil)
    {
        self.tag = tag
        self.label = label
        self.description = description
        icon = image
        self.isReversed = isReversed
        self.isError = isError
        self.isReadOnly = isReadOnly
        self.hasDivider = hasDivider
        self.accessibilityIdentifier = accessibilityIdentifier
    }

    /// Defines the data to use to define the checkbox items (``OUDSCheckboxItem``)
    ///
    /// - Parameters:
    ///    - tag: a value to discriminate one checkbox to another
    ///    - label: the mandatory text to add to ``OUDSCheckboxItem``
    ///    - description: An optional text, default set to nil
    ///    - icon: An optional image, default set to nil
    ///    - renderingMode: Default set to `.template`, forces the rendering mode of the image. Should be `.original` for raw images.
    ///    - isReversed: True to use to reversed layout of the ``OUDSCheckboxItem``, false otherwise (default)
    ///    - isError: True if in an error context, false otherwise (default)
    ///    - isReadOnly: True if read only, false otherwise (default)
    ///    - hasDivider: True if a divider must be added for the current ``OUDSCheckboxItem``, false otherwise (default)
    ///    - accessibilityIdentifier: The accessibility identifier to add to the item, nil by default
    @available(*, deprecated, message: "Use OUDSCheckboxPickerData(tag:label:description:image:isReversed:isError:isReadOnly:hasDivider:accessibilityIdentifier:) with icon: OUDSImage? instead.")
    public init(tag: Tag,
                label: String,
                description: String? = nil,
                icon: Image? = nil,
                renderingMode: Image.TemplateRenderingMode = .template,
                isReversed: Bool = false,
                isError: Bool = false,
                isReadOnly: Bool = false,
                hasDivider: Bool = false,
                accessibilityIdentifier: String? = nil)
    {
        let oudsImage = icon.map { OUDSImage(asset: $0, renderingMode: renderingMode) }
        self.init(tag: tag,
                  label: label,
                  description: description,
                  image: oudsImage,
                  isReversed: isReversed,
                  isError: isError,
                  isReadOnly: isReadOnly,
                  hasDivider: hasDivider,
                  accessibilityIdentifier: accessibilityIdentifier)
    }
}

// swiftlint:enable line_length
#endif
