//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

/// Defines provider objects for `ColorChartSemanticTokens` so as to pack them as light and dark modes colors.
/// These values cannot be overriden as not specified / allowed, forbidden by design.
///
/// Helps to expose color chart semantic tokens with two values to use depending to the color scheme (*Figma* cannot manage such tokens and generate them).
extension OrangeThemeColorChartSemanticTokensProvider: ColorChartMultipleSemanticTokens {

    @objc public final var border: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderLight, dark: borderDark) }

    @objc public final var borderContrast: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderContrastLight, dark: borderContrastDark) }

    @objc public final var categoricalTier1: MultipleColorSemanticToken { MultipleColorSemanticToken(light: categoricalTier1Light, dark: categoricalTier1Dark) }

    @objc public final var categoricalTier2: MultipleColorSemanticToken { MultipleColorSemanticToken(light: categoricalTier2Light, dark: categoricalTier2Dark) }

    @objc public final var categoricalTier3: MultipleColorSemanticToken { MultipleColorSemanticToken(light: categoricalTier3Light, dark: categoricalTier3Dark) }

    @objc public final var categoricalTier4: MultipleColorSemanticToken { MultipleColorSemanticToken(light: categoricalTier4Light, dark: categoricalTier4Dark) }

    @objc public final var categoricalTier5: MultipleColorSemanticToken { MultipleColorSemanticToken(light: categoricalTier5Light, dark: categoricalTier5Dark) }

    @objc public final var categoricalTier6: MultipleColorSemanticToken { MultipleColorSemanticToken(light: categoricalTier6Light, dark: categoricalTier6Dark) }

    @objc public final var categoricalTier7: MultipleColorSemanticToken { MultipleColorSemanticToken(light: categoricalTier7Light, dark: categoricalTier7Dark) }

    @objc public final var categoricalTier8: MultipleColorSemanticToken { MultipleColorSemanticToken(light: categoricalTier8Light, dark: categoricalTier8Dark) }

    @objc public final var categoricalTier9: MultipleColorSemanticToken { MultipleColorSemanticToken(light: categoricalTier9Light, dark: categoricalTier9Dark) }

    @objc public final var categoricalTier10: MultipleColorSemanticToken { MultipleColorSemanticToken(light: categoricalTier10Light, dark: categoricalTier10Dark) }

    @objc public final var functionalInfo: MultipleColorSemanticToken { MultipleColorSemanticToken(light: functionalInfoLight, dark: functionalInfoDark) }

    @objc public final var functionalNegative: MultipleColorSemanticToken { MultipleColorSemanticToken(light: functionalNegativeLight, dark: functionalNegativeDark) }

    @objc public final var functionalPositive: MultipleColorSemanticToken { MultipleColorSemanticToken(light: functionalPositiveLight, dark: functionalPositiveDark) }

    @objc public final var functionalWarning: MultipleColorSemanticToken { MultipleColorSemanticToken(light: functionalWarningLight, dark: functionalWarningDark) }

    @objc public final var gridlines: MultipleColorSemanticToken { MultipleColorSemanticToken(light: gridlinesLight, dark: gridlinesDark) }

    @objc public final var highlight: MultipleColorSemanticToken { MultipleColorSemanticToken(light: highlightLight, dark: highlightDark) }

    @objc public final var neutral: MultipleColorSemanticToken { MultipleColorSemanticToken(light: neutralLight, dark: neutralDark) }
}
