//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable line_length

/// Defines basic values common to all themes for `FontCompositeSemanticToken`.
/// These values can be overriden inside ``OrangeThemeFontSemanticTokensProvider`` subclasses (in extensions or not, in the same module or not) thanks to the `@objc open` combination.
/// The aim of this extensions is to make relationships between all composite semantic tokens for typography / fonts and associated composite raw tokens.
/// The *tokenator* is not able to provide code for such "composite" objects because the *Figma* tool itself cannot manage that and does not output anything in its JSON to process.
extension OrangeThemeFontSemanticTokensProvider: FontCompositeSemanticTokens {

    private typealias MCT /* Multiple Composite Tokens */ = MultipleFontCompositeSemanticToken
    private typealias CT /* Composite Token */ = FontCompositeSemanticToken

    // MARK: - Semantic tokens - Typography - Composites - Display

    @objc open var displayLarge: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeDisplayLargeMobile,
                                                                                      lineHeight: lineHeightDisplayLargeMobile,
                                                                                      weight: weightDisplay,
                                                                                      letterSpacing: letterSpacingDisplayLargeMobile),
                                                                          regular: CT(size: sizeDisplayLargeTablet,
                                                                                      lineHeight: lineHeightDisplayLargeTablet,
                                                                                      weight: weightDisplay,
                                                                                      letterSpacing: letterSpacingDisplayLargeTablet)) }

    @objc open var displayMedium: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeDisplayMediumMobile,
                                                                                       lineHeight: lineHeightDisplayMediumMobile,
                                                                                       weight: weightDisplay,
                                                                                       letterSpacing: letterSpacingDisplayMediumMobile),
                                                                           regular: CT(size: sizeDisplayMediumTablet,
                                                                                       lineHeight: lineHeightDisplayMediumTablet,
                                                                                       weight: weightDisplay,
                                                                                       letterSpacing: letterSpacingDisplayMediumTablet)) }

    @objc open var displaySmall: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeDisplaySmallMobile,
                                                                                      lineHeight: lineHeightDisplaySmallMobile,
                                                                                      weight: weightDisplay,
                                                                                      letterSpacing: letterSpacingDisplaySmallMobile),
                                                                          regular: CT(size: sizeDisplaySmallTablet,
                                                                                      lineHeight: lineHeightDisplaySmallTablet,
                                                                                      weight: weightDisplay,
                                                                                      letterSpacing: letterSpacingDisplaySmallTablet)) }

    // MARK: - Semantic tokens - Typography - Composites - Heading

    @objc open var headingXLarge: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeHeadingXlargeMobile,
                                                                                       lineHeight: lineHeightHeadingXlargeMobile,
                                                                                       weight: weightHeading,
                                                                                       letterSpacing: letterSpacingHeadingXlargeMobile),
                                                                           regular: CT(size: sizeHeadingXlargeTablet,
                                                                                       lineHeight: lineHeightHeadingXlargeTablet,
                                                                                       weight: weightHeading,
                                                                                       letterSpacing: letterSpacingHeadingXlargeTablet)) }

    @objc open var headingLarge: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeHeadingLargeMobile,
                                                                                      lineHeight: lineHeightHeadingLargeMobile,
                                                                                      weight: weightHeading,
                                                                                      letterSpacing: letterSpacingHeadingLargeMobile),
                                                                          regular: CT(size: sizeHeadingLargeTablet,
                                                                                      lineHeight: lineHeightHeadingLargeTablet,
                                                                                      weight: weightHeading,
                                                                                      letterSpacing: letterSpacingHeadingLargeTablet)) }

    @objc open var headingMedium: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeHeadingMediumMobile,
                                                                                       lineHeight: lineHeightHeadingMediumMobile,
                                                                                       weight: weightHeading,
                                                                                       letterSpacing: letterSpacingHeadingMediumMobile),
                                                                           regular: CT(size: sizeHeadingMediumTablet,
                                                                                       lineHeight: lineHeightHeadingMediumTablet,
                                                                                       weight: weightHeading,
                                                                                       letterSpacing: letterSpacingHeadingMediumTablet)) }

    @objc open var headingSmall: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeHeadingSmallMobile,
                                                                                      lineHeight: lineHeightHeadingSmallMobile,
                                                                                      weight: weightHeading,
                                                                                      letterSpacing: letterSpacingHeadingSmallMobile),
                                                                          regular: CT(size: sizeHeadingSmallTablet,
                                                                                      lineHeight: lineHeightHeadingSmallTablet,
                                                                                      weight: weightHeading,
                                                                                      letterSpacing: letterSpacingHeadingSmallTablet)) }

    // MARK: - Semantic tokens - Typography - Composites - Body

    @objc open var bodyDefaultLarge: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeBodyLargeMobile,
                                                                                          lineHeight: lineHeightBodyLargeMobile,
                                                                                          weight: weightBodyDefault,
                                                                                          letterSpacing: letterSpacingBodyLargeMobile),
                                                                              regular: CT(size: sizeBodyLargeTablet,
                                                                                          lineHeight: lineHeightBodyLargeTablet,
                                                                                          weight: weightBodyDefault,
                                                                                          letterSpacing: letterSpacingBodyLargeTablet)) }

    @objc open var bodyDefaultMedium: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeBodyMediumMobile,
                                                                                           lineHeight: lineHeightBodyMediumMobile,
                                                                                           weight: weightBodyDefault,
                                                                                           letterSpacing: letterSpacingBodyMediumMobile),
                                                                               regular: CT(size: sizeBodyMediumTablet,
                                                                                           lineHeight: lineHeightBodyMediumTablet,
                                                                                           weight: weightBodyDefault,
                                                                                           letterSpacing: letterSpacingBodyMediumTablet)) }

    @objc open var bodyDefaultSmall: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeBodySmallMobile,
                                                                                          lineHeight: lineHeightBodySmallMobile,
                                                                                          weight: weightBodyDefault,
                                                                                          letterSpacing: letterSpacingBodySmallMobile),
                                                                              regular: CT(size: sizeBodySmallTablet,
                                                                                          lineHeight: lineHeightBodySmallTablet,
                                                                                          weight: weightBodyDefault,
                                                                                          letterSpacing: letterSpacingBodySmallTablet)) }

    @objc open var bodyModerateLarge: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeBodyLargeMobile,
                                                                                           lineHeight: lineHeightBodyLargeMobile,
                                                                                           weight: weightBodyModerate,
                                                                                           letterSpacing: letterSpacingBodyLargeMobile),
                                                                               regular: CT(size: sizeBodyLargeTablet,
                                                                                           lineHeight: lineHeightBodyLargeTablet,
                                                                                           weight: weightBodyModerate,
                                                                                           letterSpacing: letterSpacingBodyLargeTablet)) }

    @objc open var bodyModerateMedium: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeBodyMediumMobile,
                                                                                            lineHeight: lineHeightBodyMediumMobile,
                                                                                            weight: weightBodyModerate,
                                                                                            letterSpacing: letterSpacingBodyMediumMobile),
                                                                                regular: CT(size: sizeBodyMediumTablet,
                                                                                            lineHeight: lineHeightBodyMediumTablet,
                                                                                            weight: weightBodyModerate,
                                                                                            letterSpacing: letterSpacingBodyMediumTablet)) }

    @objc open var bodyModerateSmall: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeBodySmallMobile,
                                                                                           lineHeight: lineHeightBodySmallMobile,
                                                                                           weight: weightBodyModerate,
                                                                                           letterSpacing: letterSpacingBodySmallMobile),
                                                                               regular: CT(size: sizeBodySmallTablet,
                                                                                           lineHeight: lineHeightBodySmallTablet,
                                                                                           weight: weightBodyModerate,
                                                                                           letterSpacing: letterSpacingBodySmallTablet)) }

    @objc open var bodyStrongLarge: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeBodyLargeMobile,
                                                                                         lineHeight: lineHeightBodyLargeMobile,
                                                                                         weight: weightBodyStrong,
                                                                                         letterSpacing: letterSpacingBodyLargeMobile),
                                                                             regular: CT(size: sizeBodyLargeTablet,
                                                                                         lineHeight: lineHeightBodyLargeTablet,
                                                                                         weight: weightBodyStrong,
                                                                                         letterSpacing: letterSpacingBodyLargeTablet)) }

    @objc open var bodyStrongMedium: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeBodyMediumMobile,
                                                                                          lineHeight: lineHeightBodyMediumMobile,
                                                                                          weight: weightBodyStrong,
                                                                                          letterSpacing: letterSpacingBodyMediumMobile),
                                                                              regular: CT(size: sizeBodyMediumTablet,
                                                                                          lineHeight: lineHeightBodyMediumTablet,
                                                                                          weight: weightBodyStrong,
                                                                                          letterSpacing: letterSpacingBodyMediumTablet)) }

    @objc open var bodyStrongSmall: MultipleFontCompositeSemanticToken { MCT(compact: CT(size: sizeBodySmallMobile,
                                                                                         lineHeight: lineHeightBodySmallMobile,
                                                                                         weight: weightBodyStrong,
                                                                                         letterSpacing: letterSpacingBodySmallMobile),
                                                                             regular: CT(size: sizeBodySmallTablet,
                                                                                         lineHeight: lineHeightBodySmallTablet,
                                                                                         weight: weightBodyStrong,
                                                                                         letterSpacing: letterSpacingBodySmallTablet)) }

    // MARK: - Semantic tokens - Typography - Composites - Label

    @objc open var labelDefaultXLarge: MultipleFontCompositeSemanticToken { MCT(CT(size: sizeLabelXlarge,
                                                                                   lineHeight: lineHeightLabelXlarge,
                                                                                   weight: weightLabelDefault,
                                                                                   letterSpacing: letterSpacingLabelXlarge)) }

    @objc open var labelDefaultLarge: MultipleFontCompositeSemanticToken { MCT(CT(size: sizeLabelLarge,
                                                                                  lineHeight: lineHeightLabelLarge,
                                                                                  weight: weightLabelDefault,
                                                                                  letterSpacing: letterSpacingLabelLarge)) }

    @objc open var labelDefaultMedium: MultipleFontCompositeSemanticToken { MCT(CT(size: sizeLabelMedium,
                                                                                   lineHeight: lineHeightLabelMedium,
                                                                                   weight: weightLabelDefault,
                                                                                   letterSpacing: letterSpacingLabelMedium)) }

    @objc open var labelDefaultSmall: MultipleFontCompositeSemanticToken { MCT(CT(size: sizeLabelSmall,
                                                                                  lineHeight: lineHeightLabelSmall,
                                                                                  weight: weightLabelDefault,
                                                                                  letterSpacing: letterSpacingLabelSmall)) }

    @objc open var labelModerateXLarge: MultipleFontCompositeSemanticToken { MCT(CT(size: sizeLabelXlarge,
                                                                                    lineHeight: lineHeightLabelXlarge,
                                                                                    weight: weightLabelModerate,
                                                                                    letterSpacing: letterSpacingLabelXlarge)) }

    @objc open var labelModerateLarge: MultipleFontCompositeSemanticToken { MCT(CT(size: sizeLabelLarge,
                                                                                   lineHeight: lineHeightLabelLarge,
                                                                                   weight: weightLabelModerate,
                                                                                   letterSpacing: letterSpacingLabelLarge)) }

    @objc open var labelModerateMedium: MultipleFontCompositeSemanticToken { MCT(CT(size: sizeLabelMedium,
                                                                                    lineHeight: lineHeightLabelMedium,
                                                                                    weight: weightLabelModerate,
                                                                                    letterSpacing: letterSpacingLabelMedium)) }

    @objc open var labelModerateSmall: MultipleFontCompositeSemanticToken { MCT(CT(size: sizeLabelSmall,
                                                                                   lineHeight: lineHeightLabelSmall,
                                                                                   weight: weightLabelModerate,
                                                                                   letterSpacing: letterSpacingLabelSmall)) }

    @objc open var labelStrongXLarge: MultipleFontCompositeSemanticToken { MCT(CT(size: sizeLabelXlarge,
                                                                                  lineHeight: lineHeightLabelXlarge,
                                                                                  weight: weightLabelStrong,
                                                                                  letterSpacing: letterSpacingLabelXlarge)) }

    @objc open var labelStrongLarge: MultipleFontCompositeSemanticToken { MCT(CT(size: sizeLabelLarge,
                                                                                 lineHeight: lineHeightLabelLarge,
                                                                                 weight: weightLabelStrong,
                                                                                 letterSpacing: letterSpacingLabelLarge)) }

    @objc open var labelStrongMedium: MultipleFontCompositeSemanticToken { MCT(CT(size: sizeLabelMedium,
                                                                                  lineHeight: lineHeightLabelMedium,
                                                                                  weight: weightLabelStrong,
                                                                                  letterSpacing: letterSpacingLabelMedium)) }

    @objc open var labelStrongSmall: MultipleFontCompositeSemanticToken { MCT(CT(size: sizeLabelSmall,
                                                                                 lineHeight: lineHeightLabelSmall,
                                                                                 weight: weightLabelStrong,
                                                                                 letterSpacing: letterSpacingLabelSmall)) }

    // MARK: - Semantic tokens - Typography - Composites - Code

    @objc open var codeMedium: MultipleFontCompositeSemanticToken { MCT(CT(size: sizeCodeMedium,
                                                                           lineHeight: lineHeightCodeMedium,
                                                                           weight: weightCode,
                                                                           letterSpacing: letterSpacingCodeMedium)) }
}

// swiftlint:enable line_length
