//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensRaw
import OUDSTokensSemantic

// 🧬 Tokens version: 2.1.0 (Orange brand)
// 🤖 Generated by Tokenator

extension OrangeThemeGridSemanticTokensProvider: GridSemanticTokens {
    /// Has for value token GridRawTokens.minWidthExtraCompact
    @objc open var gridExtraCompactMinWidth: GridSemanticToken { GridRawTokens.minWidthExtraCompact }
    /// Has for value token GridRawTokens.maxWidthExtraCompact
    @objc open var gridExtraCompactMaxWidth: GridSemanticToken { GridRawTokens.maxWidthExtraCompact }
    /// Has for value token GridRawTokens.margin100
    @objc open var gridExtraCompactMargin: GridSemanticToken { GridRawTokens.margin100 }
    /// Has for value token GridRawTokens.columnGap100
    @objc open var gridExtraCompactColumnGap: GridSemanticToken { GridRawTokens.columnGap100 }
    /// Has for value token GridRawTokens.minWidthCompact
    @objc open var gridCompactMinWidth: GridSemanticToken { GridRawTokens.minWidthCompact }
    /// Has for value token GridRawTokens.maxWidthCompact
    @objc open var gridCompactMaxWidth: GridSemanticToken { GridRawTokens.maxWidthCompact }
    /// Has for value token GridRawTokens.margin300
    @objc open var gridCompactMargin: GridSemanticToken { GridRawTokens.margin300 }
    /// Has for value token GridRawTokens.columnGap100
    @objc open var gridCompactColumnGap: GridSemanticToken { GridRawTokens.columnGap100 }
    /// Has for value token GridRawTokens.minWidthRegular
    @objc open var gridRegularMinWidth: GridSemanticToken { GridRawTokens.minWidthRegular }
    /// Has for value token GridRawTokens.maxWidthRegular
    @objc open var gridRegularMaxWidth: GridSemanticToken { GridRawTokens.maxWidthRegular }
    /// Has for value token GridRawTokens.margin500
    @objc open var gridRegularMargin: GridSemanticToken { GridRawTokens.margin500 }
    /// Has for value token GridRawTokens.columnGap400
    @objc open var gridRegularColumnGap: GridSemanticToken { GridRawTokens.columnGap400 }
}
