//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

/// Defines provider objects for space semantic tokens (i.e. in the end `DimensionRawTokens`).
/// These values can be overriden inside ``OrangeThemeSpaceSemanticTokensProvider`` subclasses
/// (in extensions or not, in the same module or not) thanks to the `@objc open` combination.
extension OrangeThemeSpaceSemanticTokensProvider: SpaceMultipleSemanticTokens {

    // MARK: Semantic token - Spacing - Layout fluid

    @objc open var spaceScaledNone: MultipleSpaceSemanticTokens { MultipleSpaceSemanticTokens(compact: spaceScaledNoneMobile, regular: spaceScaledNoneTablet) }
    @objc open var spaceScaled3xs: MultipleSpaceSemanticTokens { MultipleSpaceSemanticTokens(compact: spaceScaled3xsMobile, regular: spaceScaled3xsTablet) }
    @objc open var spaceScaled2xs: MultipleSpaceSemanticTokens { MultipleSpaceSemanticTokens(compact: spaceScaled2xsMobile, regular: spaceScaled2xsTablet) }
    @objc open var spaceScaledXs: MultipleSpaceSemanticTokens { MultipleSpaceSemanticTokens(compact: spaceScaledXsMobile, regular: spaceScaledXsTablet) }
    @objc open var spaceScaledSm: MultipleSpaceSemanticTokens { MultipleSpaceSemanticTokens(compact: spaceScaledSmMobile, regular: spaceScaledSmTablet) }
    @objc open var spaceScaledMd: MultipleSpaceSemanticTokens { MultipleSpaceSemanticTokens(compact: spaceScaledMdMobile, regular: spaceScaledMdTablet) }
    @objc open var spaceScaledLg: MultipleSpaceSemanticTokens { MultipleSpaceSemanticTokens(compact: spaceScaledLgMobile, regular: spaceScaledLgTablet) }
    @objc open var spaceScaledXl: MultipleSpaceSemanticTokens { MultipleSpaceSemanticTokens(compact: spaceScaledXlMobile, regular: spaceScaledXlTablet) }
    @objc open var spaceScaled2xl: MultipleSpaceSemanticTokens { MultipleSpaceSemanticTokens(compact: spaceScaled2xlMobile, regular: spaceScaled2xlTablet) }
    @objc open var spaceScaled3xl: MultipleSpaceSemanticTokens { MultipleSpaceSemanticTokens(compact: spaceScaled3xlMobile, regular: spaceScaled3xlTablet) }
}
