//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable line_length

/// Defines provider objects for font semantic tokens but "multiple", i.e. tokens with values depending to size classes or color schemes.
/// These values can be overriden inside `OrangeThemeFontSemanticTokensProvider` subclasses (in extensions or not, in the same module or not) thanks to the `@objc open` combination.
extension OrangeThemeFontSemanticTokensProvider: FontMultipleSemanticTokens {

    // MARK: - Semantic token - Typography - Font - Size

    @objc open var sizeDisplayLarge: MultipleFontSizeSemanticTokens { MultipleFontSizeSemanticTokens(compact: sizeDisplayLargeMobile, regular: sizeDisplayLargeTablet) }
    @objc open var sizeDisplayMedium: MultipleFontSizeSemanticTokens { MultipleFontSizeSemanticTokens(compact: sizeDisplayMediumMobile, regular: sizeDisplayMediumTablet) }
    @objc open var sizeDisplaySmall: MultipleFontSizeSemanticTokens { MultipleFontSizeSemanticTokens(compact: sizeDisplaySmallMobile, regular: sizeDisplaySmallTablet) }
    @objc open var sizeHeadingXlarge: MultipleFontSizeSemanticTokens { MultipleFontSizeSemanticTokens(compact: sizeHeadingXlargeMobile, regular: sizeHeadingXlargeTablet) }
    @objc open var sizeHeadingLarge: MultipleFontSizeSemanticTokens { MultipleFontSizeSemanticTokens(compact: sizeHeadingLargeMobile, regular: sizeHeadingLargeTablet) }
    @objc open var sizeHeadingMedium: MultipleFontSizeSemanticTokens { MultipleFontSizeSemanticTokens(compact: sizeHeadingMediumMobile, regular: sizeHeadingMediumTablet) }
    @objc open var sizeHeadingSmall: MultipleFontSizeSemanticTokens { MultipleFontSizeSemanticTokens(compact: sizeHeadingSmallMobile, regular: sizeHeadingSmallTablet) }
    @objc open var sizeBodyLarge: MultipleFontSizeSemanticTokens { MultipleFontSizeSemanticTokens(compact: sizeBodyLargeMobile, regular: sizeBodyLargeTablet) }
    @objc open var sizeBodyMedium: MultipleFontSizeSemanticTokens { MultipleFontSizeSemanticTokens(compact: sizeBodyMediumMobile, regular: sizeBodyMediumTablet) }
    @objc open var sizeBodySmall: MultipleFontSizeSemanticTokens { MultipleFontSizeSemanticTokens(compact: sizeBodySmallMobile, regular: sizeBodySmallTablet) }

    // MARK: - Semantic token - Typography - Font - Line height

    @objc open var lineHeightDisplayLarge: MultipleFontLineHeightSemanticTokens { MultipleFontLineHeightSemanticTokens(compact: lineHeightDisplayLargeMobile, regular: lineHeightDisplayLargeTablet) }
    @objc open var lineHeightDisplayMedium: MultipleFontLineHeightSemanticTokens { MultipleFontLineHeightSemanticTokens(compact: lineHeightDisplayMediumMobile, regular: lineHeightDisplayMediumTablet) }
    @objc open var lineHeightDisplaySmall: MultipleFontLineHeightSemanticTokens { MultipleFontLineHeightSemanticTokens(compact: lineHeightDisplaySmallMobile, regular: lineHeightDisplaySmallTablet) }
    @objc open var lineHeightHeadingXlarge: MultipleFontLineHeightSemanticTokens { MultipleFontLineHeightSemanticTokens(compact: lineHeightHeadingXlargeMobile, regular: lineHeightHeadingXlargeTablet) }
    @objc open var lineHeightHeadingLarge: MultipleFontLineHeightSemanticTokens { MultipleFontLineHeightSemanticTokens(compact: lineHeightHeadingLargeMobile, regular: lineHeightHeadingLargeTablet) }
    @objc open var lineHeightHeadingMedium: MultipleFontLineHeightSemanticTokens { MultipleFontLineHeightSemanticTokens(compact: lineHeightHeadingMediumMobile, regular: lineHeightHeadingMediumTablet) }
    @objc open var lineHeightHeadingSmall: MultipleFontLineHeightSemanticTokens { MultipleFontLineHeightSemanticTokens(compact: lineHeightHeadingSmallMobile, regular: lineHeightHeadingSmallTablet) }
    @objc open var lineHeightBodyLarge: MultipleFontLineHeightSemanticTokens { MultipleFontLineHeightSemanticTokens(compact: lineHeightBodyLargeMobile, regular: lineHeightBodyLargeTablet) }
    @objc open var lineHeightBodyMedium: MultipleFontLineHeightSemanticTokens { MultipleFontLineHeightSemanticTokens(compact: lineHeightBodyMediumMobile, regular: lineHeightBodyMediumTablet) }
    @objc open var lineHeightBodySmall: MultipleFontLineHeightSemanticTokens { MultipleFontLineHeightSemanticTokens(compact: lineHeightBodySmallMobile, regular: lineHeightBodySmallTablet) }

    // MARK: - Semantic token - Typography - Font - Letter spacing

    @objc open var letterSpacingDisplayLarge: MultipleFontLetterSpacingSemanticTokens { MultipleFontLetterSpacingSemanticTokens(compact: letterSpacingDisplayLargeMobile, regular: letterSpacingDisplayLargeTablet) }
    @objc open var letterSpacingDisplayMedium: MultipleFontLetterSpacingSemanticTokens { MultipleFontLetterSpacingSemanticTokens(compact: letterSpacingDisplayMediumMobile, regular: letterSpacingDisplayMediumTablet) }
    @objc open var letterSpacingDisplaySmall: MultipleFontLetterSpacingSemanticTokens { MultipleFontLetterSpacingSemanticTokens(compact: letterSpacingDisplaySmallMobile, regular: letterSpacingDisplaySmallTablet) }
    @objc open var letterSpacingHeadingXlarge: MultipleFontLetterSpacingSemanticTokens { MultipleFontLetterSpacingSemanticTokens(compact: letterSpacingHeadingXlargeMobile, regular: letterSpacingHeadingXlargeTablet) }
    @objc open var letterSpacingHeadingLarge: MultipleFontLetterSpacingSemanticTokens { MultipleFontLetterSpacingSemanticTokens(compact: letterSpacingHeadingLargeMobile, regular: letterSpacingHeadingLargeTablet) }
    @objc open var letterSpacingHeadingMedium: MultipleFontLetterSpacingSemanticTokens { MultipleFontLetterSpacingSemanticTokens(compact: letterSpacingHeadingMediumMobile, regular: letterSpacingHeadingMediumTablet) }
    @objc open var letterSpacingHeadingSmall: MultipleFontLetterSpacingSemanticTokens { MultipleFontLetterSpacingSemanticTokens(compact: letterSpacingHeadingSmallMobile, regular: letterSpacingHeadingSmallTablet) }
    @objc open var letterSpacingBodyLarge: MultipleFontLetterSpacingSemanticTokens { MultipleFontLetterSpacingSemanticTokens(compact: letterSpacingBodyLargeMobile, regular: letterSpacingBodyLargeTablet) }
    @objc open var letterSpacingBodyMedium: MultipleFontLetterSpacingSemanticTokens { MultipleFontLetterSpacingSemanticTokens(compact: letterSpacingBodyMediumMobile, regular: letterSpacingBodyMediumTablet) }
    @objc open var letterSpacingBodySmall: MultipleFontLetterSpacingSemanticTokens { MultipleFontLetterSpacingSemanticTokens(compact: letterSpacingBodySmallMobile, regular: letterSpacingBodySmallTablet) }
}

// swiftlint:enable line_length
