//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensRaw
import OUDSTokensSemantic
import SwiftUI

// [File not generated by the tokenator]
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable line_length

/// Defines provider objects for `ColorModeSemanticTokens` so as to pack them as light and dark mode colors.
/// These values can be overriden inside `OrangeThemeColorModeSemanticTokensProvider` subclasses (in extensions or not, in the same module or not) thanks to the `@objc open` combination.
extension OrangeThemeColorModeSemanticTokensProvider: ColorModeMultipleSemanticTokens {

    // MARK: - Multiple tokens

    @objc open var modeOnBrandPrimary: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnBrandPrimaryLight, dark: modeOnBrandPrimaryDark) }

    @objc open var modeOnBrandSecondary: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnBrandSecondaryLight, dark: modeOnBrandSecondaryDark) }

    @objc open var modeOnBrandTertiary: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnBrandTertiaryLight, dark: modeOnBrandTertiaryDark) }

    @objc open var modeOnStatusAccentEmphasized: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnStatusAccentEmphasizedLight, dark: modeOnStatusAccentEmphasizedDark) }

    @objc open var modeOnStatusAccentMuted: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnStatusAccentMutedLight, dark: modeOnStatusAccentMutedDark) }

    @objc open var modeOnStatusInfoEmphasized: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnStatusInfoEmphasizedLight, dark: modeOnStatusInfoEmphasizedDark) }

    @objc open var modeOnStatusInfoMuted: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnStatusInfoMutedLight, dark: modeOnStatusInfoMutedDark) }

    @objc open var modeOnStatusNegativeEmphasized: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnStatusNegativeEmphasizedLight, dark: modeOnStatusNegativeEmphasizedDark) }

    @objc open var modeOnStatusNegativeMuted: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnStatusNegativeMutedLight, dark: modeOnStatusNegativeMutedDark) }

    @objc open var modeOnStatusNeutralEmphasized: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnStatusNeutralEmphasizedLight, dark: modeOnStatusNeutralEmphasizedDark) }

    @objc open var modeOnStatusNeutralMuted: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnStatusNeutralMutedLight, dark: modeOnStatusNeutralMutedDark) }

    @objc open var modeOnStatusPositiveEmphasized: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnStatusPositiveEmphasizedLight, dark: modeOnStatusPositiveEmphasizedDark) }

    @objc open var modeOnStatusPositiveMuted: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnStatusPositiveMutedLight, dark: modeOnStatusPositiveMutedDark) }

    @objc open var modeOnStatusWarningEmphasized: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnStatusWarningEmphasizedLight, dark: modeOnStatusWarningEmphasizedDark) }

    @objc open var modeOnStatusWarningMuted: MultipleColorModeSemanticTokens { MultipleColorModeSemanticTokens(light: modeOnStatusWarningMutedLight, dark: modeOnStatusWarningMutedDark) }

    // MARK: - Additional rules

    /// Depending to the given `mode`, should return the SwfitUI `ColorScheme` to consider.
    /// For Orange theme, the rules are:
    /// - if light version is dark mode and dark version is light mode, reverse the color scheme
    /// - if light and dark versions are light mode, return light color scheme
    /// - if light and dark versions are dark mode, return dark color scheme
    /// - otherwise return current color scheme
    ///
    /// - Parameters:
    ///    - mode: The color mode token to test
    ///    - current: The current color scheme
    /// - Returns: The color scheme to consider depending to the theme rules
    public func useColorScheme(for mode: MultipleColorModeSemanticTokens,
                               _ current: ColorScheme) -> ColorScheme {

        let lightColorScheme = ColorModeRawTokens.colorScheme(for: mode.light)
        let darkColorScheme = ColorModeRawTokens.colorScheme(for: mode.dark)

        // Reverse the color scheme to apply
        if lightColorScheme == .dark && darkColorScheme == .light {
            return (current == .light ? .dark : .light)
        }

        // Force light
        if lightColorScheme == .light && darkColorScheme == .light {
            return .light
        }

        // Force dark
        if lightColorScheme == .dark && darkColorScheme == .dark {
            return .dark
        }

        // Otherwise use device configuration
        return current
    }

    /// Depending to the given `mode`, should return a flag saying if monochrome mode must be considered.
    /// For Orange theme, the rule is :
    /// - if both light and dark versions are monochrome, returns true, otherwise false
    ///
    /// - Parameter mode: The color mode token to test
    /// - Returns: The flag for monochrome mode depending to the theme rules
    public func isMonochrome(mode: MultipleColorModeSemanticTokens) -> Bool {
        let lightIsMonochrome = ColorModeRawTokens.isMonochrome(mode: mode.light)
        let darkIsMonochrome = ColorModeRawTokens.isMonochrome(mode: mode.dark)
        return lightIsMonochrome == true && darkIsMonochrome == true
    }

    // swiftlint:disable cyclomatic_complexity
    /// Returns the colors semantic token depending to the given color mode
    /// - Parameter mode: The color mpde token to use
    /// - Returns: The colors to apply
    public func toColor(from mode: MultipleColorModeSemanticTokens) -> MultipleColorSemanticTokens {
        if mode == modeOnBrandPrimary { return colors.colorSurfaceBrandPrimary }
        if mode == modeOnBrandSecondary { return colors.colorSurfaceBrandPrimary } // TODO: #521 - Not sure of this implementation
        if mode == modeOnBrandTertiary { return colors.colorSurfaceBrandPrimary } // TODO: #521 - Not sure of this implementation
        if mode == modeOnStatusAccentEmphasized { return colors.colorSurfaceStatusAccentEmphasized }
        if mode == modeOnStatusAccentMuted { return colors.colorSurfaceStatusAccentMuted }
        if mode == modeOnStatusInfoEmphasized { return colors.colorSurfaceStatusInfoEmphasized }
        if mode == modeOnStatusInfoMuted { return colors.colorSurfaceStatusInfoMuted }
        if mode == modeOnStatusNeutralEmphasized { return colors.colorSurfaceStatusNegativeEmphasized }
        if mode == modeOnStatusNegativeMuted { return colors.colorSurfaceStatusNegativeMuted }
        if mode == modeOnStatusNeutralEmphasized { return colors.colorSurfaceStatusNeutralEmphasized }
        if mode == modeOnStatusNeutralMuted { return colors.colorSurfaceStatusNeutralMuted }
        if mode == modeOnStatusPositiveEmphasized { return colors.colorSurfaceStatusPositiveEmphasized }
        if mode == modeOnStatusPositiveMuted { return colors.colorSurfaceStatusPositiveMuted }
        if mode == modeOnStatusWarningEmphasized { return colors.colorSurfaceStatusWarningEmphasized }
        if mode == modeOnStatusWarningMuted { return colors.colorSurfaceStatusWarningMuted }
        return colors.colorSurfaceBrandPrimary // TODO: #521 - Which default behavior?
    }
    // swiftlint:enable cyclomatic_complexity
}

// swiftlint:enable line_length
