//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable line_length

/// Defines provider objects for `ColorSemanticTokens` so as to pack them as light and dark modes colors.
/// These values can be overriden inside `OrangeThemeColorSemanticTokensProvider` subclasses (in extensions or not, in the same module or not) thanks to the `@objc open` combination.
/// Some tokens do not have values assigned in the design system, and must be overriden.
/// Some tokens must be overriden in `OrangeTheme` side because they rely on Orange brand colors.
/// Helps to expose color semantic tokens with two values to use depending to the color scheme (*Figma* cannot manage such tokens and generate them).
extension OrangeThemeColorSemanticTokensProvider: ColorMultipleSemanticTokens {

    // MARK: - Color - Opacity

    @objc open var opacityLowest: MultipleColorSemanticToken { MultipleColorSemanticToken(light: opacityLowestLight, dark: opacityLowestDark) }

    @objc open var opacityLower: MultipleColorSemanticToken { MultipleColorSemanticToken(light: opacityLowerLight, dark: opacityLowerDark) }

    @objc open var opacityTransparent: MultipleColorSemanticToken { MultipleColorSemanticToken(light: opacityTransparentLight, dark: opacityTransparentDark) }

    // MARK: - Color - Action

    @objc open var actionDisabled: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionDisabledLight, dark: actionDisabledDark) }

    @objc open var actionEnabled: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionEnabledLight, dark: actionEnabledDark) }

    @objc open var actionFocus: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionFocusLight, dark: actionFocusDark) }

    @objc open var actionHighlighted: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionHighlightedLight, dark: actionHighlightedDark) }

    @objc open var actionHover: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionHoverLight, dark: actionHoverDark) }

    @objc open var actionLoading: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionLoadingLight, dark: actionLoadingDark) }

    @objc open var actionNegativeEnabled: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionNegativeEnabledLight, dark: actionNegativeEnabledDark) }

    @objc open var actionNegativeFocus: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionNegativeFocusLight, dark: actionNegativeFocusDark) }

    @objc open var actionNegativeHover: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionNegativeHoverLight, dark: actionNegativeHoverDark) }

    @objc open var actionNegativeLoading: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionNegativeLoadingLight, dark: actionNegativeLoadingDark) }

    @objc open var actionNegativePressed: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionNegativePressedLight, dark: actionNegativePressedDark) }

    @objc open var actionPressed: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionPressedLight, dark: actionPressedDark) }

    @objc open var actionSelected: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionSelectedLight, dark: actionSelectedDark) }

    @objc open var actionSupportEnabled: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionSupportEnabledLight, dark: actionSupportEnabledDark) }

    @objc open var actionSupportDisabled: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionSupportDisabledLight, dark: actionSupportDisabledDark) }

    @objc open var actionSupportFocus: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionSupportFocusLight, dark: actionSupportFocusDark) }

    @objc open var actionSupportHover: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionSupportHoverLight, dark: actionSupportHoverDark) }

    @objc open var actionSupportLoading: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionSupportLoadingLight, dark: actionSupportLoadingDark) }

    @objc open var actionSupportPressed: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionSupportPressedLight, dark: actionSupportPressedDark) }

    @objc open var actionVisited: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionVisitedLight, dark: actionVisitedDark) }

    @objc open var actionReadOnlyPrimary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionReadOnlyPrimaryLight, dark: actionReadOnlyPrimaryDark) }

    @objc open var actionReadOnlySecondary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionReadOnlySecondaryLight, dark: actionReadOnlySecondaryDark) }

    @objc open var actionAccent: MultipleColorSemanticToken { MultipleColorSemanticToken(light: actionAccentLight, dark: actionAccentDark) }

    // MARK: - Color - Background

    @objc open var bgPrimary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: bgPrimaryLight, dark: bgPrimaryDark) }

    @objc open var bgSecondary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: bgSecondaryLight, dark: bgSecondaryDark) }

    @objc open var bgTertiary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: bgTertiaryLight, dark: bgTertiaryDark) }

    @objc open var bgInverseLow: MultipleColorSemanticToken { MultipleColorSemanticToken(light: bgInverseLowLight, dark: bgInverseLowDark) }

    @objc open var bgInverseHigh: MultipleColorSemanticToken { MultipleColorSemanticToken(light: bgInverseHighLight, dark: bgInverseHighDark) }

    // MARK: - Color - Border

    @objc open var borderBrandPrimary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderBrandPrimaryLight, dark: borderBrandPrimaryDark) }

    @objc open var borderBrandSecondary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderBrandSecondaryLight, dark: borderBrandSecondaryDark) }

    @objc open var borderBrandTertiary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderBrandTertiaryLight, dark: borderBrandTertiaryDark) }

    @objc open var borderDefault: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderDefaultLight, dark: borderDefaultDark) }

    @objc open var borderEmphasized: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderEmphasizedLight, dark: borderEmphasizedDark) }

    @objc open var borderFocus: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderFocusLight, dark: borderFocusDark) }

    @objc open var borderFocusInset: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderFocusInsetLight, dark: borderFocusInsetDark) }

    @objc open var borderMuted: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderMutedLight, dark: borderMutedDark) }

    @objc open var borderOnBrandPrimary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderOnBrandPrimaryLight, dark: borderOnBrandPrimaryDark) }

    @objc open var borderOnBrandSecondary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderOnBrandSecondaryLight, dark: borderOnBrandSecondaryDark) }

    @objc open var borderOnBrandTertiary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderOnBrandTertiaryLight, dark: borderOnBrandTertiaryDark) }

    @objc open var borderMinimal: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderMinimalLight, dark: borderMinimalDark) }

    @objc open var borderStatusPositive: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderStatusPositiveLight, dark: borderStatusPositiveDark) }

    @objc open var borderStatusInfo: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderStatusInfoLight, dark: borderStatusInfoDark) }

    @objc open var borderStatusWarning: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderStatusWarningLight, dark: borderStatusWarningDark) }

    @objc open var borderStatusNegative: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderStatusNegativeLight, dark: borderStatusNegativeDark) }

    @objc open var borderStatusAccent: MultipleColorSemanticToken { MultipleColorSemanticToken(light: borderStatusAccentLight, dark: borderStatusAccentDark) }

    // MARK: - Color - Content

    @objc open var contentBrandPrimary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentBrandPrimaryLight, dark: contentBrandPrimaryDark) }

    @objc open var contentBrandSecondary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentBrandSecondaryLight, dark: contentBrandSecondaryDark) }

    @objc open var contentBrandTertiary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentBrandTertiaryLight, dark: contentBrandTertiaryDark) }

    @objc open var contentDefault: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentDefaultLight, dark: contentDefaultDark) }

    @objc open var contentDisabled: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentDisabledLight, dark: contentDisabledDark) }

    @objc open var contentMuted: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentMutedLight, dark: contentMutedDark) }

    @objc open var contentOnActionSelected: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnActionSelectedLight, dark: contentOnActionSelectedDark) }

    @objc open var contentOnActionDisabled: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnActionDisabledLight, dark: contentOnActionDisabledDark) }

    @objc open var contentOnActionEnabled: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnActionEnabledLight, dark: contentOnActionEnabledDark) }

    @objc open var contentOnActionFocus: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnActionFocusLight, dark: contentOnActionFocusDark) }

    @objc open var contentOnActionHighlighted: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnActionHighlightedLight, dark: contentOnActionHighlightedDark) }

    @objc open var contentOnActionHover: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnActionHoverLight, dark: contentOnActionHoverDark) }

    @objc open var contentOnActionLoading: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnActionLoadingLight, dark: contentOnActionLoadingDark) }

    @objc open var contentOnActionPressed: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnActionPressedLight, dark: contentOnActionPressedDark) }

    @objc open var contentOnBrandPrimary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnBrandPrimaryLight, dark: contentOnBrandPrimaryDark) }

    @objc open var contentOnBrandSecondary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnBrandSecondaryLight, dark: contentOnBrandSecondaryDark) }

    @objc open var contentOnBrandTertiary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnBrandTertiaryLight, dark: contentOnBrandTertiaryDark) }

    @objc open var contentOnStatusPositiveMuted: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnStatusPositiveMutedLight, dark: contentOnStatusPositiveMutedDark) }

    @objc open var contentOnStatusPositiveEmphasized: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnStatusPositiveEmphasizedLight, dark: contentOnStatusPositiveEmphasizedDark) }

    @objc open var contentOnStatusWarningMuted: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnStatusWarningMutedLight, dark: contentOnStatusWarningMutedDark) }

    @objc open var contentOnStatusWarningEmphasized: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnStatusWarningEmphasizedLight, dark: contentOnStatusWarningEmphasizedDark) }

    @objc open var contentInverse: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentInverseLight, dark: contentInverseDark) }

    @objc open var contentOnStatusNegativeMuted: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnStatusNegativeMutedLight, dark: contentOnStatusNegativeMutedDark) }

    @objc open var contentOnStatusNegativeEmphasized: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnStatusNegativeEmphasizedLight, dark: contentOnStatusNegativeEmphasizedDark) }

    @objc open var contentOnStatusInfoMuted: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnStatusInfoMutedLight, dark: contentOnStatusInfoMutedDark) }

    @objc open var contentOnStatusInfoEmphasized: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnStatusInfoEmphasizedLight, dark: contentOnStatusInfoEmphasizedDark) }

    @objc open var contentOnStatusAccentMuted: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnStatusAccentMutedLight, dark: contentOnStatusAccentMutedDark) }

    @objc open var contentOnStatusAccentEmphasized: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentOnStatusAccentEmphasizedLight, dark: contentOnStatusAccentEmphasizedDark) }

    @objc open var contentStatusAccent: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentStatusAccentLight, dark: contentStatusAccentDark) }

    @objc open var contentStatusInfo: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentStatusInfoLight, dark: contentStatusInfoDark) }

    @objc open var contentStatusNegative: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentStatusNegativeLight, dark: contentStatusNegativeDark) }

    @objc open var contentStatusPositive: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentStatusPositiveLight, dark: contentStatusPositiveDark) }

    @objc open var contentStatusWarning: MultipleColorSemanticToken { MultipleColorSemanticToken(light: contentStatusWarningLight, dark: contentStatusWarningDark) }

    // MARK: - Color - Overlay

    @objc open var overlayDropdown: MultipleColorSemanticToken { MultipleColorSemanticToken(light: overlayDropdownLight, dark: overlayDropdownDark) }

    @objc open var overlayTooltip: MultipleColorSemanticToken { MultipleColorSemanticToken(light: overlayTooltipLight, dark: overlayTooltipDark) }

    @objc open var overlayDrag: MultipleColorSemanticToken { MultipleColorSemanticToken(light: overlayDragLight, dark: overlayDragDark) }

    @objc open var overlayModal: MultipleColorSemanticToken { MultipleColorSemanticToken(light: overlayModalLight, dark: overlayModalDark) }

    // MARK: - Color - Surface

    @objc open var surfaceBrandPrimary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceBrandPrimaryLight, dark: surfaceBrandPrimaryDark) }

    @objc open var surfaceBrandSecondary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceBrandSecondaryLight, dark: surfaceBrandSecondaryDark) }

    @objc open var surfaceBrandTertiary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceBrandTertiaryLight, dark: surfaceBrandTertiaryDark) }

    @objc open var surfaceStatusAccentEmphasized: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceStatusAccentEmphasizedLight, dark: surfaceStatusAccentEmphasizedDark) }

    @objc open var surfaceStatusAccentMuted: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceStatusAccentMutedLight, dark: surfaceStatusAccentMutedDark) }

    @objc open var surfaceStatusInfoEmphasized: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceStatusInfoEmphasizedLight, dark: surfaceStatusInfoEmphasizedDark) }

    @objc open var surfaceStatusInfoMuted: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceStatusInfoMutedLight, dark: surfaceStatusInfoMutedDark) }

    @objc open var surfaceStatusNegativeEmphasized: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceStatusNegativeEmphasizedLight, dark: surfaceStatusNegativeEmphasizedDark) }

    @objc open var surfaceStatusNegativeMuted: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceStatusNegativeMutedLight, dark: surfaceStatusNegativeMutedDark) }

    @objc open var surfaceInverseHigh: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceInverseHighLight, dark: surfaceInverseHighDark) }

    @objc open var surfaceInverseLow: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceInverseLowLight, dark: surfaceInverseLowDark) }

    @objc open var surfacePrimary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfacePrimaryLight, dark: surfacePrimaryDark) }

    @objc open var surfaceSecondary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceSecondaryLight, dark: surfaceSecondaryDark) }

    @objc open var surfaceTertiary: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceTertiaryLight, dark: surfaceTertiaryDark) }

    @objc open var surfaceStatusPositiveEmphasized: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceStatusPositiveEmphasizedLight, dark: surfaceStatusPositiveEmphasizedDark) }

    @objc open var surfaceStatusPositiveMuted: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceStatusPositiveMutedLight, dark: surfaceStatusPositiveMutedDark) }

    @objc open var surfaceStatusWarningEmphasized: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceStatusWarningEmphasizedLight, dark: surfaceStatusWarningEmphasizedDark) }

    @objc open var surfaceStatusWarningMuted: MultipleColorSemanticToken { MultipleColorSemanticToken(light: surfaceStatusWarningMutedLight, dark: surfaceStatusWarningMutedDark) }
}

// swiftlint:enable line_length
