#
# Software Name: Orange Unified Design System
# SPDX-FileCopyrightText: Copyright (c) Orange SA
# SPDX-License-Identifier: MIT
#
# This software is distributed under the MIT license,
# the text of which is available at https://opensource.org/license/MIT/
# or see the "LICENSE" file for more details.
#
# Authors: See CONTRIBUTORS.txt
# Software description: A SwiftUI components library with code examples for Orange Unified Design System
#


# Project configuration
# ---------------------

#OUDS_WORKSPACE = "DesignToolbox.xcworkspace"
#OUDS_PROJECT = "DesignToolbox.xcodeproj"
#OUDS_SCHEME = "DesignToolbox"
#OUDS_TARGET = "DesignToolbox"

# Devices configuration
# ---------------------

#OUDS_SNAPSHOTS_TEST_DEVICE = "iPhone 16 Pro (18.0)"

# Lanes
# ------

default_platform(:ios)

platform :ios do

    before_all do |lane, options|
        xcodes(
            version: '16.3',
            select_for_current_build_only: true,
        )
    end

    # ------------------------------------------------------------
    # RUN PERIPHERY FOR DEAD CODE ANALYSIS
    # ------------------------------------------------------------
    desc "RUN PERIPHERY FOR DEAD CODE ANALYSIS"
    lane :check_dead_code do
        puts "👉 Check dead code with Periphery"
        # Command must run at root where Package.swift is
        sh "cd .. && periphery scan --relative-results --format xcode"
    end

    # ------------------------------------------------------------
    # RUN SWIFT FORMAT TO FORMAT SOURCES
    # ------------------------------------------------------------
    desc "RUN SWIFT FORMAT TO FORMAT SOURCES"
    lane :format do
        puts "👉 Run Swift Format to format sources"
        sh "cd .. && swiftformat ."
    end
end