//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensSemantic

// 🧬 Tokens version: 2.1.0 (Orange brand)
// 🤖 Generated by Tokenator

extension OrangeThemeChipComponentTokensProvider: ChipComponentTokens {
    /// Has for value token colors.colorSurfaceInverseHigh
    @objc open var chipBadgeColorBg: MultipleColorSemanticTokens { colors.colorSurfaceInverseHigh }
    /// Has for value token colors.colorContentInverse
    @objc open var chipBadgeColorContent: MultipleColorSemanticTokens { colors.colorContentInverse }
    /// Has for value token colors.opacityTransparent
    @objc open var chipColorBgSelectedEnabled: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent
    @objc open var chipColorBgSelectedHover: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent
    @objc open var chipColorBgSelectedPressed: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent
    @objc open var chipColorBgSelectedDisabled: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent
    @objc open var chipColorBgSelectedFocus: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent
    @objc open var chipColorBgUnselectedEnabled: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent
    @objc open var chipColorBgUnselectedHover: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent
    @objc open var chipColorBgUnselectedPressed: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent
    @objc open var chipColorBgUnselectedDisabled: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.opacityTransparent
    @objc open var chipColorBgUnselectedFocus: MultipleColorSemanticTokens { colors.opacityTransparent }
    /// Has for value token colors.colorActionSelected
    @objc open var chipColorContentSelectedTickEnabled: MultipleColorSemanticTokens { colors.colorActionSelected }
    /// Has for value token colors.colorActionEnabled
    @objc open var chipColorContentSelectedEnabled: MultipleColorSemanticTokens { colors.colorActionEnabled }
    /// Has for value token colors.colorActionHover
    @objc open var chipColorContentSelectedHover: MultipleColorSemanticTokens { colors.colorActionHover }
    /// Has for value token colors.colorActionPressed
    @objc open var chipColorContentSelectedPressed: MultipleColorSemanticTokens { colors.colorActionPressed }
    /// Has for value token colors.colorActionDisabled
    @objc open var chipColorContentSelectedDisabled: MultipleColorSemanticTokens { colors.colorActionDisabled }
    /// Has for value token colors.colorActionFocus
    @objc open var chipColorContentSelectedFocus: MultipleColorSemanticTokens { colors.colorActionFocus }
    /// Has for value token colors.colorActionEnabled
    @objc open var chipColorContentUnselectedEnabled: MultipleColorSemanticTokens { colors.colorActionEnabled }
    /// Has for value token colors.colorActionHover
    @objc open var chipColorContentUnselectedHover: MultipleColorSemanticTokens { colors.colorActionHover }
    /// Has for value token colors.colorActionPressed
    @objc open var chipColorContentUnselectedPressed: MultipleColorSemanticTokens { colors.colorActionPressed }
    /// Has for value token colors.colorActionDisabled
    @objc open var chipColorContentUnselectedDisabled: MultipleColorSemanticTokens { colors.colorActionDisabled }
    /// Has for value token colors.colorActionFocus
    @objc open var chipColorContentUnselectedFocus: MultipleColorSemanticTokens { colors.colorActionFocus }
    /// Has for value token colors.colorActionSelected
    @objc open var chipColorBorderSelectedEnabled: MultipleColorSemanticTokens { colors.colorActionSelected }
    /// Has for value token colors.colorActionHover
    @objc open var chipColorBorderSelectedHover: MultipleColorSemanticTokens { colors.colorActionHover }
    /// Has for value token colors.colorActionPressed
    @objc open var chipColorBorderSelectedPressed: MultipleColorSemanticTokens { colors.colorActionPressed }
    /// Has for value token colors.colorActionDisabled
    @objc open var chipColorBorderSelectedDisabled: MultipleColorSemanticTokens { colors.colorActionDisabled }
    /// Has for value token colors.colorActionFocus
    @objc open var chipColorBorderSelectedFocus: MultipleColorSemanticTokens { colors.colorActionFocus }
    /// Has for value token colors.colorBorderDefault
    @objc open var chipColorBorderUnselectedEnabled: MultipleColorSemanticTokens { colors.colorBorderDefault }
    /// Has for value token colors.colorActionHover
    @objc open var chipColorBorderUnselectedHover: MultipleColorSemanticTokens { colors.colorActionHover }
    /// Has for value token colors.colorActionPressed
    @objc open var chipColorBorderUnselectedPressed: MultipleColorSemanticTokens { colors.colorActionPressed }
    /// Has for value token colors.colorActionDisabled
    @objc open var chipColorBorderUnselectedDisabled: MultipleColorSemanticTokens { colors.colorActionDisabled }
    /// Has for value token colors.colorActionFocus
    @objc open var chipColorBorderUnselectedFocus: MultipleColorSemanticTokens { colors.colorActionFocus }
    /// Has for value token borders.radiusPill
    @objc open var chipBorderRadius: BorderRadiusSemanticToken { borders.radiusPill }
    /// Has for value token borders.widthMedium
    @objc open var chipBorderWidthSelected: BorderWidthSemanticToken { borders.widthMedium }
    /// Has for value token borders.widthDefault
    @objc open var chipBorderWidthUnselected: BorderWidthSemanticToken { borders.widthDefault }
    /// Has for value token borders.widthMedium
    @objc open var chipBorderWidthUnselectedInteraction: BorderWidthSemanticToken { borders.widthMedium }
    /// Has for value token spaces.spacePaddingBlock2xsmall
    @objc open var chipSpacePaddingBlock: SpaceSemanticToken { spaces.spacePaddingBlock2xsmall }
    /// Has for value token spaces.spacePaddingBlockXsmall
    @objc open var chipSpacePaddingBlockIconOnly: SpaceSemanticToken { spaces.spacePaddingBlockXsmall }
    /// Has for value token spaces.spacePaddingInlineSmall
    @objc open var chipSpacePaddingInlineIcon: SpaceSemanticToken { spaces.spacePaddingInlineSmall }
    /// Has for value token spaces.spacePaddingInlineLarge
    @objc open var chipSpacePaddingInlineIconNone: SpaceSemanticToken { spaces.spacePaddingInlineLarge }
    /// Has for value token spaces.spacePaddingInlineXsmall
    @objc open var chipSpacePaddingInlineChevronEnd: SpaceSemanticToken { spaces.spacePaddingInlineXsmall }
    /// Has for value token spaces.spacePaddingInline4xsmall
    @objc open var chipSpacePaddingInlineBadgeStart: SpaceSemanticToken { spaces.spacePaddingInline4xsmall }
    /// Has for value token spaces.spaceColumnGapXsmall
    @objc open var chipSpaceColumnGapIcon: SpaceSemanticToken { spaces.spaceColumnGapXsmall }
    /// Has for value token spaces.spaceColumnGap2xsmall
    @objc open var chipSpaceColumnGapBadgeChevron: SpaceSemanticToken { spaces.spaceColumnGap2xsmall }
    /// Has for value token sizes.sizeIconWithLabelMediumSizeSmall
    @objc open var chipSizeIcon: SizeSemanticToken { sizes.sizeIconWithLabelMediumSizeSmall }
    /// Has for value token _s._2xlarge
    @objc open var chipSizeMinWidth: SizeSemanticToken { _s._2xlarge }
    /// Has for value token _s._Xsmall
    @objc open var chipSizeMinHeight: SizeSemanticToken { _s._Xsmall }
    /// Has for value token sizes.sizeMinInteractiveArea
    @objc open var chipSizeMinHeightInteractiveArea: SizeSemanticToken { sizes.sizeMinInteractiveArea }
}
