//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensSemantic

// 🧬 Tokens version: 1.5.0 (Orange brand)
// 🤖 Generated by Tokenator

extension OrangeThemeInputTagComponentTokensProvider: InputTagComponentTokens {
    /// Has for value token colors.colorActionSupportEnabled
    @objc open var inputTagColorBgEnabled: MultipleColorSemanticTokens { colors.colorActionSupportEnabled }
    /// Has for value token colors.colorActionSupportHover
    @objc open var inputTagColorBgHover: MultipleColorSemanticTokens { colors.colorActionSupportHover }
    /// Has for value token colors.colorActionSupportPressed
    @objc open var inputTagColorBgPressed: MultipleColorSemanticTokens { colors.colorActionSupportPressed }
    /// Has for value token colors.colorActionSupportFocus
    @objc open var inputTagColorBgFocus: MultipleColorSemanticTokens { colors.colorActionSupportFocus }
    /// Has for value token colors.colorActionEnabled
    @objc open var inputTagColorContentEnabled: MultipleColorSemanticTokens { colors.colorActionEnabled }
    /// Has for value token colors.colorActionHover
    @objc open var inputTagColorContentHover: MultipleColorSemanticTokens { colors.colorActionHover }
    /// Has for value token colors.colorActionPressed
    @objc open var inputTagColorContentPressed: MultipleColorSemanticTokens { colors.colorActionPressed }
    /// Has for value token colors.colorActionFocus
    @objc open var inputTagColorContentFocus: MultipleColorSemanticTokens { colors.colorActionFocus }
    /// Has for value token colors.colorBorderDefault
    @objc open var inputTagColorBorderEnabled: MultipleColorSemanticTokens { colors.colorBorderDefault }
    /// Has for value token colors.colorActionHover
    @objc open var inputTagColorBorderHover: MultipleColorSemanticTokens { colors.colorActionHover }
    /// Has for value token colors.colorActionPressed
    @objc open var inputTagColorBorderPressed: MultipleColorSemanticTokens { colors.colorActionPressed }
    /// Has for value token colors.colorActionFocus
    @objc open var inputTagColorBorderFocus: MultipleColorSemanticTokens { colors.colorActionFocus }
    /// Has for value token borders.borderWidthDefault
    @objc open var inputTagBorderWidthDefault: BorderWidthSemanticToken { borders.borderWidthDefault }
    /// Has for value token borders.borderWidthMedium
    @objc open var inputTagBorderWidthDefaultInteraction: BorderWidthSemanticToken { borders.borderWidthMedium }
}
