//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensRaw
import OUDSTokensSemantic

// 🧬 Tokens version: 2.1.0 (Orange brand)
// 🤖 Generated by Tokenator

extension OrangeThemeTagComponentTokensProvider: TagComponentTokens {
    /// Has for value token borders.radiusPill
    @objc open var tagBorderRadius: BorderRadiusSemanticToken { borders.radiusPill }
    /// Has for value token spaces.paddingInlineSmall
    @objc open var tagSpacePaddingInlineSmall: SpaceSemanticToken { spaces.paddingInlineSmall }
    /// Has for value token spaces.paddingInlineMedium
    @objc open var tagSpacePaddingInlineDefault: SpaceSemanticToken { spaces.paddingInlineMedium }
    /// Has for value token spaces.paddingInline2xsmall
    @objc open var tagSpacePaddingInlineAssetSmall: SpaceSemanticToken { spaces.paddingInline2xsmall }
    /// Has for value token spaces.paddingInlineXsmall
    @objc open var tagSpacePaddingInlineAssetDefault: SpaceSemanticToken { spaces.paddingInlineXsmall }
    /// Has for value token spaces.paddingBlock3xsmall
    @objc open var tagSpacePaddingBlockSmall: SpaceSemanticToken { spaces.paddingBlock3xsmall }
    /// Has for value token spaces.paddingBlock2xsmall
    @objc open var tagSpacePaddingBlockDefault: SpaceSemanticToken { spaces.paddingBlock2xsmall }
    /// Has for value token spaces.insetNone
    @objc open var tagSpaceInsetIconSmall: SpaceSemanticToken { spaces.insetNone }
    /// Has for value token spaces.inset3xsmall
    @objc open var tagSpaceInsetBulletSmall: SpaceSemanticToken { spaces.inset3xsmall }
    /// Has for value token spaces.inset4xsmall
    @objc open var tagSpaceInsetLoaderSmall: SpaceSemanticToken { spaces.inset4xsmall }
    /// Has for value token spaces.inset4xsmall
    @objc open var tagSpaceInsetIconDefault: SpaceSemanticToken { spaces.inset4xsmall }
    /// Has for value token DimensionRawTokens.outOfSystem75
    @objc open var tagSpaceInsetBulletDefault: SpaceSemanticToken { DimensionRawTokens.outOfSystem75 }
    /// Has for value token spaces.inset3xsmall
    @objc open var tagSpaceInsetLoaderDefault: SpaceSemanticToken { spaces.inset3xsmall }
    /// Has for value token spaces.columnGap2xsmall
    @objc open var tagSpaceColumnGapSmall: SpaceSemanticToken { spaces.columnGap2xsmall }
    /// Has for value token spaces.columnGap2xsmall
    @objc open var tagSpaceColumnGapDefault: SpaceSemanticToken { spaces.columnGap2xsmall }
    /// Has for value token sizes.iconWithLabelSmallSizeSmall
    @objc open var tagSizeAssetSmall: SizeSemanticToken { sizes.iconWithLabelSmallSizeSmall }
    /// Has for value token sizes.iconWithLabelMediumSizeSmall
    @objc open var tagSizeAssetDefault: SizeSemanticToken { sizes.iconWithLabelMediumSizeSmall }
    /// Has for value token dimensions._3xsmall
    @objc open var tagSizeMinHeightSmall: SizeSemanticToken { dimensions._3xsmall }
    /// Has for value token dimensions._Xsmall
    @objc open var tagSizeMinHeightDefault: SizeSemanticToken { dimensions._xsmall }
    /// Has for value token dimensions._Large
    @objc open var tagSizeMinWidthSmall: SizeSemanticToken { dimensions._large }
    /// Has for value token dimensions._Xlarge
    @objc open var tagSizeMinWidthDefault: SizeSemanticToken { dimensions._xlarge }
    /// Has for value token sizes.minInteractiveArea
    @objc open var tagSizeMinHeightInteractiveArea: SizeSemanticToken { sizes.minInteractiveArea }
}
