//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensSemantic

// 🧬 Tokens version: 2.5.0 (Orange brand)
// 🤖 Generated by Tokenator

// swiftlint:disable identifier_name
// swiftlint:disable line_length
extension OrangeThemeIconComponentTokensProvider: IconComponentTokens {
    /// Has for value token MultipleColorSemanticToken(light: colors.repositoryWarningMedium, dark: colors.repositoryWarningLow) (= light: "#FFD000FF" / dark: "#FFE270FF")
    @objc open var colorContentStatusWarningExternalShape: MultipleColorSemanticToken { MultipleColorSemanticToken(light: colors.repositoryWarningMedium, dark: colors.repositoryWarningLow) }
    /// Has for value token MultipleColorSemanticToken(light: colors.repositoryWarningHigh, dark: colors.opacityTransparentDark) (= light: "#856A00FF" / dark: "#FFFFFF00")
    @objc open var colorContentStatusWarningInternalShape: MultipleColorSemanticToken { MultipleColorSemanticToken(light: colors.repositoryWarningHigh, dark: colors.opacityTransparentDark) }
    /// Has for value token MultipleColorSemanticToken(light: colors.repositoryWarningLow, dark: colors.repositoryWarningMedium) (= light: "#FFE270FF" / dark: "#FFD000FF")
    @objc open var colorContentStatusWarningInverseExternalShape: MultipleColorSemanticToken { MultipleColorSemanticToken(light: colors.repositoryWarningLow, dark: colors.repositoryWarningMedium) }
    /// Has for value token MultipleColorSemanticToken(light: colors.opacityTransparentDark, dark: colors.repositoryWarningHigh) (= light: "#FFFFFF00" / dark: "#856A00FF")
    @objc open var colorContentStatusWarningInverseInternalShape: MultipleColorSemanticToken { MultipleColorSemanticToken(light: colors.opacityTransparentDark, dark: colors.repositoryWarningHigh) }

    // MARK: - Old tokens to keep until components updates
    // See https://github.com/Orange-OpenSource/ouds-ios#1437

    /// Has for value token MultipleColorSemanticToken(light: colors.repositoryNeutralEmphasizedBlack, dark: colors.repositoryNeutralMutedLower)
    @objc public final var colorContentDefault: MultipleColorSemanticToken { MultipleColorSemanticToken(light: colors.repositoryNeutralEmphasizedBlack, dark: colors.repositoryNeutralMutedLower) }
}

// swiftlint:enable identifier_name
// swiftlint:enable line_length
