//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensRaw
import OUDSTokensSemantic

// 🧬 Tokens version: 2.1.0 (Orange brand)
// 🤖 Generated by Tokenator

extension OrangeThemeBadgeComponentTokensProvider: BadgeComponentTokens {
    /// Has for value token DimensionRawTokens.dimensionOutOfSystem75
    @objc open var badgeSpaceInset: SpaceSemanticToken { DimensionRawTokens.dimensionOutOfSystem75 }
    /// Has for value token spaces.spacePaddingInline3xsmall
    @objc open var badgeSpacePaddingInlineMedium: SpaceSemanticToken { spaces.spacePaddingInline3xsmall }
    /// Has for value token spaces.spacePaddingInline2xsmall
    @objc open var badgeSpacePaddingInlineLarge: SpaceSemanticToken { spaces.spacePaddingInline2xsmall }
    /// Has for value token dimensions.dimension8xsmall
    @objc open var badgeSizeXsmall: SizeSemanticToken { dimensions.dimension8xsmall }
    /// Has for value token dimensions.dimension6xsmall
    @objc open var badgeSizeSmall: SizeSemanticToken { dimensions.dimension6xsmall }
    /// Has for value token dimensions.dimension5xsmall
    @objc open var badgeSizeMedium: SizeSemanticToken { dimensions.dimension5xsmall }
    /// Has for value token dimensions.dimension4xsmall
    @objc open var badgeSizeLarge: SizeSemanticToken { dimensions.dimension4xsmall }
}
