//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensSemantic

// 🧬 Tokens version: 2.7.0 (Orange brand)
// 🤖 Generated by Tokenator

// swiftlint:disable identifier_name

extension OrangeThemeTypographyComponentTokensProvider: TypographyComponentTokens {
    /// Has for value token colors.contentBrandPrimary (= light: "#F15E00FF" / dark: "#FF7900FF")
    @objc open var colorContentMarker: MultipleColorSemanticToken { colors.contentBrandPrimary }
    /// Has for value token true
    @objc open var headingLargeMarker: Bool { true }
    /// Has for value token {ouds1f4a0_paddingBlock4xsmall (= 2)
    @objc open var spacePaddingBlockBottomHeadingLargeMarker: SpaceSemanticToken { {ouds1f4a0_paddingBlock4xsmall }
    /// Has for value token {ouds1f4a0_paddingBlock3xsmall (= 4)
    @objc open var spacePaddingBlockTopHeadingLargeMarker: SpaceSemanticToken { {ouds1f4a0_paddingBlock3xsmall }
}

// swiftlint:enable identifier_name
