//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensRaw
import OUDSTokensSemantic

// 🧱 Tokens version: 0.11.0
// 🤖 Generated by Tokenator

extension OrangeThemeButtonComponentTokensProvider: ButtonComponentTokens {
    /// borders.borderRadiusDefault
    @objc open var buttonBorderRadius: BorderRadiusSemanticToken { borders.borderRadiusDefault }
    /// borders.borderWidthDefault
    @objc open var buttonBorderWidthDefault: BorderWidthSemanticToken { borders.borderWidthDefault }
    /// borders.borderWidthMedium
    @objc open var buttonBorderWidthDefaultInteraction: BorderWidthSemanticToken { borders.borderWidthMedium }
    /// borders.borderWidthNone
    @objc open var buttonBorderWidthDefaultInteractionMono: BorderWidthSemanticToken { borders.borderWidthNone }
    /// borders.borderWidthNone
    @objc open var buttonBorderWidthMinimal: BorderWidthSemanticToken { borders.borderWidthNone }
    /// borders.borderWidthNone
    @objc open var buttonBorderWidthMinimalInteraction: BorderWidthSemanticToken { borders.borderWidthNone }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBgDefaultDisabled: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBgDefaultDisabledMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBgDefaultEnabled: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBgDefaultEnabledMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBgDefaultFocus: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorRepositoryOpacityBlackHigher 
    @objc open var buttonColorBgDefaultFocusMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityBlackHigher }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBgDefaultHover: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorRepositoryOpacityBlackHigher 
    @objc open var buttonColorBgDefaultHoverMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityBlackHigher }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBgDefaultLoading: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorRepositoryOpacityWhiteHigher 
    @objc open var buttonColorBgDefaultLoadingMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityWhiteHigher }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBgDefaultPressed: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorRepositoryOpacityWhiteHigher 
    @objc open var buttonColorBgDefaultPressedMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityWhiteHigher }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBgMinimalDisabled: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBgMinimalDisabledMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBgMinimalEnabled: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBgMinimalEnabledMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorActionSupportFocus 
    @objc open var buttonColorBgMinimalFocus: MultipleColorSemanticTokens { colors.colorActionSupportFocus }
    ///  colors.colorRepositoryOpacityBlackHigher 
    @objc open var buttonColorBgMinimalFocusMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityBlackHigher }
    ///  colors.colorActionSupportHover 
    @objc open var buttonColorBgMinimalHover: MultipleColorSemanticTokens { colors.colorActionSupportHover }
    ///  colors.colorRepositoryOpacityBlackHigher 
    @objc open var buttonColorBgMinimalHoverMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityBlackHigher }
    ///  colors.colorActionSupportLoading 
    @objc open var buttonColorBgMinimalLoading: MultipleColorSemanticTokens { colors.colorActionSupportLoading }
    ///  colors.colorRepositoryOpacityWhiteHigher 
    @objc open var buttonColorBgMinimalLoadingMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityWhiteHigher }
    ///  colors.colorActionSupportPressed 
    @objc open var buttonColorBgMinimalPressed: MultipleColorSemanticTokens { colors.colorActionSupportPressed }
    ///  colors.colorRepositoryOpacityWhiteHigher 
    @objc open var buttonColorBgMinimalPressedMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityWhiteHigher }
    ///  colors.colorRepositoryOpacityBlackMedium 
    @objc open var buttonColorBgStrongDisabledMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityBlackMedium }
    ///  colors.colorRepositoryNeutralEmphasizedBlack 
    @objc open var buttonColorBgStrongEnabledMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralEmphasizedBlack }
    ///  colors.colorRepositoryOpacityBlackHigher 
    @objc open var buttonColorBgStrongFocusMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityBlackHigher }
    ///  colors.colorRepositoryOpacityBlackHigher 
    @objc open var buttonColorBgStrongHoverMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityBlackHigher }
    ///  colors.colorRepositoryOpacityWhiteHigher 
    @objc open var buttonColorBgStrongLoadingMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityWhiteHigher }
    ///  colors.colorRepositoryOpacityWhiteHigher 
    @objc open var buttonColorBgStrongPressedMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityWhiteHigher }
    ///  colors.colorActionDisabled 
    @objc open var buttonColorBorderDefaultDisabled: MultipleColorSemanticTokens { colors.colorActionDisabled }
    ///  colors.colorRepositoryOpacityBlackMedium 
    @objc open var buttonColorBorderDefaultDisabledMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityBlackMedium }
    ///  colors.colorActionEnabled 
    @objc open var buttonColorBorderDefaultEnabled: MultipleColorSemanticTokens { colors.colorActionEnabled }
    ///  colors.colorRepositoryNeutralEmphasizedBlack 
    @objc open var buttonColorBorderDefaultEnabledMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralEmphasizedBlack }
    ///  colors.colorActionFocus 
    @objc open var buttonColorBorderDefaultFocus: MultipleColorSemanticTokens { colors.colorActionFocus }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderDefaultFocusMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorActionHover 
    @objc open var buttonColorBorderDefaultHover: MultipleColorSemanticTokens { colors.colorActionHover }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderDefaultHoverMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorActionLoading 
    @objc open var buttonColorBorderDefaultLoading: MultipleColorSemanticTokens { colors.colorActionLoading }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderDefaultLoadingMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorActionPressed 
    @objc open var buttonColorBorderDefaultPressed: MultipleColorSemanticTokens { colors.colorActionPressed }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderDefaultPressedMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderMinimalDisabled: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderMinimalDisabledMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderMinimalEnabled: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderMinimalEnabledMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderMinimalFocus: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderMinimalFocusMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderMinimalHover: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderMinimalHoverMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderMinimalLoading: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderMinimalLoadingMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderMinimalPressed: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderMinimalPressedMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderStrongDisabledMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderStrongEnabledMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderStrongFocusMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderStrongHoverMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderStrongLoadingMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorOpacityTransparent 
    @objc open var buttonColorBorderStrongPressedMono: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    ///  colors.colorActionDisabled 
    @objc open var buttonColorContentDefaultDisabled: MultipleColorSemanticTokens { colors.colorActionDisabled }
    ///  colors.colorRepositoryOpacityBlackMedium 
    @objc open var buttonColorContentDefaultDisabledMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityBlackMedium }
    ///  colors.colorActionEnabled 
    @objc open var buttonColorContentDefaultEnabled: MultipleColorSemanticTokens { colors.colorActionEnabled }
    ///  colors.colorRepositoryNeutralEmphasizedBlack 
    @objc open var buttonColorContentDefaultEnabledMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralEmphasizedBlack }
    ///  colors.colorActionFocus 
    @objc open var buttonColorContentDefaultFocus: MultipleColorSemanticTokens { colors.colorActionFocus }
    ///  colors.colorRepositoryNeutralMutedWhite 
    @objc open var buttonColorContentDefaultFocusMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralMutedWhite }
    ///  colors.colorActionHover 
    @objc open var buttonColorContentDefaultHover: MultipleColorSemanticTokens { colors.colorActionHover }
    ///  colors.colorRepositoryNeutralMutedWhite 
    @objc open var buttonColorContentDefaultHoverMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralMutedWhite }
    ///  colors.colorActionLoading 
    @objc open var buttonColorContentDefaultLoading: MultipleColorSemanticTokens { colors.colorActionLoading }
    ///  colors.colorRepositoryNeutralEmphasizedBlack 
    @objc open var buttonColorContentDefaultLoadingMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralEmphasizedBlack }
    ///  colors.colorActionPressed 
    @objc open var buttonColorContentDefaultPressed: MultipleColorSemanticTokens { colors.colorActionPressed }
    ///  colors.colorRepositoryNeutralEmphasizedBlack 
    @objc open var buttonColorContentDefaultPressedMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralEmphasizedBlack }
    ///  colors.colorActionDisabled 
    @objc open var buttonColorContentMinimalDisabled: MultipleColorSemanticTokens { colors.colorActionDisabled }
    ///  colors.colorRepositoryOpacityBlackMedium 
    @objc open var buttonColorContentMinimalDisabledMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityBlackMedium }
    ///  colors.colorActionEnabled 
    @objc open var buttonColorContentMinimalEnabled: MultipleColorSemanticTokens { colors.colorActionEnabled }
    ///  colors.colorRepositoryNeutralEmphasizedBlack 
    @objc open var buttonColorContentMinimalEnabledMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralEmphasizedBlack }
    ///  colors.colorActionFocus 
    @objc open var buttonColorContentMinimalFocus: MultipleColorSemanticTokens { colors.colorActionFocus }
    ///  colors.colorRepositoryNeutralMutedWhite 
    @objc open var buttonColorContentMinimalFocusMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralMutedWhite }
    ///  colors.colorActionHover 
    @objc open var buttonColorContentMinimalHover: MultipleColorSemanticTokens { colors.colorActionHover }
    ///  colors.colorRepositoryNeutralMutedWhite 
    @objc open var buttonColorContentMinimalHoverMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralMutedWhite }
    ///  colors.colorContentDefault 
    @objc open var buttonColorContentMinimalLoading: MultipleColorSemanticTokens { colors.colorContentDefault }
    ///  colors.colorRepositoryNeutralEmphasizedBlack 
    @objc open var buttonColorContentMinimalLoadingMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralEmphasizedBlack }
    ///  colors.colorActionPressed 
    @objc open var buttonColorContentMinimalPressed: MultipleColorSemanticTokens { colors.colorActionPressed }
    ///  colors.colorRepositoryNeutralEmphasizedBlack 
    @objc open var buttonColorContentMinimalPressedMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralEmphasizedBlack }
    ///  colors.colorRepositoryOpacityWhiteHigh 
    @objc open var buttonColorContentStrongDisabledMono: MultipleColorSemanticTokens { colors.colorRepositoryOpacityWhiteHigh }
    ///  colors.colorRepositoryNeutralMutedWhite 
    @objc open var buttonColorContentStrongEnabledMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralMutedWhite }
    ///  colors.colorRepositoryNeutralMutedWhite 
    @objc open var buttonColorContentStrongFocusMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralMutedWhite }
    ///  colors.colorRepositoryNeutralMutedWhite 
    @objc open var buttonColorContentStrongHoverMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralMutedWhite }
    ///  colors.colorRepositoryNeutralEmphasizedBlack 
    @objc open var buttonColorContentStrongLoadingMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralEmphasizedBlack }
    ///  colors.colorRepositoryNeutralEmphasizedBlack 
    @objc open var buttonColorContentStrongPressedMono: MultipleColorSemanticTokens { colors.colorRepositoryNeutralEmphasizedBlack }
    /// sizes.sizeIconWithLabelLargeSizeXs
    @objc open var buttonSizeIcon: SizeSemanticToken { sizes.sizeIconWithLabelLargeSizeXs }
    /// sizes.sizeIconWithLabelLargeSizeSm
    @objc open var buttonSizeIconOnly: SizeSemanticToken { sizes.sizeIconWithLabelLargeSizeSm }
    /// sizes.sizeIconWithLabelLargeSizeXs
    @objc open var buttonSizeLoader: SizeSemanticToken { sizes.sizeIconWithLabelLargeSizeXs }
    /// DimensionRawTokens.dimension600
    @objc open var buttonSizeMaxHeightIconOnly: SizeSemanticToken { DimensionRawTokens.dimension600 }
    /// DimensionRawTokens.dimension600
    @objc open var buttonSizeMinHeight: SizeSemanticToken { DimensionRawTokens.dimension600 }
    /// DimensionRawTokens.dimension600
    @objc open var buttonSizeMinWidth: SizeSemanticToken { DimensionRawTokens.dimension600 }
    /// spaces.spaceColumnGapShorter
    @objc open var buttonSpaceColumnGapArrow: SpaceSemanticToken { spaces.spaceColumnGapShorter }
    /// spaces.spaceColumnGapShort
    @objc open var buttonSpaceColumnGapIcon: SpaceSemanticToken { spaces.spaceColumnGapShort }
    /// spaces.spaceInsetMedium
    @objc open var buttonSpaceInsetIconOnly: SpaceSemanticToken { spaces.spaceInsetMedium }
    /// spaces.spacePaddingBlockMedium
    @objc open var buttonSpacePaddingBlock: SpaceSemanticToken { spaces.spacePaddingBlockMedium }
    /// spaces.spacePaddingInlineTall
    @objc open var buttonSpacePaddingInlineArrowEnd: SpaceSemanticToken { spaces.spacePaddingInlineTall }
    /// spaces.spacePaddingInlineTall
    @objc open var buttonSpacePaddingInlineArrowStart: SpaceSemanticToken { spaces.spacePaddingInlineTall }
    /// spaces.spacePaddingInlineSpacious
    @objc open var buttonSpacePaddingInlineEndIconStart: SpaceSemanticToken { spaces.spacePaddingInlineSpacious }
    /// spaces.spacePaddingInlineHuge
    @objc open var buttonSpacePaddingInlineIconNone: SpaceSemanticToken { spaces.spacePaddingInlineHuge }
    /// spaces.spacePaddingInlineTaller
    @objc open var buttonSpacePaddingInlineIconStart: SpaceSemanticToken { spaces.spacePaddingInlineTaller }
    /// spaces.spacePaddingInlineSpacious
    @objc open var buttonSpacePaddingInlineStartIconEnd: SpaceSemanticToken { spaces.spacePaddingInlineSpacious }
}
