//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensRaw
import OUDSTokensSemantic

// 🧱 Tokens version: 0.6.1
// 🤖 Generated by Tokenator

extension OrangeThemeTagComponentTokensProvider: TagComponentTokens {
    @objc open var tagColorBgReminder: MultipleColorSemanticTokens { colors.colorOpacityLower }
}
