//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable line_length

/// Defines provider objects for elevation semantic tokens but "multiple", i.e. tokens with values depending to color schemes.
/// These values can be overriden inside `WireframeThemeElevationSemanticTokensProvider` subclasses (in extensions or not, in the same module or not) thanks to the `@objc open` combination.
extension WireframeThemeElevationSemanticTokensProvider: ElevationMultipleSemanticTokens {

    public var colorDefault: ElevationMultipleColorSemanticToken { MultipleColorSemanticTokens(light: colorDefaultLight, dark: colorDefaultDark) }

    public var colorRaised: ElevationMultipleColorSemanticToken { MultipleColorSemanticTokens(light: colorRaisedLight, dark: colorRaisedDark) }

    public var colorDrag: ElevationMultipleColorSemanticToken { MultipleColorSemanticTokens(light: colorDragLight, dark: colorDragDark) }

    public var colorEmphasized: ElevationMultipleColorSemanticToken { MultipleColorSemanticTokens(light: colorEmphasizedLight, dark: colorEmphasizedDark) }

    public var colorSticky: ElevationMultipleColorSemanticToken { MultipleColorSemanticTokens(light: colorStickyLight, dark: colorStickyDark) }
}

// swiftlint:enable line_length
