//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensRaw
import OUDSTokensSemantic

// 🧬 Tokens version: 2.1.0 (Wireframe brand)
// 🤖 Generated by Tokenator

extension WireframeThemeElevationSemanticTokensProvider: ElevationSemanticTokens {
    /// Has for value token ElevationRawTokens.elevationX0
    @objc public final var elevationXNone: ElevationXSemanticToken { ElevationRawTokens.elevationX0 }
    /// Has for value token ElevationRawTokens.elevationX0
    @objc public final var elevationXRaised: ElevationXSemanticToken { ElevationRawTokens.elevationX0 }
    /// Has for value token ElevationRawTokens.elevationX0
    @objc public final var elevationXDefault: ElevationXSemanticToken { ElevationRawTokens.elevationX0 }
    /// Has for value token ElevationRawTokens.elevationX0
    @objc public final var elevationXEmphasized: ElevationXSemanticToken { ElevationRawTokens.elevationX0 }
    /// Has for value token ElevationRawTokens.elevationX0
    @objc public final var elevationXDrag: ElevationXSemanticToken { ElevationRawTokens.elevationX0 }
    /// Has for value token ElevationRawTokens.elevationX0
    @objc public final var elevationXSticky: ElevationXSemanticToken { ElevationRawTokens.elevationX0 }
    /// Has for value token ElevationRawTokens.elevationY0
    @objc public final var elevationYNone: ElevationYSemanticToken { ElevationRawTokens.elevationY0 }
    /// Has for value token ElevationRawTokens.elevationY100
    @objc public final var elevationYRaised: ElevationYSemanticToken { ElevationRawTokens.elevationY100 }
    /// Has for value token ElevationRawTokens.elevationY200
    @objc public final var elevationYDefault: ElevationYSemanticToken { ElevationRawTokens.elevationY200 }
    /// Has for value token ElevationRawTokens.elevationY500
    @objc public final var elevationYEmphasized: ElevationYSemanticToken { ElevationRawTokens.elevationY500 }
    /// Has for value token ElevationRawTokens.elevationY300
    @objc public final var elevationYDrag: ElevationYSemanticToken { ElevationRawTokens.elevationY300 }
    /// Has for value token ElevationRawTokens.elevationY300
    @objc public final var elevationYSticky: ElevationYSemanticToken { ElevationRawTokens.elevationY300 }
    /// Has for value token ElevationRawTokens.elevationBlur0
    @objc public final var elevationBlurNone: ElevationBlurSemanticToken { ElevationRawTokens.elevationBlur0 }
    /// Has for value token ElevationRawTokens.elevationBlur200
    @objc public final var elevationBlurRaised: ElevationBlurSemanticToken { ElevationRawTokens.elevationBlur200 }
    /// Has for value token ElevationRawTokens.elevationBlur300
    @objc public final var elevationBlurDefault: ElevationBlurSemanticToken { ElevationRawTokens.elevationBlur300 }
    /// Has for value token ElevationRawTokens.elevationBlur600
    @objc public final var elevationBlurEmphasized: ElevationBlurSemanticToken { ElevationRawTokens.elevationBlur600 }
    /// Has for value token ElevationRawTokens.elevationBlur400
    @objc public final var elevationBlurDrag: ElevationBlurSemanticToken { ElevationRawTokens.elevationBlur400 }
    /// Has for value token ElevationRawTokens.elevationBlur400
    @objc public final var elevationBlurSticky: ElevationBlurSemanticToken { ElevationRawTokens.elevationBlur400 }
    /// Has for value token ColorRawTokens.opacityBlack0
    @objc public final var elevationColorNone: ElevationColorSemanticToken { ColorRawTokens.opacityBlack0 }
    /// Has for value token ColorRawTokens.opacityBlack240
    @objc public final var elevationColorRaisedLight: ElevationColorSemanticToken { ColorRawTokens.opacityBlack240 }
    /// Has for value token ColorRawTokens.opacityBlack320
    @objc public final var elevationColorRaisedDark: ElevationColorSemanticToken { ColorRawTokens.opacityBlack320 }
    /// Has for value token ColorRawTokens.opacityBlack240
    @objc public final var elevationColorDefaultLight: ElevationColorSemanticToken { ColorRawTokens.opacityBlack240 }
    /// Has for value token ColorRawTokens.opacityBlack240
    @objc public final var elevationColorDefaultDark: ElevationColorSemanticToken { ColorRawTokens.opacityBlack240 }
    /// Has for value token ColorRawTokens.opacityBlack160
    @objc public final var elevationColorEmphasizedLight: ElevationColorSemanticToken { ColorRawTokens.opacityBlack160 }
    /// Has for value token ColorRawTokens.opacityBlack160
    @objc public final var elevationColorEmphasizedDark: ElevationColorSemanticToken { ColorRawTokens.opacityBlack160 }
    /// Has for value token ColorRawTokens.opacityBlack240
    @objc public final var elevationColorDragLight: ElevationColorSemanticToken { ColorRawTokens.opacityBlack240 }
    /// Has for value token ColorRawTokens.opacityBlack320
    @objc public final var elevationColorDragDark: ElevationColorSemanticToken { ColorRawTokens.opacityBlack320 }
    /// Has for value token ColorRawTokens.opacityBlack160
    @objc public final var elevationColorStickyLight: ElevationColorSemanticToken { ColorRawTokens.opacityBlack160 }
    /// Has for value token ColorRawTokens.opacityBlack160
    @objc public final var elevationColorStickyDark: ElevationColorSemanticToken { ColorRawTokens.opacityBlack160 }
}
