//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensRaw
import OUDSTokensSemantic

// 🧬 Tokens version: 2.1.0 (Wireframe brand)
// 🤖 Generated by Tokenator

extension WireframeThemeOpacitySemanticTokensProvider: OpacitySemanticTokens {
    /// Has for value token OpacityRawTokens._0
    @objc public final var opacityInvisible: OpacitySemanticToken { OpacityRawTokens._0 }
    /// Has for value token OpacityRawTokens._40
    @objc public final var opacityWeakest: OpacitySemanticToken { OpacityRawTokens._40 }
    /// Has for value token OpacityRawTokens._160
    @objc public final var opacityWeaker: OpacitySemanticToken { OpacityRawTokens._160 }
    /// Has for value token OpacityRawTokens._320
    @objc public final var opacityWeak: OpacitySemanticToken { OpacityRawTokens._320 }
    /// Has for value token OpacityRawTokens._560
    @objc public final var opacityMedium: OpacitySemanticToken { OpacityRawTokens._560 }
    /// Has for value token OpacityRawTokens._640
    @objc public final var opacityStrong: OpacitySemanticToken { OpacityRawTokens._640 }
    /// Has for value token OpacityRawTokens._1000
    @objc public final var opacityOpaque: OpacitySemanticToken { OpacityRawTokens._1000 }
    /// Has for value token OpacityRawTokens._200
    @objc public final var opacityDisabled: OpacitySemanticToken { OpacityRawTokens._200 }
}
