//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensComponent
import OUDSTokensSemantic

// 🧱 Tokens version: 1.3.0 (Orange Business Tools brand)
// 🤖 Generated by Tokenator

extension OrangeBusinessToolsThemeButtonComponentTokensProvider: ButtonComponentTokens {
    /// Has for value token colors.colorOpacityTransparent
    @objc public final var buttonColorBgDefaultEnabled: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    /// Has for value token colors.colorOpacityTransparent
    @objc public final var buttonColorBgDefaultHover: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    /// Has for value token colors.colorOpacityTransparent
    @objc public final var buttonColorBgDefaultPressed: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    /// Has for value token colors.colorOpacityTransparent
    @objc public final var buttonColorBgDefaultLoading: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    /// Has for value token colors.colorOpacityTransparent
    @objc public final var buttonColorBgDefaultDisabled: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    /// Has for value token colors.colorOpacityTransparent
    @objc public final var buttonColorBgDefaultFocus: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    /// Has for value token colors.colorOpacityTransparent
    @objc public final var buttonColorBgMinimalEnabled: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    /// Has for value token colors.colorActionSupportHover
    @objc public final var buttonColorBgMinimalHover: MultipleColorSemanticTokens { colors.colorActionSupportHover }
    /// Has for value token colors.colorActionSupportPressed
    @objc public final var buttonColorBgMinimalPressed: MultipleColorSemanticTokens { colors.colorActionSupportPressed }
    /// Has for value token colors.colorActionSupportLoading
    @objc public final var buttonColorBgMinimalLoading: MultipleColorSemanticTokens { colors.colorActionSupportLoading }
    /// Has for value token colors.colorOpacityTransparent
    @objc public final var buttonColorBgMinimalDisabled: MultipleColorSemanticTokens { colors.colorOpacityTransparent }
    /// Has for value token colors.colorActionSupportFocus
    @objc public final var buttonColorBgMinimalFocus: MultipleColorSemanticTokens { colors.colorActionSupportFocus }
    /// Has for value token colors.colorActionEnabled
    @objc public final var buttonColorContentDefaultEnabled: MultipleColorSemanticTokens { colors.colorActionEnabled }
    /// Has for value token colors.colorActionHover
    @objc public final var buttonColorContentDefaultHover: MultipleColorSemanticTokens { colors.colorActionHover }
    /// Has for value token colors.colorActionPressed
    @objc public final var buttonColorContentDefaultPressed: MultipleColorSemanticTokens { colors.colorActionPressed }
    /// Has for value token colors.colorActionLoading
    @objc public final var buttonColorContentDefaultLoading: MultipleColorSemanticTokens { colors.colorActionLoading }
    /// Has for value token colors.colorActionDisabled
    @objc public final var buttonColorContentDefaultDisabled: MultipleColorSemanticTokens { colors.colorActionDisabled }
    /// Has for value token colors.colorActionFocus
    @objc public final var buttonColorContentDefaultFocus: MultipleColorSemanticTokens { colors.colorActionFocus }
    /// Has for value token colors.colorActionEnabled
    @objc public final var buttonColorContentMinimalEnabled: MultipleColorSemanticTokens { colors.colorActionEnabled }
    /// Has for value token colors.colorActionHover
    @objc public final var buttonColorContentMinimalHover: MultipleColorSemanticTokens { colors.colorActionHover }
    /// Has for value token colors.colorActionPressed
    @objc public final var buttonColorContentMinimalPressed: MultipleColorSemanticTokens { colors.colorActionPressed }
    /// Has for value token colors.colorContentDefault
    @objc public final var buttonColorContentMinimalLoading: MultipleColorSemanticTokens { colors.colorContentDefault }
    /// Has for value token colors.colorActionDisabled
    @objc public final var buttonColorContentMinimalDisabled: MultipleColorSemanticTokens { colors.colorActionDisabled }
    /// Has for value token colors.colorActionFocus
    @objc public final var buttonColorContentMinimalFocus: MultipleColorSemanticTokens { colors.colorActionFocus }
    /// Has for value token colors.colorActionEnabled
    @objc public final var buttonColorBorderDefaultEnabled: MultipleColorSemanticTokens { colors.colorActionEnabled }
    /// Has for value token colors.colorActionHover
    @objc public final var buttonColorBorderDefaultHover: MultipleColorSemanticTokens { colors.colorActionHover }
    /// Has for value token colors.colorActionPressed
    @objc public final var buttonColorBorderDefaultPressed: MultipleColorSemanticTokens { colors.colorActionPressed }
    /// Has for value token colors.colorActionLoading
    @objc public final var buttonColorBorderDefaultLoading: MultipleColorSemanticTokens { colors.colorActionLoading }
    /// Has for value token colors.colorActionDisabled
    @objc public final var buttonColorBorderDefaultDisabled: MultipleColorSemanticTokens { colors.colorActionDisabled }
    /// Has for value token colors.colorActionFocus
    @objc public final var buttonColorBorderDefaultFocus: MultipleColorSemanticTokens { colors.colorActionFocus }
    /// Has for value token borders.borderRadiusDefault
    @objc public final var buttonBorderRadius: BorderRadiusSemanticToken { borders.borderRadiusDefault }
    /// Has for value token borders.borderWidthDefault
    @objc public final var buttonBorderWidthDefault: BorderWidthSemanticToken { borders.borderWidthDefault }
    /// Has for value token borders.borderWidthMedium
    @objc public final var buttonBorderWidthDefaultInteraction: BorderWidthSemanticToken { borders.borderWidthMedium }
    /// Has for value token borders.borderWidthNone
    @objc public final var buttonBorderWidthDefaultInteractionMono: BorderWidthSemanticToken { borders.borderWidthNone }
    /// Has for value token spaces.spaceInsetMd
    @objc public final var buttonSpaceInsetIconOnly: SpaceSemanticToken { spaces.spaceInsetMd }
    /// Has for value token spaces.spacePaddingBlockMd
    @objc public final var buttonSpacePaddingBlock: SpaceSemanticToken { spaces.spacePaddingBlockMd }
    /// Has for value token spaces.spacePaddingInline3xl
    @objc public final var buttonSpacePaddingInlineStartIconEnd: SpaceSemanticToken { spaces.spacePaddingInline3xl }
    /// Has for value token spaces.spacePaddingInline3xl
    @objc public final var buttonSpacePaddingInlineEndIconStart: SpaceSemanticToken { spaces.spacePaddingInline3xl }
    /// Has for value token spaces.spacePaddingInline4xl
    @objc public final var buttonSpacePaddingInlineIconNone: SpaceSemanticToken { spaces.spacePaddingInline4xl }
    /// Has for value token spaces.spacePaddingInlineXl
    @objc public final var buttonSpacePaddingInlineIconStart: SpaceSemanticToken { spaces.spacePaddingInlineXl }
    /// Has for value token spaces.spacePaddingInlineLg
    @objc public final var buttonSpacePaddingInlineChevronStart: SpaceSemanticToken { spaces.spacePaddingInlineLg }
    /// Has for value token spaces.spacePaddingInlineLg
    @objc public final var buttonSpacePaddingInlineChevronEnd: SpaceSemanticToken { spaces.spacePaddingInlineLg }
    /// Has for value token spaces.spaceColumnGapSm
    @objc public final var buttonSpaceColumnGapIcon: SpaceSemanticToken { spaces.spaceColumnGapSm }
    /// Has for value token spaces.spaceColumnGapXs
    @objc public final var buttonSpaceColumnGapChevron: SpaceSemanticToken { spaces.spaceColumnGapXs }
    /// Has for value token spaces.spaceColumnGap2xs
    @objc public final var buttonSpaceColumnGapIconChevron: SpaceSemanticToken { spaces.spaceColumnGap2xs }
    /// Has for value token sizes.sizeIconWithLabelLargeSizeXs
    @objc public final var buttonSizeIcon: SizeSemanticToken { sizes.sizeIconWithLabelLargeSizeXs }
    /// Has for value token sizes.sizeIconWithLabelLargeSizeSm
    @objc public final var buttonSizeIconOnly: SizeSemanticToken { sizes.sizeIconWithLabelLargeSizeSm }
    /// Has for value token sizes.sizeIconWithLabelLargeSizeXs
    @objc public final var buttonSizeLoader: SizeSemanticToken { sizes.sizeIconWithLabelLargeSizeXs }
    /// Has for value token sizes.sizeMinInteractiveArea
    @objc public final var buttonSizeMinHeight: SizeSemanticToken { sizes.sizeMinInteractiveArea }
    /// Has for value token sizes.sizeMinInteractiveArea
    @objc public final var buttonSizeMinWidth: SizeSemanticToken { sizes.sizeMinInteractiveArea }
    /// Has for value token sizes.sizeMinInteractiveArea
    @objc public final var buttonSizeMaxHeightIconOnly: SizeSemanticToken { sizes.sizeMinInteractiveArea }
}
