//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDS
import OUDSThemesOrangeBusinessTools
import Testing

// swiftlint:disable function_body_length
// swiftlint:disable type_body_length

/// Checks if the closed semantic tokens of dimensions, as defined in the OrangeBusinessTools theme, have expected values and relationships
/// between them.
struct DimensionSemanticTokensValuesTests {

    private var theme: OUDSTheme

    init() {
        theme = OrangeBusinessToolsTheme()
    }

    @Test func dimensionsAreSmallerOneByOne() throws {
        #expect(theme.dimensions.dimensionNone < theme.dimensions.dimension12xsmall)
        #expect(theme.dimensions.dimension12xsmall < theme.dimensions.dimension11xsmall)
        #expect(theme.dimensions.dimension11xsmall < theme.dimensions.dimension10xsmall)
        #expect(theme.dimensions.dimension10xsmall < theme.dimensions.dimension9xsmall)
        #expect(theme.dimensions.dimension9xsmall < theme.dimensions.dimension8xsmall)
        #expect(theme.dimensions.dimension8xsmall < theme.dimensions.dimension7xsmall)
        #expect(theme.dimensions.dimension7xsmall <= theme.dimensions.dimension6xsmall) // Confirmed by Mdesign team, can be equal
        #expect(theme.dimensions.dimension6xsmall < theme.dimensions.dimension5xsmall)
        #expect(theme.dimensions.dimension5xsmall < theme.dimensions.dimension4xsmall)
        #expect(theme.dimensions.dimension4xsmall < theme.dimensions.dimension3xsmall)
        #expect(theme.dimensions.dimension3xsmall < theme.dimensions.dimension2xsmall)
        #expect(theme.dimensions.dimension2xsmall < theme.dimensions.dimensionXsmall)
        #expect(theme.dimensions.dimensionXsmall < theme.dimensions.dimensionSmall)
        #expect(theme.dimensions.dimensionSmall < theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimensionMedium < theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimensionLarge < theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimensionXlarge < theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimension2xlarge < theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimension3xlarge < theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimension4xlarge < theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension5xlarge < theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension6xlarge < theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension7xlarge < theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension8xlarge < theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension9xlarge < theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension10xlarge < theme.dimensions.dimension11xlarge)
    }

    @Test func dimensionsAreAllUnique() throws {
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension12xsmall)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension11xsmall)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension10xsmall)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension9xsmall)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension8xsmall)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension7xsmall)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension6xsmall)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension5xsmall)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension4xsmall)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension3xsmall)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension2xsmall)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimensionXsmall)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimensionSmall)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimensionNone != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension11xsmall)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension10xsmall)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension9xsmall)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension8xsmall)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension7xsmall)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension6xsmall)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension5xsmall)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension4xsmall)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension3xsmall)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension2xsmall)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimensionXsmall)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimensionSmall)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension12xsmall != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension10xsmall)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension9xsmall)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension8xsmall)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension7xsmall)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension6xsmall)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension5xsmall)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension4xsmall)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension3xsmall)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension2xsmall)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimensionXsmall)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimensionSmall)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension11xsmall != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension9xsmall)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension8xsmall)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension7xsmall)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension6xsmall)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension5xsmall)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension4xsmall)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension3xsmall)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension2xsmall)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimensionXsmall)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimensionSmall)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension10xsmall != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension8xsmall)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension7xsmall)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension6xsmall)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension5xsmall)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension4xsmall)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension3xsmall)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension2xsmall)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimensionXsmall)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimensionSmall)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension9xsmall != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension7xsmall)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension6xsmall)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension5xsmall)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension4xsmall)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension3xsmall)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension2xsmall)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimensionXsmall)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimensionSmall)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension8xsmall != theme.dimensions.dimension11xlarge)

        // Confirmed by Mdesign team, can be equal
        // #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension6xsmall)

        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension5xsmall)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension4xsmall)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension3xsmall)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension2xsmall)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimensionXsmall)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimensionSmall)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension7xsmall != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimension5xsmall)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimension4xsmall)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimension3xsmall)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimension2xsmall)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimensionXsmall)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimensionSmall)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension6xsmall != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimension4xsmall)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimension3xsmall)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimension2xsmall)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimensionXsmall)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimensionSmall)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension5xsmall != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimension3xsmall)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimension2xsmall)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimensionXsmall)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimensionSmall)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension4xsmall != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimension2xsmall)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimensionXsmall)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimensionSmall)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension3xsmall != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimensionXsmall)
        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimensionSmall)
        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension2xsmall != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimensionXsmall != theme.dimensions.dimensionSmall)
        #expect(theme.dimensions.dimensionXsmall != theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimensionXsmall != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimensionXsmall != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimensionXsmall != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimensionXsmall != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimensionXsmall != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimensionXsmall != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimensionXsmall != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimensionXsmall != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimensionXsmall != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimensionXsmall != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimensionXsmall != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimensionXsmall != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimensionSmall != theme.dimensions.dimensionMedium)
        #expect(theme.dimensions.dimensionSmall != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimensionSmall != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimensionSmall != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimensionSmall != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimensionSmall != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimensionSmall != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimensionSmall != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimensionSmall != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimensionSmall != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimensionSmall != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimensionSmall != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimensionSmall != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimensionMedium != theme.dimensions.dimensionLarge)
        #expect(theme.dimensions.dimensionMedium != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimensionMedium != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimensionMedium != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimensionMedium != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimensionMedium != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimensionMedium != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimensionMedium != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimensionMedium != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimensionMedium != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimensionMedium != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimensionMedium != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimensionLarge != theme.dimensions.dimensionXlarge)
        #expect(theme.dimensions.dimensionLarge != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimensionLarge != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimensionLarge != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimensionLarge != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimensionLarge != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimensionLarge != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimensionLarge != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimensionLarge != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimensionLarge != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimensionLarge != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimensionXlarge != theme.dimensions.dimension2xlarge)
        #expect(theme.dimensions.dimensionXlarge != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimensionXlarge != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimensionXlarge != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimensionXlarge != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimensionXlarge != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimensionXlarge != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimensionXlarge != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimensionXlarge != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimensionXlarge != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension2xlarge != theme.dimensions.dimension3xlarge)
        #expect(theme.dimensions.dimension2xlarge != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimension2xlarge != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension2xlarge != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension2xlarge != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension2xlarge != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension2xlarge != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension2xlarge != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension2xlarge != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension3xlarge != theme.dimensions.dimension4xlarge)
        #expect(theme.dimensions.dimension3xlarge != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension3xlarge != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension3xlarge != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension3xlarge != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension3xlarge != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension3xlarge != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension3xlarge != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension4xlarge != theme.dimensions.dimension5xlarge)
        #expect(theme.dimensions.dimension4xlarge != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension4xlarge != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension4xlarge != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension4xlarge != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension4xlarge != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension4xlarge != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension5xlarge != theme.dimensions.dimension6xlarge)
        #expect(theme.dimensions.dimension5xlarge != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension5xlarge != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension5xlarge != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension5xlarge != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension5xlarge != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension6xlarge != theme.dimensions.dimension7xlarge)
        #expect(theme.dimensions.dimension6xlarge != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension6xlarge != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension6xlarge != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension6xlarge != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension7xlarge != theme.dimensions.dimension8xlarge)
        #expect(theme.dimensions.dimension7xlarge != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension7xlarge != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension7xlarge != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension8xlarge != theme.dimensions.dimension9xlarge)
        #expect(theme.dimensions.dimension8xlarge != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension8xlarge != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension9xlarge != theme.dimensions.dimension10xlarge)
        #expect(theme.dimensions.dimension9xlarge != theme.dimensions.dimension11xlarge)

        #expect(theme.dimensions.dimension10xlarge != theme.dimensions.dimension11xlarge)
    }
}

// swiftlint:enable function_body_length
// swiftlint:enable type_body_length
