//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import OUDS
import OUDSThemesOrangeBusinessTools
import Testing

// swiftlint:disable function_body_length
// swiftlint:disable type_body_length

/// Checks if the closed semantic tokens of _s, as defined in the OrangeBusinessTools theme, have expected values and relationships
/// between them.
struct DimensionSemanticTokensValuesTests {

    private var theme: OUDSTheme

    init() {
        theme = OrangeBusinessToolsTheme()
    }

    @Test func dimensionsAreSmallerOneByOne() throws {
        #expect(theme._s._None < theme._s._12xsmall)
        #expect(theme._s._12xsmall < theme._s._11xsmall)
        #expect(theme._s._11xsmall < theme._s._10xsmall)
        #expect(theme._s._10xsmall < theme._s._9xsmall)
        #expect(theme._s._9xsmall < theme._s._8xsmall)
        #expect(theme._s._8xsmall < theme._s._7xsmall)
        #expect(theme._s._7xsmall <= theme._s._6xsmall) // Confirmed by Mdesign team, can be equal
        #expect(theme._s._6xsmall < theme._s._5xsmall)
        #expect(theme._s._5xsmall < theme._s._4xsmall)
        #expect(theme._s._4xsmall < theme._s._3xsmall)
        #expect(theme._s._3xsmall < theme._s._2xsmall)
        #expect(theme._s._2xsmall < theme._s._Xsmall)
        #expect(theme._s._Xsmall < theme._s._Small)
        #expect(theme._s._Small < theme._s._Medium)
        #expect(theme._s._Medium < theme._s._Large)
        #expect(theme._s._Large < theme._s._Xlarge)
        #expect(theme._s._Xlarge < theme._s._2xlarge)
        #expect(theme._s._2xlarge < theme._s._3xlarge)
        #expect(theme._s._3xlarge < theme._s._4xlarge)
        #expect(theme._s._4xlarge < theme._s._5xlarge)
        #expect(theme._s._5xlarge < theme._s._6xlarge)
        #expect(theme._s._6xlarge < theme._s._7xlarge)
        #expect(theme._s._7xlarge < theme._s._8xlarge)
        #expect(theme._s._8xlarge < theme._s._9xlarge)
        #expect(theme._s._9xlarge < theme._s._10xlarge)
        #expect(theme._s._10xlarge < theme._s._11xlarge)
    }

    @Test func dimensionsAreAllUnique() throws {
        #expect(theme._s._None != theme._s._12xsmall)
        #expect(theme._s._None != theme._s._11xsmall)
        #expect(theme._s._None != theme._s._10xsmall)
        #expect(theme._s._None != theme._s._9xsmall)
        #expect(theme._s._None != theme._s._8xsmall)
        #expect(theme._s._None != theme._s._7xsmall)
        #expect(theme._s._None != theme._s._6xsmall)
        #expect(theme._s._None != theme._s._5xsmall)
        #expect(theme._s._None != theme._s._4xsmall)
        #expect(theme._s._None != theme._s._3xsmall)
        #expect(theme._s._None != theme._s._2xsmall)
        #expect(theme._s._None != theme._s._Xsmall)
        #expect(theme._s._None != theme._s._Small)
        #expect(theme._s._None != theme._s._Medium)
        #expect(theme._s._None != theme._s._Large)
        #expect(theme._s._None != theme._s._Xlarge)
        #expect(theme._s._None != theme._s._2xlarge)
        #expect(theme._s._None != theme._s._3xlarge)
        #expect(theme._s._None != theme._s._4xlarge)
        #expect(theme._s._None != theme._s._5xlarge)
        #expect(theme._s._None != theme._s._6xlarge)
        #expect(theme._s._None != theme._s._7xlarge)
        #expect(theme._s._None != theme._s._8xlarge)
        #expect(theme._s._None != theme._s._9xlarge)
        #expect(theme._s._None != theme._s._10xlarge)
        #expect(theme._s._None != theme._s._11xlarge)

        #expect(theme._s._12xsmall != theme._s._11xsmall)
        #expect(theme._s._12xsmall != theme._s._10xsmall)
        #expect(theme._s._12xsmall != theme._s._9xsmall)
        #expect(theme._s._12xsmall != theme._s._8xsmall)
        #expect(theme._s._12xsmall != theme._s._7xsmall)
        #expect(theme._s._12xsmall != theme._s._6xsmall)
        #expect(theme._s._12xsmall != theme._s._5xsmall)
        #expect(theme._s._12xsmall != theme._s._4xsmall)
        #expect(theme._s._12xsmall != theme._s._3xsmall)
        #expect(theme._s._12xsmall != theme._s._2xsmall)
        #expect(theme._s._12xsmall != theme._s._Xsmall)
        #expect(theme._s._12xsmall != theme._s._Small)
        #expect(theme._s._12xsmall != theme._s._Medium)
        #expect(theme._s._12xsmall != theme._s._Large)
        #expect(theme._s._12xsmall != theme._s._Xlarge)
        #expect(theme._s._12xsmall != theme._s._2xlarge)
        #expect(theme._s._12xsmall != theme._s._3xlarge)
        #expect(theme._s._12xsmall != theme._s._4xlarge)
        #expect(theme._s._12xsmall != theme._s._5xlarge)
        #expect(theme._s._12xsmall != theme._s._6xlarge)
        #expect(theme._s._12xsmall != theme._s._7xlarge)
        #expect(theme._s._12xsmall != theme._s._8xlarge)
        #expect(theme._s._12xsmall != theme._s._9xlarge)
        #expect(theme._s._12xsmall != theme._s._10xlarge)
        #expect(theme._s._12xsmall != theme._s._11xlarge)

        #expect(theme._s._11xsmall != theme._s._10xsmall)
        #expect(theme._s._11xsmall != theme._s._9xsmall)
        #expect(theme._s._11xsmall != theme._s._8xsmall)
        #expect(theme._s._11xsmall != theme._s._7xsmall)
        #expect(theme._s._11xsmall != theme._s._6xsmall)
        #expect(theme._s._11xsmall != theme._s._5xsmall)
        #expect(theme._s._11xsmall != theme._s._4xsmall)
        #expect(theme._s._11xsmall != theme._s._3xsmall)
        #expect(theme._s._11xsmall != theme._s._2xsmall)
        #expect(theme._s._11xsmall != theme._s._Xsmall)
        #expect(theme._s._11xsmall != theme._s._Small)
        #expect(theme._s._11xsmall != theme._s._Medium)
        #expect(theme._s._11xsmall != theme._s._Large)
        #expect(theme._s._11xsmall != theme._s._Xlarge)
        #expect(theme._s._11xsmall != theme._s._2xlarge)
        #expect(theme._s._11xsmall != theme._s._3xlarge)
        #expect(theme._s._11xsmall != theme._s._4xlarge)
        #expect(theme._s._11xsmall != theme._s._5xlarge)
        #expect(theme._s._11xsmall != theme._s._6xlarge)
        #expect(theme._s._11xsmall != theme._s._7xlarge)
        #expect(theme._s._11xsmall != theme._s._8xlarge)
        #expect(theme._s._11xsmall != theme._s._9xlarge)
        #expect(theme._s._11xsmall != theme._s._10xlarge)
        #expect(theme._s._11xsmall != theme._s._11xlarge)

        #expect(theme._s._10xsmall != theme._s._9xsmall)
        #expect(theme._s._10xsmall != theme._s._8xsmall)
        #expect(theme._s._10xsmall != theme._s._7xsmall)
        #expect(theme._s._10xsmall != theme._s._6xsmall)
        #expect(theme._s._10xsmall != theme._s._5xsmall)
        #expect(theme._s._10xsmall != theme._s._4xsmall)
        #expect(theme._s._10xsmall != theme._s._3xsmall)
        #expect(theme._s._10xsmall != theme._s._2xsmall)
        #expect(theme._s._10xsmall != theme._s._Xsmall)
        #expect(theme._s._10xsmall != theme._s._Small)
        #expect(theme._s._10xsmall != theme._s._Medium)
        #expect(theme._s._10xsmall != theme._s._Large)
        #expect(theme._s._10xsmall != theme._s._Xlarge)
        #expect(theme._s._10xsmall != theme._s._2xlarge)
        #expect(theme._s._10xsmall != theme._s._3xlarge)
        #expect(theme._s._10xsmall != theme._s._4xlarge)
        #expect(theme._s._10xsmall != theme._s._5xlarge)
        #expect(theme._s._10xsmall != theme._s._6xlarge)
        #expect(theme._s._10xsmall != theme._s._7xlarge)
        #expect(theme._s._10xsmall != theme._s._8xlarge)
        #expect(theme._s._10xsmall != theme._s._9xlarge)
        #expect(theme._s._10xsmall != theme._s._10xlarge)
        #expect(theme._s._10xsmall != theme._s._11xlarge)

        #expect(theme._s._9xsmall != theme._s._8xsmall)
        #expect(theme._s._9xsmall != theme._s._7xsmall)
        #expect(theme._s._9xsmall != theme._s._6xsmall)
        #expect(theme._s._9xsmall != theme._s._5xsmall)
        #expect(theme._s._9xsmall != theme._s._4xsmall)
        #expect(theme._s._9xsmall != theme._s._3xsmall)
        #expect(theme._s._9xsmall != theme._s._2xsmall)
        #expect(theme._s._9xsmall != theme._s._Xsmall)
        #expect(theme._s._9xsmall != theme._s._Small)
        #expect(theme._s._9xsmall != theme._s._Medium)
        #expect(theme._s._9xsmall != theme._s._Large)
        #expect(theme._s._9xsmall != theme._s._Xlarge)
        #expect(theme._s._9xsmall != theme._s._2xlarge)
        #expect(theme._s._9xsmall != theme._s._3xlarge)
        #expect(theme._s._9xsmall != theme._s._4xlarge)
        #expect(theme._s._9xsmall != theme._s._5xlarge)
        #expect(theme._s._9xsmall != theme._s._6xlarge)
        #expect(theme._s._9xsmall != theme._s._7xlarge)
        #expect(theme._s._9xsmall != theme._s._8xlarge)
        #expect(theme._s._9xsmall != theme._s._9xlarge)
        #expect(theme._s._9xsmall != theme._s._10xlarge)
        #expect(theme._s._9xsmall != theme._s._11xlarge)

        #expect(theme._s._8xsmall != theme._s._7xsmall)
        #expect(theme._s._8xsmall != theme._s._6xsmall)
        #expect(theme._s._8xsmall != theme._s._5xsmall)
        #expect(theme._s._8xsmall != theme._s._4xsmall)
        #expect(theme._s._8xsmall != theme._s._3xsmall)
        #expect(theme._s._8xsmall != theme._s._2xsmall)
        #expect(theme._s._8xsmall != theme._s._Xsmall)
        #expect(theme._s._8xsmall != theme._s._Small)
        #expect(theme._s._8xsmall != theme._s._Medium)
        #expect(theme._s._8xsmall != theme._s._Large)
        #expect(theme._s._8xsmall != theme._s._Xlarge)
        #expect(theme._s._8xsmall != theme._s._2xlarge)
        #expect(theme._s._8xsmall != theme._s._3xlarge)
        #expect(theme._s._8xsmall != theme._s._4xlarge)
        #expect(theme._s._8xsmall != theme._s._5xlarge)
        #expect(theme._s._8xsmall != theme._s._6xlarge)
        #expect(theme._s._8xsmall != theme._s._7xlarge)
        #expect(theme._s._8xsmall != theme._s._8xlarge)
        #expect(theme._s._8xsmall != theme._s._9xlarge)
        #expect(theme._s._8xsmall != theme._s._10xlarge)
        #expect(theme._s._8xsmall != theme._s._11xlarge)

        // Confirmed by Mdesign team, can be equal
        // #expect(theme._s._7xsmall != theme._s._6xsmall)

        #expect(theme._s._7xsmall != theme._s._5xsmall)
        #expect(theme._s._7xsmall != theme._s._4xsmall)
        #expect(theme._s._7xsmall != theme._s._3xsmall)
        #expect(theme._s._7xsmall != theme._s._2xsmall)
        #expect(theme._s._7xsmall != theme._s._Xsmall)
        #expect(theme._s._7xsmall != theme._s._Small)
        #expect(theme._s._7xsmall != theme._s._Medium)
        #expect(theme._s._7xsmall != theme._s._Large)
        #expect(theme._s._7xsmall != theme._s._Xlarge)
        #expect(theme._s._7xsmall != theme._s._2xlarge)
        #expect(theme._s._7xsmall != theme._s._3xlarge)
        #expect(theme._s._7xsmall != theme._s._4xlarge)
        #expect(theme._s._7xsmall != theme._s._5xlarge)
        #expect(theme._s._7xsmall != theme._s._6xlarge)
        #expect(theme._s._7xsmall != theme._s._7xlarge)
        #expect(theme._s._7xsmall != theme._s._8xlarge)
        #expect(theme._s._7xsmall != theme._s._9xlarge)
        #expect(theme._s._7xsmall != theme._s._10xlarge)
        #expect(theme._s._7xsmall != theme._s._11xlarge)

        #expect(theme._s._6xsmall != theme._s._5xsmall)
        #expect(theme._s._6xsmall != theme._s._4xsmall)
        #expect(theme._s._6xsmall != theme._s._3xsmall)
        #expect(theme._s._6xsmall != theme._s._2xsmall)
        #expect(theme._s._6xsmall != theme._s._Xsmall)
        #expect(theme._s._6xsmall != theme._s._Small)
        #expect(theme._s._6xsmall != theme._s._Medium)
        #expect(theme._s._6xsmall != theme._s._Large)
        #expect(theme._s._6xsmall != theme._s._Xlarge)
        #expect(theme._s._6xsmall != theme._s._2xlarge)
        #expect(theme._s._6xsmall != theme._s._3xlarge)
        #expect(theme._s._6xsmall != theme._s._4xlarge)
        #expect(theme._s._6xsmall != theme._s._5xlarge)
        #expect(theme._s._6xsmall != theme._s._6xlarge)
        #expect(theme._s._6xsmall != theme._s._7xlarge)
        #expect(theme._s._6xsmall != theme._s._8xlarge)
        #expect(theme._s._6xsmall != theme._s._9xlarge)
        #expect(theme._s._6xsmall != theme._s._10xlarge)
        #expect(theme._s._6xsmall != theme._s._11xlarge)

        #expect(theme._s._5xsmall != theme._s._4xsmall)
        #expect(theme._s._5xsmall != theme._s._3xsmall)
        #expect(theme._s._5xsmall != theme._s._2xsmall)
        #expect(theme._s._5xsmall != theme._s._Xsmall)
        #expect(theme._s._5xsmall != theme._s._Small)
        #expect(theme._s._5xsmall != theme._s._Medium)
        #expect(theme._s._5xsmall != theme._s._Large)
        #expect(theme._s._5xsmall != theme._s._Xlarge)
        #expect(theme._s._5xsmall != theme._s._2xlarge)
        #expect(theme._s._5xsmall != theme._s._3xlarge)
        #expect(theme._s._5xsmall != theme._s._4xlarge)
        #expect(theme._s._5xsmall != theme._s._5xlarge)
        #expect(theme._s._5xsmall != theme._s._6xlarge)
        #expect(theme._s._5xsmall != theme._s._7xlarge)
        #expect(theme._s._5xsmall != theme._s._8xlarge)
        #expect(theme._s._5xsmall != theme._s._9xlarge)
        #expect(theme._s._5xsmall != theme._s._10xlarge)
        #expect(theme._s._5xsmall != theme._s._11xlarge)

        #expect(theme._s._4xsmall != theme._s._3xsmall)
        #expect(theme._s._4xsmall != theme._s._2xsmall)
        #expect(theme._s._4xsmall != theme._s._Xsmall)
        #expect(theme._s._4xsmall != theme._s._Small)
        #expect(theme._s._4xsmall != theme._s._Medium)
        #expect(theme._s._4xsmall != theme._s._Large)
        #expect(theme._s._4xsmall != theme._s._Xlarge)
        #expect(theme._s._4xsmall != theme._s._2xlarge)
        #expect(theme._s._4xsmall != theme._s._3xlarge)
        #expect(theme._s._4xsmall != theme._s._4xlarge)
        #expect(theme._s._4xsmall != theme._s._5xlarge)
        #expect(theme._s._4xsmall != theme._s._6xlarge)
        #expect(theme._s._4xsmall != theme._s._7xlarge)
        #expect(theme._s._4xsmall != theme._s._8xlarge)
        #expect(theme._s._4xsmall != theme._s._9xlarge)
        #expect(theme._s._4xsmall != theme._s._10xlarge)
        #expect(theme._s._4xsmall != theme._s._11xlarge)

        #expect(theme._s._3xsmall != theme._s._2xsmall)
        #expect(theme._s._3xsmall != theme._s._Xsmall)
        #expect(theme._s._3xsmall != theme._s._Small)
        #expect(theme._s._3xsmall != theme._s._Medium)
        #expect(theme._s._3xsmall != theme._s._Large)
        #expect(theme._s._3xsmall != theme._s._Xlarge)
        #expect(theme._s._3xsmall != theme._s._2xlarge)
        #expect(theme._s._3xsmall != theme._s._3xlarge)
        #expect(theme._s._3xsmall != theme._s._4xlarge)
        #expect(theme._s._3xsmall != theme._s._5xlarge)
        #expect(theme._s._3xsmall != theme._s._6xlarge)
        #expect(theme._s._3xsmall != theme._s._7xlarge)
        #expect(theme._s._3xsmall != theme._s._8xlarge)
        #expect(theme._s._3xsmall != theme._s._9xlarge)
        #expect(theme._s._3xsmall != theme._s._10xlarge)
        #expect(theme._s._3xsmall != theme._s._11xlarge)

        #expect(theme._s._2xsmall != theme._s._Xsmall)
        #expect(theme._s._2xsmall != theme._s._Small)
        #expect(theme._s._2xsmall != theme._s._Medium)
        #expect(theme._s._2xsmall != theme._s._Large)
        #expect(theme._s._2xsmall != theme._s._Xlarge)
        #expect(theme._s._2xsmall != theme._s._2xlarge)
        #expect(theme._s._2xsmall != theme._s._3xlarge)
        #expect(theme._s._2xsmall != theme._s._4xlarge)
        #expect(theme._s._2xsmall != theme._s._5xlarge)
        #expect(theme._s._2xsmall != theme._s._6xlarge)
        #expect(theme._s._2xsmall != theme._s._7xlarge)
        #expect(theme._s._2xsmall != theme._s._8xlarge)
        #expect(theme._s._2xsmall != theme._s._9xlarge)
        #expect(theme._s._2xsmall != theme._s._10xlarge)
        #expect(theme._s._2xsmall != theme._s._11xlarge)

        #expect(theme._s._Xsmall != theme._s._Small)
        #expect(theme._s._Xsmall != theme._s._Medium)
        #expect(theme._s._Xsmall != theme._s._Large)
        #expect(theme._s._Xsmall != theme._s._Xlarge)
        #expect(theme._s._Xsmall != theme._s._2xlarge)
        #expect(theme._s._Xsmall != theme._s._3xlarge)
        #expect(theme._s._Xsmall != theme._s._4xlarge)
        #expect(theme._s._Xsmall != theme._s._5xlarge)
        #expect(theme._s._Xsmall != theme._s._6xlarge)
        #expect(theme._s._Xsmall != theme._s._7xlarge)
        #expect(theme._s._Xsmall != theme._s._8xlarge)
        #expect(theme._s._Xsmall != theme._s._9xlarge)
        #expect(theme._s._Xsmall != theme._s._10xlarge)
        #expect(theme._s._Xsmall != theme._s._11xlarge)

        #expect(theme._s._Small != theme._s._Medium)
        #expect(theme._s._Small != theme._s._Large)
        #expect(theme._s._Small != theme._s._Xlarge)
        #expect(theme._s._Small != theme._s._2xlarge)
        #expect(theme._s._Small != theme._s._3xlarge)
        #expect(theme._s._Small != theme._s._4xlarge)
        #expect(theme._s._Small != theme._s._5xlarge)
        #expect(theme._s._Small != theme._s._6xlarge)
        #expect(theme._s._Small != theme._s._7xlarge)
        #expect(theme._s._Small != theme._s._8xlarge)
        #expect(theme._s._Small != theme._s._9xlarge)
        #expect(theme._s._Small != theme._s._10xlarge)
        #expect(theme._s._Small != theme._s._11xlarge)

        #expect(theme._s._Medium != theme._s._Large)
        #expect(theme._s._Medium != theme._s._Xlarge)
        #expect(theme._s._Medium != theme._s._2xlarge)
        #expect(theme._s._Medium != theme._s._3xlarge)
        #expect(theme._s._Medium != theme._s._4xlarge)
        #expect(theme._s._Medium != theme._s._5xlarge)
        #expect(theme._s._Medium != theme._s._6xlarge)
        #expect(theme._s._Medium != theme._s._7xlarge)
        #expect(theme._s._Medium != theme._s._8xlarge)
        #expect(theme._s._Medium != theme._s._9xlarge)
        #expect(theme._s._Medium != theme._s._10xlarge)
        #expect(theme._s._Medium != theme._s._11xlarge)

        #expect(theme._s._Large != theme._s._Xlarge)
        #expect(theme._s._Large != theme._s._2xlarge)
        #expect(theme._s._Large != theme._s._3xlarge)
        #expect(theme._s._Large != theme._s._4xlarge)
        #expect(theme._s._Large != theme._s._5xlarge)
        #expect(theme._s._Large != theme._s._6xlarge)
        #expect(theme._s._Large != theme._s._7xlarge)
        #expect(theme._s._Large != theme._s._8xlarge)
        #expect(theme._s._Large != theme._s._9xlarge)
        #expect(theme._s._Large != theme._s._10xlarge)
        #expect(theme._s._Large != theme._s._11xlarge)

        #expect(theme._s._Xlarge != theme._s._2xlarge)
        #expect(theme._s._Xlarge != theme._s._3xlarge)
        #expect(theme._s._Xlarge != theme._s._4xlarge)
        #expect(theme._s._Xlarge != theme._s._5xlarge)
        #expect(theme._s._Xlarge != theme._s._6xlarge)
        #expect(theme._s._Xlarge != theme._s._7xlarge)
        #expect(theme._s._Xlarge != theme._s._8xlarge)
        #expect(theme._s._Xlarge != theme._s._9xlarge)
        #expect(theme._s._Xlarge != theme._s._10xlarge)
        #expect(theme._s._Xlarge != theme._s._11xlarge)

        #expect(theme._s._2xlarge != theme._s._3xlarge)
        #expect(theme._s._2xlarge != theme._s._4xlarge)
        #expect(theme._s._2xlarge != theme._s._5xlarge)
        #expect(theme._s._2xlarge != theme._s._6xlarge)
        #expect(theme._s._2xlarge != theme._s._7xlarge)
        #expect(theme._s._2xlarge != theme._s._8xlarge)
        #expect(theme._s._2xlarge != theme._s._9xlarge)
        #expect(theme._s._2xlarge != theme._s._10xlarge)
        #expect(theme._s._2xlarge != theme._s._11xlarge)

        #expect(theme._s._3xlarge != theme._s._4xlarge)
        #expect(theme._s._3xlarge != theme._s._5xlarge)
        #expect(theme._s._3xlarge != theme._s._6xlarge)
        #expect(theme._s._3xlarge != theme._s._7xlarge)
        #expect(theme._s._3xlarge != theme._s._8xlarge)
        #expect(theme._s._3xlarge != theme._s._9xlarge)
        #expect(theme._s._3xlarge != theme._s._10xlarge)
        #expect(theme._s._3xlarge != theme._s._11xlarge)

        #expect(theme._s._4xlarge != theme._s._5xlarge)
        #expect(theme._s._4xlarge != theme._s._6xlarge)
        #expect(theme._s._4xlarge != theme._s._7xlarge)
        #expect(theme._s._4xlarge != theme._s._8xlarge)
        #expect(theme._s._4xlarge != theme._s._9xlarge)
        #expect(theme._s._4xlarge != theme._s._10xlarge)
        #expect(theme._s._4xlarge != theme._s._11xlarge)

        #expect(theme._s._5xlarge != theme._s._6xlarge)
        #expect(theme._s._5xlarge != theme._s._7xlarge)
        #expect(theme._s._5xlarge != theme._s._8xlarge)
        #expect(theme._s._5xlarge != theme._s._9xlarge)
        #expect(theme._s._5xlarge != theme._s._10xlarge)
        #expect(theme._s._5xlarge != theme._s._11xlarge)

        #expect(theme._s._6xlarge != theme._s._7xlarge)
        #expect(theme._s._6xlarge != theme._s._8xlarge)
        #expect(theme._s._6xlarge != theme._s._9xlarge)
        #expect(theme._s._6xlarge != theme._s._10xlarge)
        #expect(theme._s._6xlarge != theme._s._11xlarge)

        #expect(theme._s._7xlarge != theme._s._8xlarge)
        #expect(theme._s._7xlarge != theme._s._9xlarge)
        #expect(theme._s._7xlarge != theme._s._10xlarge)
        #expect(theme._s._7xlarge != theme._s._11xlarge)

        #expect(theme._s._8xlarge != theme._s._9xlarge)
        #expect(theme._s._8xlarge != theme._s._10xlarge)
        #expect(theme._s._8xlarge != theme._s._11xlarge)

        #expect(theme._s._9xlarge != theme._s._10xlarge)
        #expect(theme._s._9xlarge != theme._s._11xlarge)

        #expect(theme._s._10xlarge != theme._s._11xlarge)
    }
}

// swiftlint:enable function_body_length
// swiftlint:enable type_body_length
