//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensSemantic

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

// swiftlint:disable line_length

/// Defines provider objects for `ColorSemanticTokens` so as to pack them as light and dark mode colors.
/// Helps to expose color semantic tokens with two values to use depending to the color scheme (*Figma* cannot manage such tokens and generate them).
extension OrangeBusinessToolsThemeColorSemanticTokensProvider: ColorMultipleSemanticTokens {

    // MARK: - Color - Opacity

    @objc public final var opacityLowest: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: opacityLowestLight, dark: opacityLowestDark) }

    @objc public final var opacityLower: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: opacityLowerLight, dark: opacityLowerDark) }

    @objc public final var opacityTransparent: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: opacityTransparentLight, dark: opacityTransparentDark) }

    // MARK: - Color - Action

    @objc public final var actionDisabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionDisabledLight, dark: actionDisabledDark) }

    @objc public final var actionEnabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionEnabledLight, dark: actionEnabledDark) }

    @objc public final var actionFocus: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionFocusLight, dark: actionFocusDark) }

    @objc public final var actionHighlighted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionHighlightedLight, dark: actionHighlightedDark) }

    @objc public final var actionHover: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionHoverLight, dark: actionHoverDark) }

    @objc public final var actionLoading: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionLoadingLight, dark: actionLoadingDark) }

    @objc public final var actionNegativeEnabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionNegativeEnabledLight, dark: actionNegativeEnabledDark) }

    @objc public final var actionNegativeFocus: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionNegativeFocusLight, dark: actionNegativeFocusDark) }

    @objc public final var actionNegativeHover: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionNegativeHoverLight, dark: actionNegativeHoverDark) }

    @objc public final var actionNegativeLoading: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionNegativeLoadingLight, dark: actionNegativeLoadingDark) }

    @objc public final var actionNegativePressed: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionNegativePressedLight, dark: actionNegativePressedDark) }

    @objc public final var actionPressed: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionPressedLight, dark: actionPressedDark) }

    @objc public final var actionSelected: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionSelectedLight, dark: actionSelectedDark) }

    @objc public final var actionSupportEnabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionSupportEnabledLight, dark: actionSupportEnabledDark) }

    @objc public final var actionSupportDisabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionSupportDisabledLight, dark: actionSupportDisabledDark) }

    @objc public final var actionSupportFocus: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionSupportFocusLight, dark: actionSupportFocusDark) }

    @objc public final var actionSupportHover: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionSupportHoverLight, dark: actionSupportHoverDark) }

    @objc public final var actionSupportLoading: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionSupportLoadingLight, dark: actionSupportLoadingDark) }

    @objc public final var actionSupportPressed: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionSupportPressedLight, dark: actionSupportPressedDark) }

    @objc public final var actionVisited: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionVisitedLight, dark: actionVisitedDark) }

    @objc public final var actionReadOnlyPrimary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionReadOnlyPrimaryLight, dark: actionReadOnlyPrimaryDark) }

    @objc public final var actionReadOnlySecondary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionReadOnlySecondaryLight, dark: actionReadOnlySecondaryDark) }

    @objc public final var actionAccent: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: actionAccentLight, dark: actionAccentDark) }

    // MARK: - Color - Background

    @objc public final var bgPrimary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: bgPrimaryLight, dark: bgPrimaryDark) }

    @objc public final var bgSecondary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: bgSecondaryLight, dark: bgSecondaryDark) }

    @objc public final var bgTertiary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: bgTertiaryLight, dark: bgTertiaryDark) }

    @objc public final var bgInverseLow: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: bgInverseLowLight, dark: bgInverseLowDark) }

    @objc public final var bgInverseHigh: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: bgInverseHighLight, dark: bgInverseHighDark) }

    // MARK: - Color - Border

    @objc public final var borderBrandPrimary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: borderBrandPrimaryLight, dark: borderBrandPrimaryDark) }

    @objc public final var borderBrandSecondary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: borderBrandSecondaryLight, dark: borderBrandSecondaryDark) }

    @objc public final var borderBrandTertiary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: borderBrandTertiaryLight, dark: borderBrandTertiaryDark) }

    @objc public final var borderDefault: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: borderDefaultLight, dark: borderDefaultDark) }

    @objc public final var borderEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: borderEmphasizedLight, dark: borderEmphasizedDark) }

    @objc public final var borderFocus: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: borderFocusLight, dark: borderFocusDark) }

    @objc public final var borderFocusInset: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: borderFocusInsetLight, dark: borderFocusInsetDark) }

    @objc public final var borderMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: borderMutedLight, dark: borderMutedDark) }

    @objc public final var borderOnBrandPrimary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: borderOnBrandPrimaryLight, dark: borderOnBrandPrimaryDark) }

    @objc public final var borderOnBrandSecondary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: borderOnBrandSecondaryLight, dark: borderOnBrandSecondaryDark) }

    @objc public final var borderOnBrandTertiary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: borderOnBrandTertiaryLight, dark: borderOnBrandTertiaryDark) }

    @objc public final var borderMinmal: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: borderMinimalLight, dark: borderMinimalDark) }

    // MARK: - Color - Content

    @objc public final var contentBrandPrimary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentBrandPrimaryLight, dark: contentBrandPrimaryDark) }

    @objc public final var contentBrandSecondary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentBrandSecondaryLight, dark: contentBrandSecondaryDark) }

    @objc public final var contentBrandTertiary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentBrandTertiaryLight, dark: contentBrandTertiaryDark) }

    @objc public final var contentDefault: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentDefaultLight, dark: contentDefaultDark) }

    @objc public final var contentDisabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentDisabledLight, dark: contentDisabledDark) }

    @objc public final var contentMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentMutedLight, dark: contentMutedDark) }

    @objc public final var contentOnActionSelected: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnActionSelectedLight, dark: contentOnActionSelectedDark) }

    @objc public final var contentOnActionDisabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnActionDisabledLight, dark: contentOnActionDisabledDark) }

    @objc public final var contentOnActionEnabled: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnActionEnabledLight, dark: contentOnActionEnabledDark) }

    @objc public final var contentOnActionFocus: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnActionFocusLight, dark: contentOnActionFocusDark) }

    @objc public final var contentOnActionHighlighted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnActionHighlightedLight, dark: contentOnActionHighlightedDark) }

    @objc public final var contentOnActionHover: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnActionHoverLight, dark: contentOnActionHoverDark) }

    @objc public final var contentOnActionLoading: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnActionLoadingLight, dark: contentOnActionLoadingDark) }

    @objc public final var contentOnActionPressed: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnActionPressedLight, dark: contentOnActionPressedDark) }

    @objc public final var contentOnBrandPrimary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnBrandPrimaryLight, dark: contentOnBrandPrimaryDark) }

    @objc public final var contentOnBrandSecondary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnBrandSecondaryLight, dark: contentOnBrandSecondaryDark) }

    @objc public final var contentOnBrandTertiary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnBrandTertiaryLight, dark: contentOnBrandTertiaryDark) }

    @objc public final var contentOnStatusPositiveMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnStatusPositiveMutedLight, dark: contentOnStatusPositiveMutedDark) }

    @objc public final var contentOnStatusPositiveEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnStatusPositiveEmphasizedLight, dark: contentOnStatusPositiveEmphasizedDark) }

    @objc public final var contentOnStatusWarningMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnStatusWarningMutedLight, dark: contentOnStatusWarningMutedDark) }

    @objc public final var contentOnStatusWarningEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnStatusWarningEmphasizedLight, dark: contentOnStatusWarningEmphasizedDark) }

    @objc public final var contentInverse: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentInverseLight, dark: contentInverseDark) }

    @objc public final var contentOnStatusNegativeMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnStatusNegativeMutedLight, dark: contentOnStatusNegativeMutedDark) }

    @objc public final var contentOnStatusNegativeEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnStatusNegativeEmphasizedLight, dark: contentOnStatusNegativeEmphasizedDark) }

    @objc public final var contentOnStatusInfoMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnStatusInfoMutedLight, dark: contentOnStatusInfoMutedDark) }

    @objc public final var contentOnStatusInfoEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnStatusInfoEmphasizedLight, dark: contentOnStatusInfoEmphasizedDark) }

    @objc public final var contentOnStatusAccentMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnStatusAccentMutedLight, dark: contentOnStatusAccentMutedDark) }

    @objc public final var contentOnStatusAccentEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentOnStatusAccentEmphasizedLight, dark: contentOnStatusAccentEmphasizedDark) }

    @objc public final var contentStatusAccent: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentStatusAccentLight, dark: contentStatusAccentDark) }

    @objc public final var contentStatusInfo: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentStatusInfoLight, dark: contentStatusInfoDark) }

    @objc public final var contentStatusNegative: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentStatusNegativeLight, dark: contentStatusNegativeDark) }

    @objc public final var contentStatusPositive: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentStatusPositiveLight, dark: contentStatusPositiveDark) }

    @objc public final var contentStatusWarning: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: contentStatusWarningLight, dark: contentStatusWarningDark) }

    // MARK: - Color - Overlay

    @objc public final var overlayDropdown: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: overlayDropdownLight, dark: overlayDropdownDark) }

    @objc public final var overlayDrag: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: overlayDragLight, dark: overlayDragDark) }

    @objc public final var overlayModal: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: overlayModalLight, dark: overlayModalDark) }

    // MARK: - Color - Surface

    @objc public final var surfaceBrandPrimary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceBrandPrimaryLight, dark: surfaceBrandPrimaryDark) }

    @objc public final var surfaceBrandSecondary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceBrandSecondaryLight, dark: surfaceBrandSecondaryDark) }

    @objc public final var surfaceBrandTertiary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceBrandTertiaryLight, dark: surfaceBrandTertiaryDark) }

    @objc public final var surfaceStatusAccentEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceStatusAccentEmphasizedLight, dark: surfaceStatusAccentEmphasizedDark) }

    @objc public final var surfaceStatusAccentMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceStatusAccentMutedLight, dark: surfaceStatusAccentMutedDark) }

    @objc public final var surfaceStatusInfoEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceStatusInfoEmphasizedLight, dark: surfaceStatusInfoEmphasizedDark) }

    @objc public final var surfaceStatusInfoMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceStatusInfoMutedLight, dark: surfaceStatusInfoMutedDark) }

    @objc public final var surfaceStatusNegativeEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceStatusNegativeEmphasizedLight, dark: surfaceStatusNegativeEmphasizedDark) }

    @objc public final var surfaceStatusNegativeMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceStatusNegativeMutedLight, dark: surfaceStatusNegativeMutedDark) }

    @objc public final var surfaceInverseHigh: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceInverseHighLight, dark: surfaceInverseHighDark) }

    @objc public final var surfaceInverseLow: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceInverseLowLight, dark: surfaceInverseLowDark) }

    @objc public final var surfacePrimary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfacePrimaryLight, dark: surfacePrimaryDark) }

    @objc public final var surfaceSecondary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceSecondaryLight, dark: surfaceSecondaryDark) }

    @objc public final var surfaceTertiary: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceTertiaryLight, dark: surfaceTertiaryDark) }

    @objc public final var surfaceStatusPositiveEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceStatusPositiveEmphasizedLight, dark: surfaceStatusPositiveEmphasizedDark) }

    @objc public final var surfaceStatusPositiveMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceStatusPositiveMutedLight, dark: surfaceStatusPositiveMutedDark) }

    @objc public final var surfaceStatusWarningEmphasized: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceStatusWarningEmphasizedLight, dark: surfaceStatusWarningEmphasizedDark) }

    @objc public final var surfaceStatusWarningMuted: MultipleColorSemanticTokens { MultipleColorSemanticTokens(light: surfaceStatusWarningMutedLight, dark: surfaceStatusWarningMutedDark) }
}

// swiftlint:enable line_length
