//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

import Foundation
import OUDSTokensSemantic

// swiftlint:disable line_length

// [File not generated by the tokenator]
// WARNING: Not synchronized anymore with the Figjam / Figma by developers team
// Create an issue for update https://github.com/Orange-OpenSource/ouds-ios/issues/new?template=token_update.yml

/// Defines provider objects for size semantic tokens (i.e. in the end `DimensionRawTokens`).
extension OrangeBusinessToolsThemeSizeSemanticTokensProvider: SizeMultipleSemanticTokens {

    // MARK: - Semantic token - Sizing - Icon with typography

    @objc public final var sizeIconWithHeadingXlargeSizeSm: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithHeadingXlargeSizeSmMobile, regular: sizeIconWithHeadingXlargeSizeSmTablet) }
    @objc public final var sizeIconWithHeadingXlargeSizeMd: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithHeadingXlargeSizeMdMobile, regular: sizeIconWithHeadingXlargeSizeMdTablet) }
    @objc public final var sizeIconWithHeadingXlargeSizeLg: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithHeadingXlargeSizeLgMobile, regular: sizeIconWithHeadingXlargeSizeLgTablet) }

    @objc public final var sizeIconWithHeadingLargeSizeSm: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithHeadingLargeSizeSmMobile, regular: sizeIconWithHeadingLargeSizeSmTablet) }
    @objc public final var sizeIconWithHeadingLargeSizeMd: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithHeadingLargeSizeMdMobile, regular: sizeIconWithHeadingLargeSizeMdTablet) }
    @objc public final var sizeIconWithHeadingLargeSizeLg: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithHeadingLargeSizeLgMobile, regular: sizeIconWithHeadingLargeSizeLgTablet) }

    @objc public final var sizeIconWithHeadingMediumSizeSm: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithHeadingMediumSizeSmMobile, regular: sizeIconWithHeadingMediumSizeSmTablet) }
    @objc public final var sizeIconWithHeadingMediumSizeMd: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithHeadingMediumSizeMdMobile, regular: sizeIconWithHeadingMediumSizeMdTablet) }
    @objc public final var sizeIconWithHeadingMediumSizeLg: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithHeadingMediumSizeLgMobile, regular: sizeIconWithHeadingMediumSizeLgTablet) }

    @objc public final var sizeIconWithHeadingSmallSizeSm: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithHeadingSmallSizeSmMobile, regular: sizeIconWithHeadingSmallSizeSmTablet) }
    @objc public final var sizeIconWithHeadingSmallSizeMd: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithHeadingSmallSizeMdMobile, regular: sizeIconWithHeadingSmallSizeMdTablet) }
    @objc public final var sizeIconWithHeadingSmallSizeLg: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithHeadingSmallSizeLgMobile, regular: sizeIconWithHeadingSmallSizeLgTablet) }

    @objc public final var sizeIconWithBodyLargeSizeSm: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithBodyLargeSizeSmMobile, regular: sizeIconWithBodyLargeSizeSmTablet) }
    @objc public final var sizeIconWithBodyLargeSizeMd: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithBodyLargeSizeMdMobile, regular: sizeIconWithBodyLargeSizeMdTablet) }
    @objc public final var sizeIconWithBodyLargeSizeLg: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithBodyLargeSizeLgMobile, regular: sizeIconWithBodyLargeSizeLgTablet) }

    @objc public final var sizeIconWithBodyMediumSizeSm: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithBodyMediumSizeSmMobile, regular: sizeIconWithBodyMediumSizeSmTablet) }
    @objc public final var sizeIconWithBodyMediumSizeMd: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithBodyMediumSizeMdMobile, regular: sizeIconWithBodyMediumSizeMdTablet) }
    @objc public final var sizeIconWithBodyMediumSizeLg: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithBodyMediumSizeLgMobile, regular: sizeIconWithBodyMediumSizeLgTablet) }

    @objc public final var sizeIconWithBodySmallSizeSm: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithBodySmallSizeSmMobile, regular: sizeIconWithBodySmallSizeSmTablet) }
    @objc public final var sizeIconWithBodySmallSizeMd: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithBodySmallSizeMdMobile, regular: sizeIconWithBodySmallSizeMdTablet) }
    @objc public final var sizeIconWithBodySmallSizeLg: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeIconWithBodySmallSizeLgMobile, regular: sizeIconWithBodySmallSizeLgTablet) }

    // MARK: - Semantic token - Sizing - Max width typography

    @objc public final var sizeMaxWidthTypeDisplayLarge: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeMaxWidthTypeDisplayLargeMobile, regular: sizeMaxWidthTypeDisplayLargeTablet) }
    @objc public final var sizeMaxWidthTypeDisplayMedium: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeMaxWidthTypeDisplayMediumMobile, regular: sizeMaxWidthTypeDisplayMediumTablet) }
    @objc public final var sizeMaxWidthTypeDisplaySmall: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeMaxWidthTypeDisplaySmallMobile, regular: sizeMaxWidthTypeDisplaySmallTablet) }

    @objc public final var sizeMaxWidthTypeHeadingXlarge: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeMaxWidthTypeHeadingXlargeMobile, regular: sizeMaxWidthTypeHeadingXlargeTablet) }
    @objc public final var sizeMaxWidthTypeHeadingLarge: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeMaxWidthTypeHeadingLargeMobile, regular: sizeMaxWidthTypeHeadingLargeTablet) }
    @objc public final var sizeMaxWidthTypeHeadingMedium: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeMaxWidthTypeHeadingMediumMobile, regular: sizeMaxWidthTypeHeadingMediumTablet) }
    @objc public final var sizeMaxWidthTypeHeadingSmall: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeMaxWidthTypeHeadingSmallMobile, regular: sizeMaxWidthTypeHeadingSmallTablet) }

    @objc public final var sizeMaxWidthTypeBodyLarge: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeMaxWidthTypeBodyLargeMobile, regular: sizeMaxWidthTypeBodyLargeTablet) }
    @objc public final var sizeMaxWidthTypeBodyMedium: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeMaxWidthTypeBodyMediumMobile, regular: sizeMaxWidthTypeBodyMediumTablet) }
    @objc public final var sizeMaxWidthTypeBodySmall: MultipleSizeSemanticTokens { MultipleSizeSemanticTokens(compact: sizeMaxWidthTypeBodySmallMobile, regular: sizeMaxWidthTypeBodySmallTablet) }
}

// swiftlint:enable line_length
