//
// Software Name: OUDS iOS
// SPDX-FileCopyrightText: Copyright (c) Orange SA
// SPDX-License-Identifier: MIT
//
// This software is distributed under the MIT license,
// the text of which is available at https://opensource.org/license/MIT/
// or see the "LICENSE" file for more details.
//
// Authors: See CONTRIBUTORS.txt
// Software description: A SwiftUI components library with code examples for Orange Unified Design System
//

// 🤖 Generated by Tokenator

/// Gathers the components and themes versions exposed through Tokenator based on Figma tokens
public enum OUDSVersions {

    // MARK: - Themes versions

    /// Version of the Core tokens library (1.10.0)
    public static let themeCoreVersion = "1.10.0"

    /// Version of the Orange core tokens library (1.2.0)
    public static let themeOrangeCoreVersion = "1.2.0"
    /// Version of the Orange brand tokens library (2.5.0)
    public static let themeOrangeBrandVersion = "2.5.0"

    /// Version of the Sosh core tokens library (1.4.0)
    public static let themeSoshCoreVersion = "1.4.0"
    /// Version of the Sosh brand tokens library (2.5.0)
    public static let themeSoshBrandVersion = "2.5.0"

    /// Version of the Orange Compact brand tokens library (2.5.0)
    public static let themeOrangeCompactBrandVersion = "2.5.0"

    /// Version of the Wireframe core tokens library (1.4.0)
    public static let themeWireframeCoreVersion = "1.4.0"
    /// Version of the Wireframe brand tokens library (2.5.0)
    public static let themeWireframeBrandVersion = "2.5.0"

    // MARK: - Components versions - Actions

    /// Version of the Figma specifications for the component button (3.2.0)
    public static let componentButtonVersion = "3.2.0"

    // MARK: - Components versions - Content display

    /// Version of the Figma specifications for the component bullet list (1.0.0)
    public static let componentBulletListVersion = "1.0.0" // NOTE: #1473 - v1.1.0 not implemented yet

    // MARK: - Components versions - Control

    /// Version of the Figma specifications for the component checkbox (2.4.0)
    public static let componentCheckboxVersion = "2.4.0"
    /// Version of the Figma specifications for the component filter chip (1.3.0)
    public static let componentFilterChipVersion = "1.3.0" // NOTE: #1473 - v1.4.0 not implemented yet
    /// Version of the Figma specifications for the component suggestion chip (1.3.0)
    public static let componentSuggestionChipVersion = "1.3.0" // NOTE: #1473 - v1.4.0 not implemented yet
    /// Version of the Figma specifications for the component filter chip expand (1.3.0)
    public static let componentFilterChipExpandVersion = "1.3.0" // NOTE: #1473 - v1.4.0 not implemented yet
    /// Version of the Figma specifications for the component radio button (1.4.0)
    public static let componentRadioButtonVersion = "1.4.0"
    /// Version of the Figma specifications for the component switch (1.5.0)
    public static let componentSwitchVersion = "1.5.0"
    /// Version of the Figma specifications for the component text input (1.3.0)
    public static let componentTextInputVersion = "1.3.0" // NOTE: #1473 - v1.4.0 not implemented yet
    /// Version of the Figma specifications for the component phone number input (1.3.0)
    public static let componentPhoneNumberInputVersion = "1.3.0"
    /// Version of the Figma specifications for the component password input (1.3.0)
    public static let componentPasswordInputVersion = "1.3.0"
    /// Version of the Figma specifications for the component pin code input (1.3.0)
    public static let componentPinCodeInputVersion = "1.3.0"
    /// Version of the Figma specifications for the component quantity input (1.3.0)
    public static let componentQuantityInputVersion = "1.3.0"
    /// Version of the Figma specifications for the component select input (1.3.0)
    public static let componentSelectInputVersion = "1.3.0"
    /// Version of the Figma specifications for the component text area (1.0.0)
    public static let componentTextAreaVersion = "1.1.0" // NOTE: #1473 - v1.2.0 not implemented yet

    // MARK: - Components versions - Dialog

    /// Version of the Figma specifications for the component alert (alert message)  (1.1.0)
    public static let componentAlertMessageVersion = "1.1.0"
    /// Version of the Figma specifications for the component alert (inline alert) (1.0.0)
    public static let componentInlineAlertVersion = "1.0.0"

    // MARK: - Components versions - Layout

    /// Version of the Figma specifications for the component divider (1.0.0)
    public static let componentDividerVersion = "1.0.0"

    // MARK: - Components versions - Navigation

    /// Version of the Figma specifications for the component link (2.2.0)
    public static let componentLinkVersion = "2.2.0"
    /// Version of the Figma specifications for the component expand link (2.3.0)
    public static let componentExpandLinkVersion = "2.3.0"
    /// Version of the Figma specifications for the tab bar components (1.0.0)
    public static let componentTabBarVersion = "1.0.0"
    /// Version of the Figma specifications for the toolbar top components (1.0.0)
    public static let componentToolBarTopVersion = "1.0.0"
    /// Version of the Figma specifications for the toolbar bottom components (1.0.0)
    public static let componentToolBarBottomVersion = "1.0.0"

    // MARK: - Components versions - Tag

    /// Version of the Figma specifications for the component badge (1.2.0)
    public static let componentBadgeVersion = "1.2.0"
    /// Version of the Figma specifications for the component skeleton (1.0.0)
    public static let componentSkeletonVersion = "1.0.0"
    /// Version of the Figma specifications for the component tag (1.4.0)
    public static let componentTagVersion = "1.4.0" // NOTE: #1473 - v1.5.0 not implemented yet

    // MARK: - Components versions - Visual assets

    // No version for "icon" component in "visual assets" category
}
