name: Check Localizables

on:
  # For protected and most important branches
  push:
    branches:
      - main
      - develop

  # Pull request events
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  i18n:
    name: Check translations (Swift Polyglot)
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Clone SwiftPolyglot
        run: git clone -b 1.1.0 https://github.com/appdecostudio/SwiftPolyglot.git

      - name: Build and Run SwiftPolyglot
        run: |
          swift build --package-path ./SwiftPolyglot --configuration release
          swift run --package-path ./SwiftPolyglot swiftpolyglot en fr --error-on-missing